/** Upstream weapon effect tables, in matching French and English order. */
export const NARRATIVE_EFFECTS_FR = [
    'Silencieux intégré', 'Chargeur étendu', 'Visée laser', 'Canon renforcé',
    'Poignée ergonomique', 'Gravure personnalisée', 'Lame dentelée', 'Contrepoids parfait',
    'Détecteur de mouvement', 'Système anti-recul', 'Revêtement antireflet', 'Lame vibrante',
    'Mécanisme de rechargement rapide', 'Canon long précision', 'Fibre optique de visée',
    'Crosse pliable', 'Munitions perforantes', 'Chargeur rotatif', 'Système de visée intelligente',
    'Compensateur de recul magnétique', 'Rail Picatinny modifié', 'Canon flottant stabilisé',
    'Système de tir sélectif amélioré', 'Poignée chauffante', 'Garde-main ventilé',
    'Lunette thermique compacte', 'Embout de canon fileté', 'Ressort de détente allégé',
    'Détente progressive', 'Système de sûreté biométrique', 'Canon traité antifriction',
    'Chargeur translucide', 'Sangle tactique trois points', 'Lampe stroboscopique',
    'Pointeur infrarouge', 'Bipied rétractable', 'Cache-flamme', 'Canon lourd précision',
    'Système de refroidissement intégré', 'Munitions traçantes', 'Lame empoisonnable',
    'Garde en fibre de carbone', 'Pommeau lesté', 'Tranchant monofilament partiel',
    'Fourreau magnétique', 'Système de dégainage rapide', 'Renfort anti-vibration',
    'Poignée en peau de dragon synthétique', 'Lame à plasma basse énergie',
    'Système de retour tactile', 'Amortisseur de choc intégré', 'Mécanisme anti-désarmement',
    'Revêtement camouflage actif', 'Système de comptage de munitions', 'Extracteur de douilles amélioré',
    'Canon interchangeable', 'Poignée à mémoire de forme', 'Système de nettoyage auto',
    'Alliage ultra-léger', 'Renfort structurel titane', 'Système de verrouillage rapide',
    'Marquage holographique', 'Revêtement phosphorescent', 'Détecteur de cible ami/ennemi',
    'Système de guidage assisté', 'Correcteur de trajectoire', 'Amplificateur de force',
    'Mécanisme silencieux', 'Lame rétractable secondaire', 'Garde électrifiée',
    'Système de fixation magnétique', 'Revêtement anti-empreintes', 'Canon court tactique',
    'Chargeur drum haute capacité', 'Détente à deux temps', 'Compensateur vertical',
    'Rail latéral accessoire', 'Dispositif de brouillage balistique', 'Lance-fumigène intégré',
    'Lunette à amplification de lumière', 'Système de recul zéro', 'Canon ventilé céramique',
    'Poignée antidérapante nano', 'Système de mise à feu électronique',
    'Module de tir en rafale contrôlée', 'Viseur à point rouge', 'Canon renforcé carbone',
    'Système de verrouillage de culasse', 'Extracteur de chaleur', 'Lame auto-aiguisante',
    'Tranchant dentelé inversé', 'Renfort de pommeau tactique', 'Système de lancer assisté',
    'Grip magnétique palmaire', 'Système de neutralisation non-létale', 'Fil monofilament rétractable',
    'Capteur de pression de détente', 'Revêtement auto-réparant', 'Micro-gyroscope stabilisateur',
    'Module de tir furtif',
  ];
export const NARRATIVE_EFFECTS_EN = [
    'Integrated silencer', 'Extended magazine', 'Laser sight', 'Reinforced barrel',
    'Ergonomic grip', 'Custom engraving', 'Serrated blade', 'Perfect counterweight',
    'Motion detector', 'Anti-recoil system', 'Anti-glare coating', 'Vibrating blade',
    'Quick reload mechanism', 'Long precision barrel', 'Fiber optic sight',
    'Folding stock', 'Armor-piercing ammo', 'Rotary magazine', 'Smart targeting system',
    'Magnetic recoil compensator', 'Modified Picatinny rail', 'Free-floating stabilized barrel',
    'Enhanced selective fire system', 'Heated grip', 'Ventilated handguard',
    'Compact thermal scope', 'Threaded barrel tip', 'Lightened trigger spring',
    'Progressive trigger', 'Biometric safety system', 'Friction-treated barrel',
    'Translucent magazine', 'Three-point tactical sling', 'Strobe flashlight',
    'Infrared pointer', 'Retractable bipod', 'Flash hider', 'Heavy precision barrel',
    'Integrated cooling system', 'Tracer rounds', 'Poisonable blade',
    'Carbon fiber guard', 'Weighted pommel', 'Partial monofilament edge',
    'Magnetic scabbard', 'Quick-draw system', 'Anti-vibration reinforcement',
    'Synthetic dragon skin grip', 'Low-energy plasma blade',
    'Tactile feedback system', 'Integrated shock absorber', 'Anti-disarm mechanism',
    'Active camo coating', 'Ammo counter system', 'Enhanced shell extractor',
    'Interchangeable barrel', 'Shape-memory grip', 'Self-cleaning system',
    'Ultra-light alloy', 'Titanium structural reinforcement', 'Quick-lock system',
    'Holographic marking', 'Phosphorescent coating', 'Friend/foe target detector',
    'Assisted guidance system', 'Trajectory corrector', 'Force amplifier',
    'Silent mechanism', 'Secondary retractable blade', 'Electrified guard',
    'Magnetic attachment system', 'Anti-fingerprint coating', 'Tactical short barrel',
    'High-capacity drum magazine', 'Two-stage trigger', 'Vertical compensator',
    'Side accessory rail', 'Ballistic jamming device', 'Integrated smoke launcher',
    'Light amplification scope', 'Zero-recoil system', 'Ceramic vented barrel',
    'Nano non-slip grip', 'Electronic firing system',
    'Controlled burst module', 'Red dot sight', 'Carbon-reinforced barrel',
    'Bolt lock system', 'Heat extractor', 'Self-sharpening blade',
    'Reverse serrated edge', 'Tactical pommel reinforcement', 'Assisted throwing system',
    'Palm magnetic grip', 'Non-lethal neutralization system', 'Retractable monofilament wire',
    'Trigger pressure sensor', 'Self-repairing coating', 'Micro-gyroscope stabilizer',
    'Stealth fire module',
  ];
