/**
 * Japanese descriptions for the NPC generator's gear templates.
 *
 * The companion of npc-generator-data-ja.ts, split off because the
 * descriptions are an order of magnitude larger than the names and reviewing
 * them in the same file would be impractical. The key is the same: the
 * upstream French `name`, nested under featType, for the reasons set out in
 * that file's header.
 *
 * Every value carries the same <p> markup as the source description. The
 * generator writes it straight into the item's description field, which
 * Foundry renders as HTML, so a dropped or unbalanced tag would be visible on
 * the sheet. npc-generator-descs-ja.test.ts checks the tag sequence of every
 * entry against the upstream description it replaces.
 *
 * A template with no entry here falls back to English, exactly as before.
 */

export const FEAT_DESCS_JA: Record<string, Record<string, string>> = {
  armor: {
    'Veste synthécuir renforcée': '<p>控えめな弾道インサートを仕込んだ合成皮革のジャケット。</p>',
    'Hoodie blindé UrbanWall': '<p>弾道繊維の裏地を備えたフーディ。</p>',
    'T-shirt renforcé IronThread': '<p>パラアラミド繊維製のTシャツ。軽量で目立たない。</p>',
    'Blouson de moto SteetHide': '<p>肘にプロテクターを備えた複合皮革のバイカージャケット。</p>',
    'Chemise blindée CorpoGuard': '<p>弾道繊維を織り込んだ上品なドレスシャツ。企業との会談に最適。</p>',
    'Gilet pare-balles Apex Shield': '<p>衣服の下に着込む軽量の防弾ベスト。</p>',
    'Veste tactique ShadowVest': '<p>着脱可能なセラミックプレートを備えた黒のタクティカルジャケット。</p>',
    'Pardessus blindé TrenchLine': '<p>弾道裏地と強化された襟を備えたロングコート。</p>',
    'Combinaison de course RunShield': '<p>関節部にプロテクターを内蔵したスポーツスーツ。</p>',
    'Gilet de sécurité WatchGuard': '<p>レベル III の弾道プレートを備えた民間警備用ベスト。</p>',
    'Manteau blindé NightShield': '<p>セラミックプレートを内蔵したロングコート。スタイルと防護を兼ね備える。</p>',
    'Armure urbaine StreetFort': '<p>交換可能なプレートを備えたモジュール式のアーバンアーマー一式。</p>',
    "Combinaison d'assaut StormSuit": '<p>敵性環境での作戦用に強化されたスーツ。</p>',
    'Cape blindée IronCape': '<p>弾道防護を備えた複合繊維製のロングクローク。</p>',
    'Armure corporelle tactique TacForce': '<p>軍用級のフル・ボディアーマー。目立たないどころではない。</p>',
    'Armure de combat Vanguard': '<p>弾道防護と対破片防護を備えたフル・コンバットアーマー。</p>',
    'Exosquelette léger FrameGuard': '<p>装甲プレートを統合した部分的なエクソスケルトン。</p>',
    'Armure anti-émeute RiotMax': '<p>強化バイザーを備えた重装の暴動鎮圧アーマー。</p>',
    'Exo-armure lourde Titan': '<p>部分的なエクソスケルトンを備えた重装甲。企業の特殊部隊が使用する。</p>',
    'Armure de siège Bulwark': '<p>正面突撃と制圧のために設計された超重装甲。</p>',
    'Gilet urbain NeoWeave': '<p>軽量な NeoWeave 繊維のベスト。バレンズでの日常に最適。</p>',
    'Poncho blindé DustRunner': '<p>再生ケブラーの裏地を備えたゆったりしたポンチョ。ノマドに人気。</p>',
    'Plastron discret SlimPlate': '<p>シャツの下に着込む極薄のチェストガード。ほぼ探知されない。</p>',
    'Veste cargo ToughLine': '<p>肩と胴を補強した頑丈なカーゴジャケット。</p>',
    'Bandana blindé StreetWrap': '<p>首と顔の下半分を覆う弾道繊維のバンダナ。</p>',
    'Duster blindé RoadWarden': '<p>裏地に軽量プレートを縫い込んだロードコート。</p>',
    'Blouson de vol ArmorWing': '<p>腕と背にセラミック補強を備えたパイロットジャケット。</p>',
    'Combinaison ouvrière ForgeSkin': '<p>弾道補強を統合した難燃性の作業用カバーオール。</p>',
    'Kimono renforcé SilkSteel': '<p>合成スパイダーシルク製の伝統的な着物。刃物に強い。</p>',
    'Parka arctique IceShell': '<p>装甲を内蔵した断熱パーカ。寒冷地作戦用に設計された。</p>',
    'Armure modulaire HexPlate': '<p>複合セラミックの六角プレートで構成された装甲。任務ごとに再構成できる。</p>',
    'Harnais de combat WarRig': '<p>着脱可能な装甲プレートと装備取付点を備えた重装タクティカルハーネス。</p>',
    'Robe de combat mystico-blindée ArcaneVeil': '<p>弾道繊維とマナ伝導フィラメントを織り込んだロングローブ。</p>',
    "Plastron d'assaut CrashCore": '<p>衝撃吸収機構を内蔵した大型の軽合金チェストプレート。</p>',
    'Armure intégrale BunkerSuit': '<p>自立式の空気濾過システムを備えた密閉式フル・ボディアーマー。</p>',
    'Carapace de sécurité SentinelShell': '<p>メガコープの精鋭警備兵が用いる硬質カラパス。</p>',
    'Armure de tranchée IronBastion': '<p>強化されたすね当てと喉当てを備えた重装の陣地防御用アーマー。</p>',
    'Combinaison blindée OgreMail': '<p>トロールの中世装甲に着想を得た、複合素材を重ねた鎖帷子のスーツ。</p>',
    'Armure de puissance Juggernaut': '<p>サーボモーターと強化セラミック装甲を備えた軍用クラスのパワードアーマー。</p>',
    'Exo-blindage Colossus': '<p>エクソスケルトンに搭載する大型の外部装甲。都市の破壊作戦用に設計された。</p>',
  },
  cyberdeck: {
    'Cyberdeck Ghostline 3700': '<p>中級のサイバーデッキ。ファイアウォールと攻撃力のバランスが良い。</p>',
    'Cyberdeck PixelWave Starter': '<p>入門用のサイバーデッキ。初心者デッカーに最適。</p>',
    'Cyberdeck DataForge Mk.I': '<p>頑丈で信頼できるモデル。フリーランサーに人気。</p>',
    'Cyberdeck NovaPulse Runner': '<p>敵性地帯での機動性に最適化された小型サイバーデッキ。</p>',
    'Cyberdeck GridRunner Eco': '<p>直感的なインターフェースと低消費電力を備えた廉価モデル。</p>',
    'Cyberdeck OmniDyne Pulse': '<p>日常的なハッキング作業向けの汎用サイバーデッキ。</p>',
    'Cyberdeck ShadowByte Mini': '<p>市場で最小のサイバーデッキ。ポケットに収まる。</p>',
    'Cyberdeck TechHive Basic': '<p>量産された基本サイバーデッキ。信頼できるが飾りはない。</p>',
    'Cyberdeck Prism Nexus': '<p>強化ファイアウォールと高度な攻撃モジュールを備えた高級サイバーデッキ。</p>',
    'Cyberdeck Ghostline 9000 Elite': '<p>量子プロセッサを統合した Ghostline の上位版。</p>',
    'Cyberdeck BlackVeil Phantom': '<p>企業ネットワークへの不可視侵入のために設計されたステルス・サイバーデッキ。</p>',
    'Cyberdeck Kurotech Ronin X': '<p>最適化されたニューラル・インターフェースを備えた日本製の精密サイバーデッキ。</p>',
    'Cyberdeck DataForge Mk.III Pro': '<p>第三世代の DataForge。攻撃と防御のモジュールが均衡している。</p>',
    'Cyberdeck Meridian Warframe': '<p>民間市場向けに転用された軍用サイバーデッキ。素の性能は比類ない。</p>',
    'Cyberdeck NovaPulse Apex': '<p>マルチコア・プロセッサと能動的熱拡散を備えた NovaPulse の最上位機。</p>',
    'Cyberdeck VortexNet Razor': '<p>専用の総当たりモジュールを備え、攻撃的サイバー戦闘に最適化されている。</p>',
    'Cyberdeck SpectraCorp Sentinel': '<p>多層ファイアウォールと高度な侵入検知を備えた防御型サイバーデッキ。</p>',
    'Cyberdeck ZeroDay Exploit': '<p>ハッカーがハッカーのために設計した。個体ごとに仕様が異なる。</p>',
    'Cyberdeck OmniDyne Titan': '<p>最強の民間サイバーデッキ。軍用機材に匹敵する。</p>',
    'Cyberdeck ShadowByte Wraith': '<p>マトリックス上の痕跡がほぼ探知されない超ステルス・サイバーデッキ。</p>',
    'Cyberdeck StreetSpark Lite': '<p>金のないハッカー向けの超簡素なサイバーデッキ。ソイカフの缶に収まる。</p>',
    'Cyberdeck BinaryBudget V2': '<p>Budget シリーズの第二モデル。相応のファイアウォールを備えた防御寄り。</p>',
    'Cyberdeck NeonFlicker': '<p>ネオン LED を備えた派手なサイバーデッキ。地下クラブで人気。</p>',
    'Cyberdeck RustBucket Mk.II': '<p>錆びて見えるが機能する。廃品から組み上げられた品。</p>',
    'Cyberdeck WaveRider Compact': '<p>マトリックス巡航用の小型サイバーデッキ。軽量で目立たない。</p>',
    'Cyberdeck CipherNode Entry': '<p>暗号化と秘匿性に重点を置いた入門モデル。</p>',
    'Cyberdeck SubNet Crawler': '<p>マトリックスの忘れられた下層網の探索に特化している。</p>',
    'Cyberdeck HoloJack Slim': '<p>没入感のあるハッキング体験のためのホログラフィック・インターフェースを統合。</p>',
    'Cyberdeck ProbeLight Scanner': '<p>戦闘よりもネットワークの偵察と走査に最適化されている。</p>',
    'Cyberdeck IronClad Pocket': '<p>防御作戦向けの堅固なファイアウォールを備えたポケット・サイバーデッキ。</p>',
    'Cyberdeck QuantumEdge Sigma': '<p>マトリックス演算を超高速で行う最新世代の量子プロセッサ。</p>',
    'Cyberdeck NightFall Stealth': '<p>マトリックス上の痕跡が最小限のステルス・サイバーデッキ。侵入に最適。</p>',
    'Cyberdeck HyperVault Fortress': '<p>三重のファイアウォール層と量子隔離を備えたデジタル要塞。</p>',
    'Cyberdeck StrikeForce Omega': '<p>専用の攻撃モジュールを備え、攻撃的サイバー戦闘のために設計された。</p>',
    'Cyberdeck CrystalMind Nexus': '<p>完全に澄んだマトリックス接続を実現する結晶製ニューラル・インターフェース。</p>',
    'Cyberdeck TempestWare Havoc': '<p>敵性プログラムへ自動で反撃する軍用サイバーデッキ。</p>',
    'Cyberdeck NebulaCore Prime': '<p>NebulaCore の最上位機。市場で最強の民間用マトリックス・プロセッサ。</p>',
    'Cyberdeck VoidRunner Eclipse': '<p>マトリックス基盤への深層ダイブに最適化されている。</p>',
    'Cyberdeck ArcticByte Glacier': '<p>極端なオーバークロックを可能にする冷凍式の熱拡散。</p>',
    'Cyberdeck PhantomLink Ultra': '<p>追跡不能な幻影マトリックス接続。プロの選択。</p>',
  },
  awakened: {
    'Éveillé — Perception et Sorcellerie': '<p>このキャラクターは覚醒者である。アストラル界を知覚し、呪文を行使できる。</p>',
    'Éveillé — Perception, Sorcellerie et Conjuration': '<p>このキャラクターは覚醒者である。アストラル知覚、呪術、精霊の召喚を行える。</p>',
    'Éveillé — Projection astrale et Conjuration': '<p>このキャラクターはシャーマンである。アストラル投射と精霊の召喚を行える。</p>',
    'Éveillé — Perception astrale et Adepte': '<p>このキャラクターはフィジカル・アデプトである。マナを自らの肉体に通す。</p>',
  },
  emerged: {
    'Émergé — Persona vivante': '<p>このキャラクターはエマージドである。思考によってマトリックスに接続し、コンプレックス・フォームを編成する。</p>',
  },
  weapon: {
    'Couteau de combat Valkyr KS-3': '<p>カーバイドで補強された短い刃。</p>',
    'Dague Neon Arms Fang': '<p>両刃の複合セラミック製ダガー。</p>',
    'Couteau de survie Meridian Claw': '<p>鋸歯の刃を備えた頑丈なサバイバルナイフ。</p>',
    'Couteau papillon OmniDyne Flicker': '<p>磁力展開による超高速のバタフライナイフ。</p>',
    'Stiletto Apex Venom': '<p>装甲の隙間を狙って設計された細い刺突用の刃。</p>',
    'Lame rétractable Kurotech Razor': '<p>黒色チタン製の伸縮式スイッチブレード。</p>',
    'Machette Prismex Bushmaster': '<p>厚い刃を備えた汎用の短いマチェット。</p>',
    'Couteau de lancer NovaPulse Dart': '<p>投擲にも近接戦闘にも使える均衡の取れたナイフ。</p>',
    'Tanto Kurogane Ghost': '<p>炭素処理鋼による日本の短刀。</p>',
    'Kriss Titan Arms Serpent': '<p>切断用合金で現代化された伝統的な波状の刃。</p>',
    'Katana Kurogane Type-4': '<p>分子鋼の刀。剃刀のように鋭い。</p>',
    'Épée large Titan Arms Claymore': '<p>両手持ちの強化合金剣。近接戦で壊滅的。</p>',
    'Sabre Meridian Hussar': '<p>現代化された騎兵サーベル。軽く鋭い。</p>',
    'Rapière NovaPulse Estoc': '<p>超軽量のカーボンファイバー製フェンシング・レイピア。</p>',
    'Nodachi Kaze Tempest': '<p>間合いに優れた長大な両手持ちの日本刀。</p>',
    'Cimeterre Apex Crescent': '<p>斬撃に最適化された湾曲したシミター。</p>',
    'Épée vibrante Prismex Resonance': '<p>軽装甲を斬り裂く超音波振動の長刃。</p>',
    'Machette longue Valkyr Jungle King': '<p>敵性環境向けの厚刃のロングマチェット。</p>',
    'Batte renforcée Ironside': '<p>鉛の芯を備えた複合合金のバット。</p>',
    'Massue Titan Arms Ogre': '<p>フランジ付きの頭部を備えた重い焼入鋼のメイス。</p>',
    'Marteau NovaPulse Sledge': '<p>強化された頭部を備えた小型のウォーハンマー。</p>',
    'Nunchaku Kaze Whirlwind': '<p>収納式の鎖を備えた硬質ポリマーのヌンチャク。</p>',
    'Matraque télescopique Apex Enforcer': '<p>三段式の伸縮バトン。素早く展開できる。</p>',
    'Tonfas Meridian Guardian': '<p>カーボンファイバー製のトンファー一対。防御と攻撃の双方に使える。</p>',
    'Bâton bo Kurotech Sensei': '<p>収納式のチタン合金製の棒。</p>',
    'Morgenstern Valkyr Brute': '<p>棘付きの球を備えたフレイル。残虐で止められない。</p>',
    'Matraque shock Zapper': '<p>高電圧の電撃バトン。</p>',
    'Taser Neon Arms Volt': '<p>近距離用のパルス式テーザー。軽装甲にも有効。</p>',
    'Gants shock OmniDyne Thunder': '<p>接触時に放電する強化グローブ。</p>',
    'Fouet électrique Prismex Arc': '<p>打撃ごとに電撃を与える導電性のウィップ。</p>',
    'Lance shock Kaze Storm': '<p>高電圧で通電する先端を備えた絶縁ランス。</p>',
    'Lame monofilament Whisper': '<p>収納式のモノフィラメント・ウィップ。ほぼ何でも斬り裂く。</p>',
    'Chaîne monofilament Kurotech Reaper': '<p>モノフィラメントの鎖。専門家向けの武器。</p>',
    'Gantelet à griffes Apex Predator': '<p>収納式の単分子合金の爪を備えたガントレット。</p>',
    'Éventail de combat Kaze Mantis': '<p>刃を隠した鉄扇。優雅で致命的。</p>',
    'Kusarigama NovaPulse Shadow': '<p>重りを付けた鎖と鎌。伝統的な武器を現代化したもの。</p>',
    'Arts martiaux : Karaté Kurotech': '<p>強力な打撃に重点を置いた空手の修練。</p>',
    'Arts martiaux : Muay Thaï Kaze': '<p>壊滅的な肘と膝の技。</p>',
    'Arts martiaux : Krav Maga Valkyr': '<p>残忍で効率的な護身術。飾りはない。</p>',
    "Poings d'acier Titan Arms": '<p>重い焼入鋼のナックル。</p>',
    'Arts martiaux : Jiu-Jitsu NovaPulse': '<p>関節技と寝技による制圧の技。</p>',
    'Pied-de-biche Meridian Leverage': '<p>強化されたバール。工具にも即席の武器にもなる。</p>',
    'Chaîne lourde Titan Arms Anchor': '<p>即席のフレイルとして使う重い鎖。</p>',
    'Tuyau en acier Apex Sewer King': '<p>拾った鉄パイプ。ストリートの武器の代表格。</p>',
    'Clé à molette Prismex Wrecker': '<p>特大のパイプレンチ。重く恐ろしい。</p>',
    'Bouteille cassée Neon Arms Last Call': '<p>強化ガラスの割れた瓶。酒場の定番武器。</p>',
    'Lames de poignet Kurotech Mantis': '<p>前腕に埋め込まれた収納式の刃。</p>',
    'Griffes cyber Apex Lynx': '<p>爪の下に仕込んだサイバネティックな爪。常に隠されている。</p>',
    'Éperon cybernétique OmniDyne Spike': '<p>不意打ち用の収納式の肘スパイク。</p>',
    'Main-lame Valkyr Edge': '<p>手のひらに統合された刃。瞬時に展開する。</p>',
    'Couteau tactique Meridian Talon': '<p>反射を抑えた黒い刃のタクティカルナイフ。</p>',
    'Kukri NovaPulse Gorkhali': '<p>強化された湾曲刃を備えた現代化ネパール製ククリ。</p>',
    'Couteau Bowie Titan Arms Frontier': '<p>高性能ステンレス鋼の大型ボウイナイフ。</p>',
    'Couteau céramique Kaze Silent': '<p>全セラミック製のナイフ。金属探知機では探知できない。</p>',
    'Karambit Apex Scorpion': '<p>湾曲刃のカランビット。近接戦の技法のために設計された。</p>',
    'Dirk OmniDyne Highland': '<p>直線的で耐久性のある合金刃を備えたスコットランドのダーク。</p>',
    'Couteau pliant Neon Arms Switchback': '<p>ベルトクリップ付きの開刃補助機構を備えた折りたたみナイフ。</p>',
    'Couteau de plongée Prismex Depth': '<p>鋸歯の刃を備えた防蝕のダイビングナイフ。</p>',
    'Poignard trench Valkyr Doughboy': '<p>ナックルガードを統合したトレンチナイフ。</p>',
    'Lame dissimulée Kurotech Shade': '<p>ペンに隠した極薄の刃。探知されない。</p>',
    'Épée bâtarde Titan Arms Conquest': '<p>片手半剣。汎用性が高く壊滅的。</p>',
    'Falchion Apex Cleaver': '<p>厚く幅広の刃を備えたファルシオン。強力な打撃に最適。</p>',
    'Wakizashi Kaze Moonlight': '<p>折り返し鍛錬の鋼による日本の脇差。</p>',
    'Gladius NovaPulse Centurion': '<p>現代化されたローマのグラディウス。短く扱いやすい。</p>',
    'Épée laser Prismex Photon': '<p>封じ込めたプラズマの刃。中装甲を斬り裂く。</p>',
    'Flamberge OmniDyne Inferno': '<p>波状の刃を持つ剣。治りにくい傷を与える。</p>',
    'Dao Kurotech Dragon': '<p>片刃の中国の青龍刀。素早い連撃に合わせて調整されている。</p>',
    'Claymore vibro Valkyr Earthquake': '<p>震動を伝えるクレイモア。打撃ごとに骨まで響く。</p>',
    'Kanabo Kaze Oni': '<p>複合鋼による棘付きの日本の金棒。</p>',
    "Fléau d'armes Titan Arms Crusher": '<p>二つの球を備えた戦闘フレイル。衝撃は壊滅的。</p>',
    'Matraque tactique NovaPulse Pacifier': '<p>重量級の暴動鎮圧用バトン。堅牢で威圧的。</p>',
    "Masse d'armes Meridian Paladin": '<p>六角の頭部を備えた戦闘メイス。装甲を打ち破る。</p>',
    'Bâton escrima Apex Dual Strike': '<p>堅木とカーボンファイバーのエスクリマ・スティック一対。</p>',
    'Marteau de guerre Prismex Goliath': '<p>タングステンの頭部を備えた重いウォーハンマー。</p>',
    'Bokken OmniDyne Senshi': '<p>強化された稽古用の木刀。鋼のように硬い。</p>',
    'Batte cloutée Neon Arms Basher': '<p>釘を打ち込んだ野球バット。ギャングを象徴する武器。</p>',
    'Taser longue portée Apex Bolt': '<p>射程を 10 メートルまで延伸したダート式テーザー。</p>',
    'Bâton choc Valkyr Thunderstrike': '<p>二箇所の接触点を備えた通電する長棒。</p>',
    'Poing shock Kurotech Jolt': '<p>放電機構を統合したナックル。</p>',
    'Filet électrifié NovaPulse NetShock': '<p>対象を拘束して感電させる導電性のネット。</p>',
    'Lasso shock Meridian Lariat': '<p>接触時に高電圧を流す導電性のラッソ。</p>',
    'Chaîne-faucille Titan Arms Harvester': '<p>モノフィラメントの刃を備えた重りつきの鎖鎌。</p>',
    'Urumi Kaze Serpent': '<p>しなやかなインドのばね鋼の剣。予測しがたく致命的。</p>',
    'Tekko-kagi NovaPulse Shadow Hand': '<p>単分子合金による忍びの手甲鉤。</p>',
    'Sai Prismex Trident': '<p>チタン製の釵一対。武器落としと打撃に最適。</p>',
    'Fouet à lame Valkyr Hydra': '<p>刃を組み込んだ分節式のウィップ。間合いと切り裂きを兼ねる。</p>',
    'Arts martiaux : Wing Chun Apex': '<p>手の速さと近距離戦に重点を置いた流派。</p>',
    'Arts martiaux : Capoeira Meridian': '<p>曲芸的なブラジルの武術。強力で予測しがたい蹴り。</p>',
    'Arts martiaux : Systema OmniDyne': '<p>流れるようなロシアの武術。関節技と投げ技を用いる。</p>',
    'Arts martiaux : Savate NovaPulse': '<p>優雅なフランスの拳闘。精確で技術的な蹴り。</p>',
    'Arts martiaux : Pencak Silat Kaze': '<p>インドネシアの武術。流れる動きと容赦のない打撃。</p>',
    'Extincteur Apex Firefight': '<p>即席の棍棒として使う重い消火器。</p>',
    'Barre à mine Kurotech Breaker': '<p>重い鋼の掘削バー。工事現場の恐るべき武器。</p>',
    "Panneau d'arrêt Neon Arms Halt": '<p>引き抜いた止まれ標識。ストリートを象徴する即席の武器。</p>',
    "Câble d'acier Prismex Garrote": '<p>絞殺用に使う撚り合わせた鋼製ケーブル。静かで致命的。</p>',
    'Clé en croix OmniDyne Roadkill': '<p>自動車用のクロスレンチ。頑丈で手に入りやすい。</p>',
    'Lame de doigt Kurotech Stiletto': '<p>人差し指に埋め込んだ収納式の極小の刃。</p>',
    'Lame de tibia NovaPulse Shin Edge': '<p>サイバネティックな脛から展開する刃。</p>',
    'Crocs cyber Apex Fang': '<p>切断用合金による強化されたサイバネティックな犬歯。</p>',
    'Queue cyber Prismex Tail Spike': '<p>収納式の棘を備えたサイバネティックな尾。究極の不意打ち武器。</p>',
    'Neon Arms Stiletto .22': '<p>小型のポケットピストル。隠し持ちやすい。</p>',
    'Prismex Whisper .25': '<p>消音機構を内蔵したピストル。潜入に最適。</p>',
    'OmniDyne Minnow .22LR': '<p>二連発のデリンジャー。手のひらに収まる。</p>',
    'Kaze Petal .22': '<p>超薄型のセラミック製ピストル。走査では探知できない。</p>',
    'Meridian Cricket .25': '<p>五発装弾の予備用小型ピストル。</p>',
    'Apex Sentinel 9mm': '<p>信頼できる軽量ピストル。分別のあるランナーの選択。</p>',
    'Valkyr P9 Compact': '<p>反動を抑えた小型の 9mm。扱いやすい。</p>',
    'Kurogane Sparrow 9mm': '<p>ホログラフィック照準器を統合した軽量ピストル。</p>',
    'NovaPulse Guardian 9mm': '<p>民間警備部隊の標準装備ピストル。</p>',
    'Titan Arms Deputy .38': '<p>古典的な軽量リボルバー。信頼でき安価。</p>',
    'Meridian Civic 9mm': '<p>普及した民間向けピストル。低価格で量産されている。</p>',
    'Neon Arms Lynx 9mm': '<p>タクティカルレイルと制退器を備えた軽量ピストル。</p>',
    'Prismex Halo 9mm': '<p>クローム仕上げと延長弾倉を備えた意匠性の高いピストル。</p>',
    'Valkyr HK-7': '<p>発射選択機構を備えた小型の自動ピストル。</p>',
    'Kurogane Rapid 10mm': '<p>延長弾倉を備えた高速連射の自動ピストル。</p>',
    'Apex Staccato Auto': '<p>折りたたみ銃床を備えたポケット・マシンピストル。</p>',
    'Meridian Tempest Auto': '<p>反動制退器を統合した自動ピストル。</p>',
    'NovaPulse Burst-9': '<p>三点射のピストル。精確で制御しやすい。</p>',
    'Apex Ironside .44': '<p>重量級のリボルバー。轟音と痛みを伴う。</p>',
    'Titan Arms Rhino .45': '<p>強化銃身を備えた重量級の半自動ピストル。</p>',
    'Valkyr Warhawk .44 Magnum': '<p>大型のマグナム・リボルバー。素の制圧力に優れる。</p>',
    'Kurogane Enforcer 10mm': '<p>複列弾倉を備えた重量級の 10mm ピストル。</p>',
    'Neon Arms Nomad .50': '<p>口径 .50 のピストル。反動は凶暴だがダメージは絶大。</p>',
    'Meridian Judge .357': '<p>つや消し鋼の汎用重量級リボルバー。</p>',
    'Prismex Dominator .45 ACP': '<p>競技用の重量級ピストル。精度と威力を兼ね備える。</p>',
    'Valkyr Pixie .22': '<p>短銃身の超小型ポケットピストル。</p>',
    'Titan Arms Mouse .25': '<p>強化ポリマー製の極小ピストル。</p>',
    'Apex Wasp .22': '<p>安全装置を統合したダブルアクションのポケットピストル。</p>',
    'OmniDyne Protector 9mm': '<p>人間工学的な把持部と速装弾倉を備えた軽量ピストル。</p>',
    'Kaze Breeze 9mm': '<p>命中精度を高める浮動銃身を備えた日本製の軽量ピストル。</p>',
    'Titan Arms Scout .380': '<p>サブコンパクトの .380 ピストル。隠し持ちに最適。</p>',
    'Meridian Peacekeeper 9mm': '<p>企業の警備部隊が用いる信頼できる装備ピストル。</p>',
    'Kaze Typhoon Auto': '<p>連射速度可変で点射機構を備えた自動ピストル。</p>',
    'Titan Arms Rattler Auto': '<p>銃口制退器を統合した小型マシンピストル。</p>',
    'Prismex Torrent Auto': '<p>螺旋弾倉を備えた高速連射の自動ピストル。</p>',
    'OmniDyne Firestorm Auto': '<p>急速冷却機構を備えた自動ピストル。</p>',
    'Neon Arms Hornet Auto': '<p>超軽量の自動ピストル。移動しながらの射撃に最適。</p>',
    'OmniDyne Mammoth .50': '<p>大型の .50 口径ピストル。素の威力は比類ない。</p>',
    'Kaze Thunder .44': '<p>強化シリンダーと放気銃身を備えた重量級リボルバー。</p>',
    'NovaPulse Titan .45': '<p>高度な反動制退器を備えた重量級の半自動ピストル。</p>',
    'Neon Arms Colossus .454': '<p>怪物じみた .454 リボルバー。入手できる拳銃口径で最大。</p>',
    'Apex Executioner .50 AE': '<p>レーザー照準器を統合した .50 AE の半自動ピストル。</p>',
    'Kurotech Shogun .44': '<p>つや消し黒仕上げと長銃身を備えた日本製の重量級リボルバー。</p>',
    'Kurogane AR-77': '<p>標準的なアサルトライフル。汎用性が高く信頼できる。</p>',
    'Valkyr Commando 5.56': '<p>近接戦闘作戦向けの小型アサルトライフル。</p>',
    'Titan Arms Warrior 7.62': '<p>重量級のバトルライフル。口径 7.62 で火力に優れる。</p>',
    'Neon Arms Spectre 5.56': '<p>消音器を統合した小型のブルパップ式アサルトライフル。</p>',
    'Meridian Patriot 6.8': '<p>汎用レイル系を備えたモジュール式アサルトライフル。</p>',
    'Meridian Scorpio': '<p>ポンプ式のショットガン。近距離では壊滅的。</p>',
    'Titan Arms Boomstick': '<p>銃身を切り詰めたショットガン。小型で壊滅的。</p>',
    'Valkyr Breacher Auto-12': '<p>ドラム弾倉を備えた 12 番の半自動ショットガン。</p>',
    'Kurogane Street Sweeper': '<p>高速連射の回転式ショットガン。面の掃討を確実にする。</p>',
    'NovaPulse Marksman X': '<p>ジャイロ安定装置を備えた高性能スナイパーライフル。</p>',
    'Apex Longbow .338': '<p>二脚を統合した長距離精密ライフル。</p>',
    'Kurotech Phantom .50 BMG': '<p>重量級の対物ライフル。軽装甲を貫通する。</p>',
    'Valkyr Wraith SR': '<p>消音器とスマート照準器を備えたモジュール式スナイパーライフル。</p>',
    'Apex Warden 5.56': '<p>中距離の精度を高める重銃身の信頼できるアサルトライフル。</p>',
    'OmniDyne Centurion 6.5': '<p>中間口径 6.5 のバトルライフル。汎用性が高く精確。</p>',
    'Prismex Phantom 5.56': '<p>消音器とフリーフロート銃身を統合したステルス・アサルトライフル。</p>',
    'Kurotech Ronin 7.62': '<p>日本製の 7.62 バトルライフル。頑丈で壊滅的。</p>',
    'Apex Thunderclap': '<p>伸縮銃床を備えたポンプ式のタクティカル・ショットガン。</p>',
    'NovaPulse Hydra-12': '<p>反動を緩和する機構を備えた半自動ショットガン。</p>',
    'Neon Arms Riot Master': '<p>20 発のドラム弾倉を備えた暴動鎮圧用ショットガン。</p>',
    'Prismex Undertaker': '<p>上下二連式の双銃身ショットガン。壊滅的な二射を放つ。</p>',
    'Meridian Deadeye .308': '<p>熱線照準器を統合した .308 精密ライフル。</p>',
    'Titan Arms Basilisk .416': '<p>対物用の .416 ライフル。中装甲を貫通する。</p>',
    'OmniDyne Specter SR': '<p>熱光学迷彩機構を備えた分解式スナイパーライフル。</p>',
    'Neon Arms Reaper .338': '<p>ねじ切り銃身とカーボン二脚を備えた長距離精密ライフル。</p>',
    'Kaze Whisperwind .300': '<p>消音された .300 スナイパーライフル。極めて遠く、音は最小限。</p>',
    'Kurogane Viper SMG': '<p>小型のサブマシンガン。市街戦に最適。</p>',
    'Neon Arms Hornet SMG': '<p>超軽量で高速連射のサブマシンガン。</p>',
    'Apex Sidewinder PDW': '<p>収納式銃床を備えた小型の個人防衛火器。</p>',
    'Meridian Cyclone 10mm': '<p>頑丈な 10mm のサブマシンガン。制圧力に優れる。</p>',
    'Prismex Vector 9mm': '<p>平衡錘機構で反動を大幅に抑えたサブマシンガン。</p>',
    'Valkyr Tempest SMG': '<p>折りたたみ銃床と前方把持部を備えたタクティカル・サブマシンガン。</p>',
    'Titan Arms Bulldog PDW': '<p>小型で頑丈な個人防衛火器。ボディガードに好まれる。</p>',
    'OmniDyne Razor SMG': '<p>連射速度を調整できる軽量ポリマー製サブマシンガン。</p>',
    'Kurotech Whisper SMG': '<p>一体型の消音器と亜音速弾を用いる消音サブマシンガン。</p>',
    'Neon Arms Firefly SMG': '<p>大容量の螺旋弾倉を備えた極小のサブマシンガン。</p>',
    'Titan Arms Devastator': '<p>重機関銃。制圧を確実にする。</p>',
    'Apex Thunder Lance': '<p>六連発の半自動グレネードランチャー。</p>',
    'NovaPulse Hellfire ATRL': '<p>レーザー誘導の対戦車ロケットランチャー。一射で足りる。</p>',
    'Valkyr Annihilator LMG': '<p>水冷機構を備えた軽機関銃。</p>',
    'Meridian Hellstorm GL': '<p>12 連発の回転式自動グレネードランチャー。</p>',
    'Kurotech Raijin ATRL': '<p>赤外線捕捉機構を備えた携行式ロケットランチャー。</p>',
    'Couteaux de lancer Kaze': '<p>均衡の取れた投げナイフ一組。</p>',
    'Shurikens Kaze Eclipse': '<p>空力に優れた焼入鋼の手裏剣。</p>',
    'Grenades frag Apex': '<p>標準的な破片グレネード。</p>',
    'Grenades fumigènes Meridian Haze': '<p>速やかに拡散する催涙ガス・グレネード。</p>',
    'Haches de lancer Titan Arms Tomahawk': '<p>均衡の取れた焼入鋼の投斧。</p>',
    'Bolas Meridian Tangle': '<p>ケブラーの紐を備えた重りつきのボーラ。対象を拘束する。</p>',
    'Grenades flash Apex Sunburst': '<p>高輝度で視界を奪う閃光グレネード。</p>',
    'Grenades EMP NovaPulse Blackout': '<p>電磁パルス・グレネード。電子機器を無力化する。</p>',
  },
  spell: {
    'Boulon de mana': '<p>対象の精神を撃つ生のマナの弾。</p>',
    'Boule de feu': '<p>一定範囲に魔法の炎を炸裂させる。</p>',
    'Éclair': '<p>意志力によって導かれる壊滅的な電弧。</p>',
    'Flèche de givre': '<p>凝縮したマナから形成される貫通性の氷の弾。</p>',
    'Vague de choc': '<p>進路上のすべてを押し退ける同心円状の力の波。</p>',
    'Lance acide': '<p>術者の手のひらから放つ腐食性の酸の噴流。</p>',
    'Étouffement': '<p>対象の周囲の空気を圧縮して窒息させる。</p>',
    'Souffle du dragon': '<p>術者が吐き出す魔法の炎の円錐。</p>',
    'Décharge de mana': '<p>単一の対象へ魔力を乱暴に解き放つ。</p>',
    'Rayon désintégrateur': '<p>物質を分子単位で分解する純粋な力の光線。</p>',
    'Tempête de grêle': '<p>一定範囲に魔法の雹の雨を呼ぶ。</p>',
    'Frappe spectrale': '<p>物理的な障壁を通り抜けるアストラルの打撃。</p>',
    "Griffes d'ombre": '<p>対象を切り裂く影の刃を投射する。</p>',
    'Nova de mana': '<p>術者を中心とする球状の生のマナの爆発。</p>',
    "Chaîne d'éclairs": '<p>複数の対象の間を跳ね渡る電弧。</p>',
    'Poing de terre': '<p>地面から岩の拳を起こして対象を打つ。</p>',
    'Torrent de force': '<p>術者の前方のすべてを払う念動の波。</p>',
    'Pluie de cendres': '<p>対象範囲に白熱した灰の燃える雨を降らせる。</p>',
    'Dard venimeux': '<p>アストラルの毒を帯びたマナの投矢。</p>',
    'Rupture sonique': '<p>物質を砕く収束した音波。</p>',
    'Détection de la vie': '<p>広い半径内の生きたオーラを知覚する。</p>',
    Clairvoyance: '<p>定点を通して遠隔の知覚を可能にする。</p>',
    'Détection des ennemis': '<p>敵性の人物の存在と位置を明らかにする。</p>',
    'Vision astrale': '<p>アストラル界を知覚する能力を与える。</p>',
    'Sens du danger': '<p>差し迫った脅威を術者に警告する。</p>',
    'Détection de la magie': '<p>活動中の魔法と術の源を明らかにする。</p>',
    'Traque astrale': '<p>生物や呪文が残したアストラルの痕跡を辿る。</p>',
    'Cartographie mentale': '<p>周囲の空間の心的な地図を作る。</p>',
    "Analyse d'aura": '<p>対象のオーラを読み、感情と魔法の状態を判断する。</p>',
    'Écoute à distance': '<p>離れた地点の周囲の音を聞き取れるようにする。</p>',
    'Psychométrie': '<p>物体に残された心的な印象を読み取る。</p>',
    'Vision thermique': '<p>熱の痕跡を見る能力を与える。</p>',
    'Détection des esprits': '<p>召喚された、あるいは彷徨う精霊の存在を明らかにする。</p>',
    'Sonde mentale': '<p>対象の精神を探り、情報を引き出す。</p>',
    'Révélation des passages': '<p>付近の隠し扉と隠された通路を探知する。</p>',
    'Guérison': '<p>マナを通して傷の治癒を早める。</p>',
    Antidote: '<p>対象の体内の毒素と毒物を中和する。</p>',
    'Régénération': '<p>細胞の再生を促して傷を閉じる。</p>',
    Purification: '<p>対象の体内から病と感染を除去する。</p>',
    'Augmentation de réflexes': '<p>対象の反射を魔法によって加速する。</p>',
    'Résistance à la douleur': '<p>対象の痛みの感覚を抑える。</p>',
    Stabilisation: '<p>死にかけた者を安定させ、悪化を防ぐ。</p>',
    'Augmentation de force': '<p>対象の身体的な筋力を一時的に高める。</p>',
    "Augmentation d'agilité": '<p>対象の敏捷力を一時的に高める。</p>',
    "Vision de l'aigle": '<p>対象の視覚を自然の限界を超えて高める。</p>',
    'Second souffle': '<p>疲れ果てた対象の持久力と活力を取り戻す。</p>',
    'Protection contre les toxines': '<p>有毒物質を濾す魔法の障壁を作る。</p>',
    'Restauration cellulaire': '<p>損傷した組織を細胞単位で修復する。</p>',
    'Endurance du troll': '<p>物理ダメージに対する超常的な耐性を与える。</p>',
    'Transfert vital': '<p>術者の活力を傷ついた対象へ移す。</p>',
    'Invisibilité': '<p>対象を肉眼では見えないようにする。</p>',
    Chaos: '<p>対象たちの精神に混沌とした幻を生む。</p>',
    Confusion: '<p>対象の知覚と思考を撹乱する。</p>',
    'Double illusoire': '<p>敵を欺くために術者の幻の分身を作る。</p>',
    Masque: '<p>対象の外見を変える。</p>',
    Silence: '<p>対象の周囲に完全な静寂の領域を作る。</p>',
    Mirage: '<p>場所や物体の写実的な幻影を投射する。</p>',
    Terreur: '<p>対象の精神に悪夢の幻視を投射する。</p>',
    Camouflage: '<p>対象の色を周囲の環境に合わせる。</p>',
    'Hallucination de masse': '<p>複数の対象に共有された幻覚を生じさせる。</p>',
    'Éblouissement': '<p>対象の方向感覚を奪う目を焼く閃光。</p>',
    'Voix fantôme': '<p>選んだ地点に幻の声を投射する。</p>',
    'Mur illusoire': '<p>堅固な壁や障害物の幻を作る。</p>',
    'Cauchemar éveillé': '<p>対象を身動きできない白昼の悪夢に突き落とす。</p>',
    'Distorsion sensorielle': '<p>対象の感覚を予測しがたく変える。</p>',
    "Brouillard d'ombre": '<p>周囲を覆い隠す超常の霧を呼ぶ。</p>',
    'Faux mort': '<p>対象を疑いなく死んだように見せる。</p>',
    'Déplacement illusoire': '<p>対象が実際の位置から数メートル離れて見えるようになる。</p>',
    'Folie passagère': '<p>対象に短い狂気の発作を起こす。</p>',
    'Reflet trompeur': '<p>鏡や反射面が偽りの像を映すようになる。</p>',
    'Lévitation': '<p>意志力によって物体や人を持ち上げて動かす。</p>',
    'Armure magique': '<p>対象を守りのマナの盾で包む。</p>',
    'Contrôle des émotions': '<p>対象の感情を操る。</p>',
    'Télékinésie': '<p>精神の力で遠くの物体を動かす。</p>',
    'Verrou magique': '<p>扉や容器を魔法で封じる。</p>',
    "Contrôle de l'eau": '<p>付近の水の動きと形を操る。</p>',
    'Pétrification': '<p>対象の筋肉を一時的に硬直させる。</p>',
    "Animation d'objet": '<p>命のない物体を一時的に動かす。</p>',
    'Façonnage de la terre': '<p>術者の意志のままに土と石を作り変える。</p>',
    'Contrôle du feu': '<p>既にある炎を操り、その広がりを制御する。</p>',
    Poltergeist: '<p>対象範囲の物体を激しく揺り動かす。</p>',
    'Contrôle mental': '<p>対象の行動を一時的に支配する。</p>',
    Transmutation: '<p>物質の組成を一時的に変える。</p>',
    'Aura de commandement': '<p>他者を従わせる魔法的な存在感を課す。</p>',
    Ralentissement: '<p>対象の動きと反射を鈍らせる。</p>',
    'Entrave végétale': '<p>蔓を伸ばして対象を拘束する。</p>',
    'Contrôle du vent': '<p>一定範囲の気流を導き、強める。</p>',
    'Glissade de verglas': '<p>地面を滑りやすい氷の層で覆う。</p>',
    'Armure de pierre': '<p>対象を魔法の石の殻で覆う。</p>',
    'Portail dimensionnel': '<p>近接する二点の間に一時的な通路を開く。</p>',
    'Barrière magique': '<p>半透明の魔力の壁を作る。</p>',
    Dissipation: '<p>活動中の呪文や継続中の術を打ち消す。</p>',
    'Bouclier anti-sort': '<p>敵の呪文を逸らす盾を作る。</p>',
    'Ancrage de garde': '<p>恒久的な魔法の障壁をある場所に固定する。</p>',
    'Réflexion de sort': '<p>敵の呪文を術者自身へ跳ね返す。</p>',
    'Cercle de protection': '<p>アストラルの存在を退ける魔法円を描く。</p>',
    'Suppression de magie': '<p>対象範囲の魔力を弱める。</p>',
    'Piège astral': '<p>アストラル界に不可視の罠を作る。</p>',
    'Absorption de mana': '<p>敵の呪文からマナを吸い取り、自らの蓄えに加える。</p>',
    'Sceau de fermeture': '<p>魔法的な存在の通行を防ぐ紋を刻む。</p>',
    'Lame de plasma': '<p>術者の手に焼け付くプラズマの刃を形作る。</p>',
    'Pluie de météores': '<p>広い範囲に白熱したマナの破片の雨を呼ぶ。</p>',
    'Flèche de tonnerre': '<p>接触時に耳を裂く音とともに炸裂する凝縮したマナの弾。</p>',
    'Vortex de mana': '<p>対象を引き込んで押し潰す破壊的なマナの渦を作る。</p>',
    'Souffle glacial': '<p>進路上のすべてを凍らせる激しい冷気の円錐。</p>',
    'Impact gravitationnel': '<p>対象の周囲の重力を乱暴に強め、地面へ押し潰す。</p>',
    'Détonation arcanique': '<p>物体に不安定なマナを込め、接触時に炸裂させる。</p>',
    'Vrilles de foudre': '<p>術者の指から複数の電弧が伸びる。</p>',
    'Rayon nécrotique': '<p>離れた位置の生体組織を腐らせる光線。</p>',
    'Éruption magmatique': '<p>敵の足元の地面から焼けたマグマを噴き上げる。</p>',
    'Boulet de canon': '<p>圧縮したマナの密な球体を高速で射出する。</p>',
    'Fouet de mana': '<p>精神を切り裂くアストラルの力の鞭を投射する。</p>',
    'Pique de givre': '<p>地面から鋭い氷の棘を噴き出させる。</p>',
    'Onde de radiation': '<p>生体組織に害を与える電離性の力の波を放つ。</p>',
    'Marteau de force': '<p>マナの純粋な力を集め、壊滅的な鉄槌の一撃とする。</p>',
    'Flèche de feu': '<p>術者の意志に導かれる燃える弾。</p>',
    'Tempête électrique': '<p>広い範囲に雷の嵐を解き放つ。</p>',
    'Éclat de void': '<p>対象の精神を引き裂く負のマナの爆縮。</p>',
    'Salve de cristal': '<p>鋭いマナの結晶片を一斉に射出する。</p>',
    'Étreinte du néant': '<p>対象をアストラルの虚無で包み、生命力を奪う。</p>',
    'Radar astral': '<p>周囲を走査し、あらゆるアストラルの活動を探知する。</p>',
    'Perception des émotions': '<p>付近の生ける者の感情を知覚する。</p>',
    'Œil du faucon': '<p>極めて遠くまで超常の鋭さで見えるようにする。</p>',
    'Détection des métaux': '<p>付近の金属の存在と種類を明らかにする。</p>',
    'Lien empathique': '<p>術者と対象の間に共感の繋がりを結ぶ。</p>',
    'Flair du pisteur': '<p>痕跡を辿るための超常の嗅覚を与える。</p>',
    'Balayage matriciel': '<p>一定範囲の電子機器と無線信号を探知する。</p>',
    'Vision nocturne': '<p>完全な暗闇の中でも見る能力を与える。</p>',
    'Détection des pièges': '<p>周囲の物理的な罠と魔法的な罠を明らかにする。</p>',
    'Télépathie de surface': '<p>対象の表層の思考を読む。</p>',
    'Sonar magique': '<p>マナの波動を放ち、空間を三次元で把握する。</p>',
    "Localisation d'objet": '<p>特定の物体の方向と距離を示す。</p>',
    'Sens de la Matrice': '<p>サイバーデッキなしに周辺のマトリックスとデータの流れを知覚する。</p>',
    'Détection des cyberware': '<p>対象の体内にあるサイバネティック・インプラントを明らかにする。</p>',
    'Vision panoramique': '<p>術者の周囲 360 度の視覚を与える。</p>',
    'Analyse de barrière': '<p>物理的あるいは魔法的な障壁の構造と弱点を解析する。</p>',
    'Écho du passé': '<p>ある場所に刻まれた過去の出来事の残響を知覚する。</p>',
    'Sixième sens': '<p>知覚しえない差し迫った危険を術者に告げる魔法的な直感。</p>',
    'Perception des flux': '<p>一定範囲のマナの線とアストラルの流れを知覚する。</p>',
    'Détection des mensonges': '<p>オーラを解析し、人が嘘をついているかを明らかにする。</p>',
    'Bouclier vital': '<p>外傷性の衝撃から対象の生命機能を守る。</p>',
    'Purge toxique': '<p>対象の体内のあらゆる汚染物質を激しく排出させる。</p>',
    'Ossification rapide': '<p>骨化を促し、骨の破損を修復する。</p>',
    'Augmentation de constitution': '<p>対象の身体的な耐久力を一時的に強める。</p>',
    'Sang de troll': '<p>トロールに匹敵する加速した再生力を与える。</p>',
    'Résistance au feu': '<p>火傷と極度の熱から対象を守る。</p>',
    'Résistance au froid': '<p>凍傷と極度の寒さから対象を守る。</p>',
    'Cicatrisation accélérée': '<p>瘢痕組織を形成して開いた傷を素早く閉じる。</p>',
    'Adrénaline magique': '<p>副腎を魔法的に刺激し、活力を高める。</p>',
    'Restauration sensorielle': '<p>損なわれた感覚を回復させる。視覚、聴覚、嗅覚。</p>',
    'Guérison de groupe': '<p>術者の近くにいる複数の仲間を同時に治癒する。</p>',
    "Peau d'écorce": '<p>対象の肌を樹皮のように硬くする。</p>',
    'Détoxification sanguine': '<p>対象の血からあらゆる有害物質を除く。</p>',
    'Souffle de vie': '<p>心停止した者の生命機能を再始動させて蘇生させる。</p>',
    'Endurance surnaturelle': '<p>疲労を取り除き、通常の限界をはるかに超えて活動させる。</p>',
    'Résistance électrique': '<p>感電と雷撃から対象を守る。</p>',
    'Augmentation de volonté': '<p>外からの影響に対する対象の精神的な意志力を強める。</p>',
    'Peau de fer': '<p>対象の肌を金属のように頑丈にする。</p>',
    'Adaptation environnementale': '<p>対象の体を過酷な環境条件に適応させる。</p>',
    'Régénération neurale': '<p>対象の神経系の損傷を修復する。</p>',
    'Dédoublement spectral': '<p>独立して動く術者の幽体の像を複数作る。</p>',
    "Voile d'ombre": '<p>対象を影で包み、その輪郭を覆い隠す。</p>',
    'Illusion de masse': '<p>広い範囲であらゆる感覚に作用する複雑な幻影を作る。</p>',
    'Murmures insidieux': '<p>対象の精神に平静を崩す囁きを投射する。</p>',
    'Paysage fantôme': '<p>ある場所の全体の見た目を変え、識別できなくする。</p>',
    'Clones illusoires': '<p>混乱を生むために幻影の複製を複数作る。</p>',
    'Sommeil profond': '<p>対象を深く穏やかな魔法の眠りに落とす。</p>',
    'Image miroir': '<p>術者の動きを真似る左右反転した反映を作る。</p>',
    'Aura trompeuse': '<p>対象の魔法的なオーラを覆い隠し、あるいは変える。</p>',
    'Cécité': '<p>感覚の幻影によって対象を一時的に盲目にする。</p>',
    'Surdité': '<p>感覚の幻影によって対象の聴覚を一時的に奪う。</p>',
    'Labyrinthe mental': '<p>対象の精神を身動きできない幻影の迷宮に閉じ込める。</p>',
    'Faux bruit': '<p>選んだ地点に写実的な幻の音を作る。</p>',
    'Apparition terrifiante': '<p>敵を怯えさせるために怪物の像を投射する。</p>',
    'Inversion sensorielle': '<p>対象の感覚を反転させる。上は下になり、熱は冷たさになる。</p>',
    'Invisibilité de groupe': '<p>術者の近くにいる一団を見えないようにする。</p>',
    'Douleur fantôme': '<p>実際のダメージを伴わない激しい幻の痛みを与える。</p>',
    'Amnésie sélective': '<p>対象の記憶から特定の出来事を消す。</p>',
    'Odeur trompeuse': '<p>欺き、あるいは惑わすための幻の匂いを作る。</p>',
    'Cage de verre': '<p>対象は壊せない硝子の檻に閉じ込められたと思い込む。</p>',
    'Chaînes de mana': '<p>対象を縛る実体あるマナの鎖を作る。</p>',
    'Mur de force': '<p>不可視でほぼ通り抜けられない力の壁を起こす。</p>',
    'Contrôle des animaux': '<p>付近の動物の行動を支配する。</p>',
    'Rouille accélérée': '<p>金属の腐食を促し、武器と装甲を弱める。</p>',
    'Bulle de protection': '<p>対象の周囲に守りの力の泡を作る。</p>',
    'Magnétisme': '<p>磁場を操り、金属を引き寄せ、あるいは退ける。</p>',
    'Distorsion spatiale': '<p>一定範囲の空間を歪め、距離を当てにならなくする。</p>',
    'Contrôle de la gravité': '<p>対象範囲の重力を変える。</p>',
    Marionnettiste: '<p>対象の身体の動きを完全に支配する。</p>',
    'Sable mouvant': '<p>敵を捉えるために地面を流砂に変える。</p>',
    'Lien de contrôle': '<p>動かした物体に指示を与えるための魔法の繋がりを結ぶ。</p>',
    Cristallisation: '<p>液体を一時的に固い結晶に変える。</p>',
    'Désassemblage': '<p>機械の部品を傷つけずに分離する。</p>',
    'Piège de mana': '<p>最初に通った対象を拘束する不可視のマナの罠を作る。</p>',
    'Réparation magique': '<p>損傷した物体の部品を魔法的に組み直して修復する。</p>',
    'Prison de glace': '<p>対象を魔法の氷塊の中に封じ込める。</p>',
    'Contrôle de la température': '<p>限られた範囲の周囲の温度を変える。</p>',
    'Compression matérielle': '<p>物質を圧縮し、より密に、より頑丈にする。</p>',
    'Cage de foudre': '<p>通り抜けようとする者を感電させる雷の檻を作る。</p>',
    'Onde de télékinésie': '<p>巨大な念動の波を放ち、その半径内のすべてを動かす。</p>',
  },
  'adept-power': {
    'Poing perforant': '<p>このキャラクターの打撃は壊滅的なダメージを与える。</p>',
    'Frappe du serpent': '<p>速く精確な攻撃。先読みは不可能。</p>',
    'Frappe du tonnerre': '<p>気を拳に集め、壊滅的な一撃を放つ。</p>',
    'Paume vibrante': '<p>破壊的な震動を内臓へ伝える打撃。</p>',
    'Griffes astrales': '<p>精霊を傷つけられるアストラルの力の爪を生む。</p>',
    'Coup de pied circulaire': '<p>複数の相手を打つ回転蹴りの連続。</p>',
    'Lame de ki': '<p>前腕に沿って純粋な力の刃を実体化させる。</p>',
    'Frappe paralysante': '<p>経穴を狙い、相手を一時的に麻痺させる。</p>',
    'Contre-attaque instinctive': '<p>攻撃に対し、即座の反撃で自動的に応じる。</p>',
    'Puissance concentrée': '<p>全身の力を単一の壊滅的な一撃に注ぎ込む。</p>',
    'Technique du brise-pierre': '<p>硬い物質を傷を負わずに打ち抜けるようにする。</p>',
    'Flèche guidée': '<p>飛翔中の弾道を修正するために弾に気を込める。</p>',
    'Rage du berserker': '<p>制御された激昂に入り、筋力と耐性を高める。</p>',
    "Frappe de l'aigle": '<p>致命的な精確さで落下しながら攻撃する。</p>',
    "Prise de l'ours": '<p>対象を逃がさない圧倒的な握力。</p>',
    'Cri de guerre': '<p>気を込めた叫びで近くの相手の方向感覚を奪う。</p>',
    'Combo dévastateur': '<p>単一の打撃に見えるほど速い連打。</p>',
    'Projection de ki': '<p>近距離に気の衝撃波を放つ。</p>',
    'Main de fer': '<p>手を鋼のように硬くし、止められない打撃を放つ。</p>',
    'Technique du cobra': '<p>急所を外科的な精確さで狙う電光の打撃。</p>',
    'Danse des lames': '<p>近接武器による流れるような致命的な動き。</p>',
    'Frappe désarmante': '<p>相手の武器を落とさせる精確な一撃。</p>',
    'Anticipation du combat': '<p>相手が動きを実行する前にそれを感じ取る。</p>',
    'Poing du dragon': '<p>着弾時に発火する竜の力を帯びた打撃。</p>',
    'Riposte foudroyante': '<p>受け流しの成功後に放つ瞬時の反撃。</p>',
    'Vitesse améliorée': '<p>マナを通し、人の限界を超えて身体を加速する。</p>',
    'Course du vent': '<p>短い間、超常の速度で走れるようにする。</p>',
    'Saut du tigre': '<p>人の常の能力を超える驚異的な跳躍。</p>',
    'Marche murale': '<p>垂直面を歩けるようにする。</p>',
    'Chute contrôlée': '<p>気の制御によって落下の衝撃を減らす。</p>',
    'Nage du saumon': '<p>超常の速度と持久力で泳ぐ。</p>',
    'Équilibre parfait': '<p>どのような面でも、針金の上でさえ完全な平衡を保つ。</p>',
    'Accélération réflexe': '<p>反応速度を劇的に高める。</p>',
    'Pas du fantôme': '<p>短い距離を瞬時に移動する。</p>',
    'Roulade acrobatique': '<p>転倒や組み付きの後、即座にペナルティなく立ち直る。</p>',
    'Adhérence du gecko': '<p>手足であらゆる面に吸着できるようにする。</p>',
    'Bond dimensionnel': '<p>アストラル界を経由した短距離の転移。</p>',
    'Grâce féline': '<p>猫科に着想を得た流れるような静かな動き。</p>',
    'Souffle de marathon': '<p>数時間の持続的な行動を可能にする超人的な持久力。</p>',
    Contorsion: '<p>狭い空間を通り抜けられる極度の柔軟性。</p>',
    'Sens du danger': '<p>差し迫った脅威を告げる魔法的な直感。</p>',
    'Vision améliorée': '<p>通常の可視範囲を超えて高められた視覚。</p>',
    'Ouïe amplifiée': '<p>超常の周波数と距離の音を聞き取る。</p>',
    'Odorat du loup': '<p>対象を数キロメートル追跡できる発達しすぎた嗅覚。</p>',
    'Toucher analytique': '<p>触れることで物体の組成と性質を判断する。</p>',
    'Perception astrale': '<p>アストラル界と魔法的なオーラを知覚できるようにする。</p>',
    'Vision nocturne': '<p>完全な暗闇でも白昼のように見る。</p>',
    'Sens sismique': '<p>地面の震動を知覚し、付近の存在を捉える。</p>',
    'Écho-localisation': '<p>反射した音を用いて周囲の空間を把握する。</p>',
    "Lecture d'intention": '<p>対話相手の敵意や友好を知覚する。</p>',
    'Goût analytique': '<p>化学的な精確さで味によって毒物と薬物を探知する。</p>',
    'Vision thermographique': '<p>生物と機械の熱の痕跡を知覚する。</p>',
    'Sixième sens': '<p>緊張下での判断を導く超常の直観。</p>',
    'Perception du flux': '<p>周囲のマナの流れを知覚する。</p>',
    'Sens magnétique': '<p>磁場と隠された電子機器を探知する。</p>',
    'Esquive surnaturelle': '<p>攻撃を避けるために魔法的に高められた反射。</p>',
    'Corps de fer': '<p>マナが身体の構造を補強し、より頑丈にする。</p>',
    'Résistance à la douleur': '<p>神経系の制御によって痛みを無視する。</p>',
    'Peau de pierre': '<p>衝撃に耐えるために肌が魔法的に硬くなる。</p>',
    'Bouclier de ki': '<p>攻撃を防ぐために気の力場を投射する。</p>',
    'Résistance aux toxines': '<p>身体が毒物と毒素を自動的に中和する。</p>',
    "Esprit d'acier": '<p>精神への侵入と操作に対する魔法的な耐性。</p>',
    "Absorption d'impact": '<p>打撃の運動の力を吸収し、ダメージを減らす。</p>',
    'Sang de dragon': '<p>加速した血の再生と出血への耐性。</p>',
    'Déflexion': '<p>近距離の弾を本能的に逸らす。</p>',
    'Volonté indomptable': '<p>恐怖と強制に対する並外れた精神の耐性。</p>',
    'Armure de ki': '<p>身体を気の守りの層で包む。</p>',
    'Résistance aux éléments': '<p>元素のダメージに耐える。火、冷気、電気。</p>',
    'Récupération accélérée': '<p>通常の二倍の速さで傷を癒す。</p>',
    'Détournement de ki': '<p>受けた攻撃の力を自らの蓄えへ転じる。</p>',
    'Pas léger': '<p>浮いているかのような静かで軽やかな動き。</p>',
    'Ombre vivante': '<p>超常の仕方で影に紛れる。</p>',
    'Aura nulle': '<p>魔法的なオーラを抑え、アストラル界で見えなくなる。</p>',
    'Silence absolu': '<p>このキャラクターが生じるあらゆる音を消す。</p>',
    'Caméléon': '<p>肌と衣服が視覚的な環境に順応する。</p>',
    'Présence effacée': '<p>視界から外れた途端、人はこのキャラクターの存在を忘れる。</p>',
    'Passage sans trace': '<p>通った物理的な痕跡を残さない。</p>',
    "Masquage d'odeur": '<p>動物と探知機を欺くために体臭をすべて消す。</p>',
    'Furtivité urbaine': '<p>人混みと街の設備に自然に紛れる。</p>',
    "Dissimulation d'arme": '<p>身に帯びた武器を魔法的に隠し、身体検査では探知されない。</p>',
    'Voix enchanteresse': '<p>言葉をより説得的にする魔法的な力を声が帯びる。</p>',
    "Aura d'autorité": '<p>敬意を強いる支配的な存在感を放つ。</p>',
    'Empathie profonde': '<p>他者の感情を魔法的な精確さで感じ取り、理解する。</p>',
    'Charme surnaturel': '<p>抗いがたい魔法的なカリスマを放つ。</p>',
    'Regard intimidant': '<p>対話相手の意志を縛る気を込めた眼光。</p>',
    'Mimétisme vocal': '<p>聞いたあらゆる声を完全に再現する。</p>',
    'Persuasion subtile': '<p>気づかせずに他者の判断に影響を与える。</p>',
    'Calme imposé': '<p>敵意ある集団の緊張を魔法的に和らげる。</p>',
    'Détection de mensonge': '<p>嘘を露わにする微細な表情とオーラの変化を知覚する。</p>',
    'Présence mémorable': '<p>出会ったすべての者に長く残る好ましい印象を与える。</p>',
    'Méditation curative': '<p>自然な治癒を早める深い瞑想。</p>',
    'Transfert de ki': '<p>傷ついた仲間を癒すために生命の気を移す。</p>',
    'Purge de toxines': '<p>気によって体内の毒素と薬物を能動的に排出する。</p>',
    'Régénération accélérée': '<p>傷が数分のうちに目に見えて閉じる。</p>',
    'Transe réparatrice': '<p>深い恍惚に入り、8 時間の睡眠を 2 時間で代える。</p>',
    'Souffle vital': '<p>身体に酸素を送り再生させる呼吸の技法。</p>',
    'Cicatrisation instantanée': '<p>気によって浅い傷を瞬時に閉じる。</p>',
    'Immunité à la fatigue': '<p>長い期間、身体が疲労を感じなくなる。</p>',
    'Restauration nerveuse': '<p>気によって神経系の損傷を修復する。</p>',
    'Harmonie corporelle': '<p>身体のあらゆる系を同調させ、最適に機能させる。</p>',
    'Frappe du phénix': '<p>気で発火させた打撃。着弾時に対象を焼く。</p>',
    'Prise du python': '<p>気で強めた締め技で対象を拘束する。</p>',
    'Fouet de ki': '<p>離れた位置を打てる純粋な力の鞭を生む。</p>',
    'Frappe sismique': '<p>地面を打ち、相手の体勢を崩す衝撃波を起こす。</p>',
    'Morsure du scorpion': '<p>相手の神経を狙う素早く毒のある打撃。</p>',
    'Tempête de coups': '<p>追えないほどの速さで打撃の弾幕を解き放つ。</p>',
    'Coupe du vent': '<p>風の刃が離れた位置を傷つけるほどの力で空を切る。</p>',
    'Technique du mantis': '<p>螳螂を模した流派。致命的な掴みを用いる。</p>',
    'Charge du taureau': '<p>障害物を跳ね飛ばす気で強めた壊滅的な突進。</p>',
    'Frappe du vide': '<p>物理的な障壁と魔法的な障壁を通り抜ける打撃。</p>',
    "Pluie d'acier": '<p>魔法的な精確さで複数の弾を同時に投げる。</p>',
    'Balayage tourbillonnant': '<p>相手を倒す気で高めた回転の足払い。</p>',
    'Frappe du tigre blanc': '<p>白虎を模した爪と噛みつきの打撃の組み合わせ。</p>',
    'Technique du miroir': '<p>相手の戦闘技法を瞬時に写し取る。</p>',
    'Coup de grâce': '<p>弱った相手に放つ壊滅的な止めの一撃。</p>',
    'Paume céleste': '<p>純粋なアストラルの力を込めた掌打。</p>',
    'Enchaînement du singe': '<p>跳躍と打撃を組み合わせた予測しがたい曲芸的な流派。</p>',
    'Lance de ki': '<p>離れた対象へ凝集した力の投槍を放つ。</p>',
    'Étreinte glaciale': '<p>冷気の気を通し、接触時に対象を凍らせる。</p>',
    'Marteau de guerre': '<p>膨大な量の気を拳に集め、壊滅的な衝撃を与える。</p>',
    'Pas de brume': '<p>一瞬だけ非実体化し、固い障害物を通り抜ける。</p>',
    "Course sur l'eau": '<p>気を足に配り、液体の面を走る。</p>',
    'Saut du cerf': '<p>水平方向に大きな距離を跳ぶ優雅で力強い跳躍。</p>',
    'Vélocité du colibri': '<p>絶え間なく回避できる超高速の小刻みな動き。</p>',
    'Glissade spectrale': '<p>地面から数センチ上を静かに滑る。</p>',
    'Ascension du singe': '<p>あらゆる面を驚異的な速さで登る。</p>',
    'Élan du guépard': '<p>短距離を超常の速度で駆ける爆発的な疾走。</p>',
    'Rétablissement aérien': '<p>空中で体勢を直し、常に足から着地する。</p>',
    'Traverse des toits': '<p>建物の間を超常の軽やかさで跳び渡る。</p>',
    'Ancrage terrestre': '<p>地面に魔法的に根を張る。動かすことも倒すこともできない。</p>',
    'Radar spirituel': '<p>広い半径内の精霊の存在と位置を探知する。</p>',
    'Vision des flux': '<p>機材なしにマトリックスのデータの流れを見る。</p>',
    'Perception du temps': '<p>決定的な瞬間に時間を緩やかに知覚する。</p>',
    'Ouïe sélective': '<p>騒がしい環境で特定の会話だけを分離して増幅する。</p>',
    'Cartographie mentale': '<p>訪れたあらゆる建物の見取り図を記憶し、心に描く。</p>',
    'Détection de magie': '<p>一定範囲の術と活動中の呪文の存在を感じ取る。</p>',
    'Vision microscopique': '<p>微細な部分まで見られるようにする魔法的な視覚の拡大。</p>',
    'Sens du cyberespace': '<p>周囲のマトリックス網の構成を直観的に知覚する。</p>',
    'Perception des émotions': '<p>オーラの微細な変化から人の感情を読み取る。</p>',
    'Oreille absolue': '<p>あらゆる音の周波数を完全に識別し、再現する。</p>',
    'Carapace astrale': '<p>魔法ダメージを吸収する守りのアストラルの力の殻。</p>',
    'Résilience du chêne': '<p>骨と筋肉を古い樫の木のように硬くする。</p>',
    'Barrière psychique': '<p>精神攻撃に対する通り抜けられない心の壁を築く。</p>',
    'Redirection de force': '<p>物理攻撃の力を地面や空へ逸らす。</p>',
    'Peau de diamant': '<p>肌が一時的に結晶化し、金剛石のように硬い面となる。</p>',
    'Absorption de mana': '<p>敵の呪文から魔力を吸収し、蓄えを回復する。</p>',
    'Posture du roc': '<p>受けるダメージを大幅に減らす揺るがぬ防御の構え。</p>',
    'Contre-sort instinctif': '<p>このキャラクターへ向けられた弱い呪文を自動的に打ち消す。</p>',
    'Résistance au drain': '<p>身体と精神が受けるドレインの影響を減らす。</p>',
    'Sang coagulant': '<p>血が瞬時に凝固し、出血を止める。</p>',
    'Effacement de traces numériques': '<p>付近のセンサーとカメラを魔法的に撹乱する。</p>',
    'Dédoublement illusoire': '<p>注意を逸らすために自らの幻の像を作る。</p>',
    'Marche silencieuse': '<p>一歩ごとに気が衝撃を和らげ、音をすべて消す。</p>',
    "Voile d'ombre": '<p>光を吸う闇の帷に身を包む。</p>',
    'Invisibilité partielle': '<p>身体の周囲で光を曲げ、部分的に見えなくなる。</p>',
    'Respiration suspendue': '<p>苦しさなく長い間呼吸を止める。</p>',
    'Déplacement non-euclidien': '<p>通常の幾何では許されない経路を通って移動する。</p>',
    'Fondu dans la foule': '<p>人の集団の中で見分けがつかなくなる。</p>',
    'Empreinte nulle': '<p>指紋も DNA も生体の痕跡も残さない。</p>',
    'Mimétisme environnemental': '<p>熱と音の痕跡を環境に合わせる。</p>',
    'Commandement tactique': '<p>戦術的な指示を仲間の精神へ直接投射する。</p>',
    'Masque émotionnel': '<p>本当の感情を気の仮面の後ろへ完全に隠す。</p>',
    'Projection de confiance': '<p>対話相手に絶対の信頼を抱かせる。</p>',
    'Voix de la raison': '<p>相手に論理を考慮させる気を込めた言葉。</p>',
    'Terreur mystique': '<p>気弱な者を逃げ出させる超常の恐怖のオーラを放つ。</p>',
    'Lien empathique': '<p>仲間と深い感情の繋がりを結ぶ。</p>',
    'Suggestion subliminale': '<p>対象の潜在意識に示唆を植え付ける。</p>',
    'Aura de sérénité': '<p>このキャラクターの周囲一帯の乱れた心を和らげる。</p>',
    'Négociateur né': '<p>交渉において相手が何を望んでいるかを本能的に知覚する。</p>',
    'Présence terrifiante': '<p>姿を見せるだけで相手の血を凍らせる。</p>',
    'Canalisation élémentaire': '<p>自然の元素を身体に通し、戦闘で用いる。</p>',
    'Toucher soigneur': '<p>手を当てることで他者の軽い傷を癒す。</p>',
    'Ancrage spirituel': '<p>下位の精霊を一時的な奉仕に縛る。</p>',
    'Flamme intérieure': '<p>冷気から身を守り、物に火をつけられる体内の熱を生む。</p>',
    'Souffle du givre': '<p>面を凍らせ対象を鈍らせる凍える息を吐く。</p>',
    'Décharge électrique': '<p>電撃を蓄え、手から放出する。</p>',
    "Peau d'écorce": '<p>肌が樹皮の質感と頑丈さを帯びる。</p>',
    'Communion animale': '<p>周囲の動物と語り合い、親しくなる。</p>',
    'Lévitation mineure': '<p>短い間、地面から数メートル上に浮かぶ。</p>',
    'Onde de choc': '<p>近接する範囲のすべてを押し退ける純粋な力の波を放つ。</p>',
    "Muscles d'acier": '<p>筋繊維を魔法的に補強し、超人的な筋力を得る。</p>',
    'Os renforcés': '<p>気が骨の構造を密にし、ほぼ折れないようにする。</p>',
    'Tendons élastiques': '<p>腱の弾性を高め、動きの範囲を広げる。</p>',
    'Poumons de fer': '<p>ガスと窒息に耐えるために肺の容量を魔法的に高める。</p>',
    'Synapses accélérées': '<p>神経の信号が超常の速度で伝わる。</p>',
    'Thermorégulation': '<p>体温を制御し、極端な環境に耐える。</p>',
    'Métabolisme accéléré': '<p>代謝が超常の速度で働き、治癒を早める。</p>',
    'Articulations renforcées': '<p>関節が気で補強され、脱臼と捻りに耐える。</p>',
    'Vision du prédateur': '<p>眼が捕食者のように順応し、周辺視野が広がる。</p>',
    'Réflexes surhumains': '<p>刺激に先立つかのように見えるほど速い反応。</p>',
    'Concentration inébranlable': '<p>気を散らすものと痛みをよそに絶対の集中を保つ。</p>',
    'Méditation de combat': '<p>戦闘中に瞑想の境地に入り、精確さと平静を高める。</p>',
    'Maîtrise du souffle': '<p>持久力と平静を最適にするための完全な呼吸の制御。</p>',
    'Esprit compartimenté': '<p>精神を区画に分け、複数の思考作業を同時に行う。</p>',
    'Mémoire eidétique': '<p>見たもの、聞いたもの、読んだもののすべてを完全な精確さで覚えている。</p>',
    "Résistance à l'interrogatoire": '<p>物理的な尋問技法と魔法的な尋問技法に耐える。</p>',
    'Volonté de fer': '<p>自らの限界を越えて押し進ませる超常の決意。</p>',
    'Conscience éveillée': '<p>眠っている間も周囲を把握し続ける。</p>',
    'Suppression de la peur': '<p>気の制御によって恐怖を完全に取り除く。</p>',
    Transcendance: '<p>身体と精神を統べる高次の意識の境地に達する。</p>',
  },
};

/** The Japanese description for a template, or undefined to fall back to English. */
export function featDescJa(featType: string, name: string): string | undefined {
  return FEAT_DESCS_JA[featType]?.[name];
}
