/** Japanese text keyed by the upstream English string; product names stay in Latin script. */
export const NARRATIVE_EFFECTS_JA: Record<string, string> = {
  "Integrated silencer": "内蔵サイレンサー",
  "Extended magazine": "拡張マガジン",
  "Laser sight": "レーザーサイト",
  "Reinforced barrel": "強化銃身",
  "Ergonomic grip": "人間工学グリップ",
  "Custom engraving": "特注の刻印",
  "Serrated blade": "鋸刃",
  "Perfect counterweight": "完全調整カウンターウェイト",
  "Motion detector": "動体検知器",
  "Anti-recoil system": "反動抑制システム",
  "Anti-glare coating": "反射防止コーティング",
  "Vibrating blade": "振動ブレード",
  "Quick reload mechanism": "高速リロード機構",
  "Long precision barrel": "長距離精密銃身",
  "Fiber optic sight": "光ファイバー照準器",
  "Folding stock": "折り畳みストック",
  "Armor-piercing ammo": "徹甲弾",
  "Rotary magazine": "回転式マガジン",
  "Smart targeting system": "スマート照準システム",
  "Magnetic recoil compensator": "磁気式反動補正器",
  "Modified Picatinny rail": "改造ピカティニーレール",
  "Free-floating stabilized barrel": "安定化フリーフローティング銃身",
  "Enhanced selective fire system": "改良型射撃モード切替機構",
  "Heated grip": "加温グリップ",
  "Ventilated handguard": "通気式ハンドガード",
  "Compact thermal scope": "小型サーマルスコープ",
  "Threaded barrel tip": "ねじ切り銃口",
  "Lightened trigger spring": "軽量トリガースプリング",
  "Progressive trigger": "段階式トリガー",
  "Biometric safety system": "生体認証セーフティ",
  "Friction-treated barrel": "摩擦低減処理銃身",
  "Translucent magazine": "半透明マガジン",
  "Three-point tactical sling": "3点式タクティカルスリング",
  "Strobe flashlight": "ストロボライト",
  "Infrared pointer": "赤外線ポインター",
  "Retractable bipod": "格納式バイポッド",
  "Flash hider": "フラッシュハイダー",
  "Heavy precision barrel": "重量級精密銃身",
  "Integrated cooling system": "内蔵冷却システム",
  "Tracer rounds": "曳光弾",
  "Poisonable blade": "毒塗布対応ブレード",
  "Carbon fiber guard": "炭素繊維の鍔",
  "Weighted pommel": "加重ポメル",
  "Partial monofilament edge": "部分モノフィラメント刃",
  "Magnetic scabbard": "磁気式鞘",
  "Quick-draw system": "クイックドロー機構",
  "Anti-vibration reinforcement": "防振補強",
  "Synthetic dragon skin grip": "合成ドラゴン皮グリップ",
  "Low-energy plasma blade": "低出力プラズマブレード",
  "Tactile feedback system": "触覚フィードバックシステム",
  "Integrated shock absorber": "内蔵ショックアブソーバー",
  "Anti-disarm mechanism": "武装解除防止機構",
  "Active camo coating": "アクティブ迷彩コーティング",
  "Ammo counter system": "残弾カウンター",
  "Enhanced shell extractor": "改良型排莢機構",
  "Interchangeable barrel": "交換式銃身",
  "Shape-memory grip": "形状記憶グリップ",
  "Self-cleaning system": "自動清掃システム",
  "Ultra-light alloy": "超軽量合金",
  "Titanium structural reinforcement": "チタン製構造補強",
  "Quick-lock system": "クイックロック機構",
  "Holographic marking": "ホログラム標識",
  "Phosphorescent coating": "蓄光コーティング",
  "Friend/foe target detector": "敵味方識別センサー",
  "Assisted guidance system": "誘導補助システム",
  "Trajectory corrector": "弾道補正器",
  "Force amplifier": "力増幅装置",
  "Silent mechanism": "消音機構",
  "Secondary retractable blade": "予備の格納式ブレード",
  "Electrified guard": "通電式の鍔",
  "Magnetic attachment system": "磁気式固定システム",
  "Anti-fingerprint coating": "指紋付着防止コーティング",
  "Tactical short barrel": "タクティカル短銃身",
  "High-capacity drum magazine": "大容量ドラムマガジン",
  "Two-stage trigger": "2段式トリガー",
  "Vertical compensator": "垂直反動補正器",
  "Side accessory rail": "側面アクセサリーレール",
  "Ballistic jamming device": "弾道妨害装置",
  "Integrated smoke launcher": "内蔵スモークランチャー",
  "Light amplification scope": "暗視スコープ",
  "Zero-recoil system": "無反動システム",
  "Ceramic vented barrel": "セラミック製通気銃身",
  "Nano non-slip grip": "ナノ滑り止めグリップ",
  "Electronic firing system": "電子発射システム",
  "Controlled burst module": "制御式バースト射撃モジュール",
  "Red dot sight": "レッドドットサイト",
  "Carbon-reinforced barrel": "炭素繊維強化銃身",
  "Bolt lock system": "ボルトロック機構",
  "Heat extractor": "排熱装置",
  "Self-sharpening blade": "自動研磨ブレード",
  "Reverse serrated edge": "逆向き鋸刃",
  "Tactical pommel reinforcement": "タクティカル・ポメル補強",
  "Assisted throwing system": "投擲補助システム",
  "Palm magnetic grip": "掌部磁気グリップ",
  "Non-lethal neutralization system": "非致死性制圧システム",
  "Retractable monofilament wire": "格納式モノフィラメントワイヤー",
  "Trigger pressure sensor": "トリガー圧力センサー",
  "Self-repairing coating": "自己修復コーティング",
  "Micro-gyroscope stabilizer": "超小型ジャイロ安定装置",
  "Stealth fire module": "隠密射撃モジュール"
};

export const DRONE_NAMES_JA: Record<string, string> = {
  "Kaze Mk.II Surveillance Microdrone": "Kaze Mk.II 監視マイクロドローン",
  "Nixe Phantom Spy Drone": "Nixe Phantom 諜報ドローン",
  "OeilNoir V4 Flying Microcam": "OeilNoir V4 飛行マイクロカメラ",
  "Solaris Whisper Sensor Drone": "Solaris Whisper センサードローン",
  "Duskwing Stealth Nanodrone": "Duskwing Stealth 隠密ナノドローン",
  "Tengu Eye Watch Drone": "Tengu Eye 警戒ドローン",
  "Shrike Optics R3 Micro-Spy": "Shrike Optics 超小型諜報機",
  "Argus Lite Sentinel Drone": "Argus Lite 哨戒ドローン",
  "Helix Scansphere Flying Sensor": "Helix Scansphere 飛行センサー",
  "Mantik Glare Surveillance Drone": "Mantik Glare 監視ドローン",
  "Lynxware Peeper Micro-Observer": "Lynxware Peeper 超小型観測機",
  "Insektik Buzz Fly Drone": "Insektik Buzz ハエ型ドローン",
  "Vortik Spyglass Spy Eye": "Vortik Spyglass 諜報センサー",
  "Neonlens Orbit Camera Drone": "Neonlens Orbit カメラドローン",
  "Dustware Mote Nano-Sensor": "Dustware Mote ナノセンサー",
  "Pyrex Seeker Thermal Drone": "Pyrex Seeker 熱探知ドローン",
  "Kasai Watcher Micro-Sentinel": "Kasai Watcher 超小型哨戒機",
  "Specter IR Infrared Spy Drone": "Specter IR 赤外線諜報ドローン",
  "Cipherfly Mk.I Flying Bug": "Cipherfly Mk.I 飛行盗聴機",
  "Strix Overwatch Observation Drone": "Strix Overwatch 観測ドローン",
  "Falcon-3 Scout Drone": "Falcon-3 Scout 偵察ドローン",
  "Vektral Dash Fast Scout": "Vektral Dash 高速偵察機",
  "Nightcrawl Mk.IV Stealth Drone": "Nightcrawl Mk.IV 隠密ドローン",
  "Kestrel Swift Tactical Scout": "Kestrel Swift 戦術偵察機",
  "Zephyra Bolt Speed Drone": "Zephyra Bolt 高速ドローン",
  "Razorwing Sprint Mini-Scout": "Razorwing Sprint 小型偵察機",
  "Talon Recon Reconnaissance Drone": "Talon Recon 偵察ドローン",
  "Gridrunner U2 Urban Scout": "Gridrunner U2 市街地偵察機",
  "Shade Wisp Infiltrator Drone": "Shade Wisp 潜入ドローン",
  "Noxwing Glider Night Scout": "Noxwing Glider 夜間偵察機",
  "Sparkfly Dart Micro-Scout": "Sparkfly Dart 超小型偵察機",
  "Vanguard Pixie Point Drone": "Vanguard Pixie 先行偵察ドローン",
  "Mutebird V6 Silent Scout": "Mutebird V6 静音偵察機",
  "Swiftek Runner Vanguard Drone": "Swiftek Runner 先遣ドローン",
  "Jetmite Blur Speed Microdrone": "Jetmite Blur 高速マイクロドローン",
  "Skypierce Alpha Aerial Scout": "Skypierce Alpha 航空偵察機",
  "Ghostwing Recon Phantom Drone": "Ghostwing Recon 隠密ドローン",
  "Molevex Burrow Tunnel Scout": "Molevex Burrow 地下道偵察機",
  "Quicksilva Flicker Agile Drone": "Quicksilva Flicker 高機動ドローン",
  "Wraith Scout S1 Stealth Scout": "Wraith Scout 隠密偵察機",
  "Parcelair Express Delivery Drone": "Parcelair Express 配達ドローン",
  "Lifepulse Medic Mini-Medidrone": "Lifepulse Medic 小型医療ドローン",
  "Fixbug Patchwork Repair Drone": "Fixbug Patchwork 修理ドローン",
  "Sparklite Arc Welding Microdrone": "Sparklite Arc 溶接マイクロドローン",
  "Ziptek Messenger Courier Drone": "Ziptek Messenger 配送ドローン",
  "Helpfly Buddy Assist Drone": "Helpfly Buddy 支援ドローン",
  "Scanfix Probe Diagnostic Minidrone": "Scanfix Probe 診断用小型ドローン",
  "Dustaway Sweep Cleaning Drone": "Dustaway Sweep 清掃ドローン",
  "Blazeout Puff Fire Extinguisher Microdrone": "Blazeout Puff 消火マイクロドローン",
  "Toolwing Multi Utility Drone": "Toolwing Multi 多目的ドローン",
  "Voltek Zapper Electrician Minidrone": "Voltek Zapper 電気工事用小型ドローン",
  "Refuel Hop Supply Drone": "Refuel Hop 補給ドローン",
  "Pipefix Drip Plumber Microdrone": "Pipefix Drip 配管修理マイクロドローン",
  "Lumivex Beacon Light Drone": "Lumivex Beacon 照明ドローン",
  "Swiftmail Pigeon Messenger Minidrone": "Swiftmail Pigeon 伝令用小型ドローン",
  "Rescuewing Aid Emergency Drone": "Rescuewing Aid 救急ドローン",
  "Spraybug Artist Paint Microdrone": "Spraybug Artist 塗装マイクロドローン",
  "Greenvex Gardener Botanist Drone": "Greenvex Gardener 園芸ドローン",
  "Samplite Grab Sampling Minidrone": "Samplite Grab 試料採取用小型ドローン",
  "Mapwing Survey Mapping Drone": "Mapwing Survey 測量ドローン",
  "Glimmer Speck Gnat Drone": "Glimmer Speck ブヨ型ドローン",
  "Orbex Sentry Aerial Sensor": "Orbex Sentry 航空センサー",
  "Pinpoint Lens Micro-Observer": "Pinpoint Lens 超小型観測機",
  "Trackbug Hound Tracking Drone": "Trackbug Hound 追跡ドローン",
  "Whisperfly Echo Nano-Bug": "Whisperfly Echo ナノ盗聴機",
  "Peregrine Zip Miniature Scout": "Peregrine Zip 小型偵察機",
  "Circlex Patrol Patrol Drone": "Circlex Patrol 巡回ドローン",
  "Vectora Pathfinder Mini-Scout": "Vectora Pathfinder 小型偵察機",
  "Harbinger Mk.III Forerunner Drone": "Harbinger Mk.III 先行ドローン",
  "Digfly Mole Underground Scout": "Digfly Mole 地下偵察機",
  "Meditek Pill Pharmacist Drone": "Meditek Pill 薬剤配布ドローン",
  "Breezex Fan Ventilator Minidrone": "Breezex Fan 換気用小型ドローン",
  "Boomaway Defuser Demining Drone": "Boomaway Defuser 地雷処理ドローン",
  "Chemisense Sniffer Tester Microdrone": "Chemisense Sniffer 検査用マイクロドローン",
  "Wirevex Carrier Cable Drone": "Wirevex Carrier ケーブル運搬ドローン",
  "Neonfly Shimmer Dragonfly Drone": "Neonfly Shimmer トンボ型ドローン",
  "Pulsetek Ping Radar Drone": "Pulsetek Ping レーダードローン",
  "Splashbug Swim Aquatic Nanodrone": "Splashbug Swim 水中ナノドローン",
  "Signalwing Boost Relay Drone": "Signalwing Boost 通信中継ドローン",
  "Miragefly Holo Holographic Microdrone": "Miragefly Holo ホログラム投影マイクロドローン",
  "Stormlet Forecast Weather Drone": "Stormlet Forecast 気象観測ドローン",
  "Jamwing Noise Jammer Minidrone": "Jamwing Noise 妨害用小型ドローン",
  "Rockbug Scanner Geologist Drone": "Rockbug Scanner 地質調査ドローン",
  "Sonex Ear Acoustic Microdrone": "Sonex Ear 音響マイクロドローン",
  "Pathmark Flare Marker Drone": "Pathmark Flare 標識設置ドローン",
  "Grabwing Picker Collection Minidrone": "Grabwing Picker 回収用小型ドローン",
  "Predabug Hunter Anti-Drone Drone": "Predabug Hunter 対ドローン迎撃機",
  "Quakelet Tremor Seismic Microdrone": "Quakelet Tremor 地震観測マイクロドローン",
  "Shutterbug Flash Photographer Drone": "Shutterbug Flash 撮影ドローン",
  "Hazelet Detector Toxicologist Minidrone": "Hazelet Detector 毒物検知用小型ドローン",
  "Laserfly Cutter Cutting Drone": "Laserfly Cutter 切断ドローン",
  "Magfly Grip Magnetic Microdrone": "Magfly Grip 磁気マイクロドローン",
  "Beaconex Trail Beacon Drone": "Beaconex Trail ビーコンドローン",
  "Drillbug Pierce Drill Minidrone": "Drillbug Pierce 掘削用小型ドローン",
  "Farseek Scope Optical Sniper Drone": "Farseek Scope 光学狙撃ドローン",
  "Datafly Courier Messenger Microdrone": "Datafly Courier 伝令マイクロドローン",
  "Flashbug Burst Ephemeral Drone": "Flashbug Burst 短時間稼働ドローン",
  "Leechfly Cling Parasite Nanodrone": "Leechfly Cling 寄生ナノドローン",
  "Sniffex Trace Detection Drone": "Sniffex Trace 探知ドローン",
  "Tagbug Mark Tracer Microdrone": "Tagbug Mark 追跡マイクロドローン",
  "Apex Centurion Combat Drone": "Apex Centurion 戦闘ドローン",
  "Meridian Wardog Tactical Drone": "Meridian Wardog 戦術ドローン",
  "Ironvex Striker Armed Drone": "Ironvex Striker 武装ドローン",
  "Razorclaw Havoc Assault Drone": "Razorclaw Havoc 強襲ドローン",
  "Hailfire Torrent Suppression Drone": "Hailfire Torrent 制圧ドローン",
  "Deadshot Marksman Gunner Drone": "Deadshot Marksman 射撃ドローン",
  "Sidewinder Rush Flanking Drone": "Sidewinder Rush 側面攻撃ドローン",
  "Ambush Fang Ambush Drone": "Ambush Fang 待ち伏せドローン",
  "Bastion Shield Defense Drone": "Bastion Shield 防御ドローン",
  "Lobtek Mortar Grenade Drone": "Lobtek Mortar グレネードドローン",
  "Rattlegun Fury Machine Gun Drone": "Rattlegun Fury 機関銃ドローン",
  "Warwatch Aegis Armed Sentinel Drone": "Warwatch Aegis 武装哨戒ドローン",
  "Guardvex Protector Escort Drone": "Guardvex Protector 護衛ドローン",
  "Hammerfall Breacher Siege Drone": "Hammerfall Breacher 攻城ドローン",
  "Predex Stalker Hunter Drone": "Predex Stalker 追撃ドローン",
  "Trapwire Snare Net Launcher Drone": "Trapwire Snare ネットランチャードローン",
  "Smokewall Cover Smokescreen Drone": "Smokewall Cover 煙幕ドローン",
  "Piercetek Javelin Anti-Armor Drone": "Piercetek Javelin 対装甲ドローン",
  "Infernotek Blaze Flamethrower Drone": "Infernotek Blaze 火炎放射ドローン",
  "Voltguard Stun Shock Drone": "Voltguard Stun 電撃ドローン",
  "Crashburn Fury Kamikaze Drone": "Crashburn Fury 自爆ドローン",
  "Vigil Mk.VII Armed Patrol Drone": "Vigil Mk.VII 武装巡回ドローン",
  "Hawkeye Precision Sniper Drone": "Hawkeye Precision 狙撃ドローン",
  "Crowdbreaker Pulse Riot Drone": "Crowdbreaker Pulse 暴動鎮圧ドローン",
  "Vendex Payback Retaliation Drone": "Vendex Payback 反撃ドローン",
  "Haulex Mule Cargo Drone": "Haulex Mule 貨物ドローン",
  "Liftvex Porter Transport Drone": "Liftvex Porter 輸送ドローン",
  "Packwing Sherpa Carrier Drone": "Packwing Sherpa 運搬ドローン",
  "Cargobug Hauler Freight Drone": "Cargobug Hauler 貨物ドローン",
  "Supplytek Drop Resupply Drone": "Supplytek Drop 補給ドローン",
  "Chainvex Link Logistics Drone": "Chainvex Link 兵站ドローン",
  "Ammofly Feeder Ammo Drone": "Ammofly Feeder 弾薬供給ドローン",
  "Rescuetek Lifter Ambulance Drone": "Rescuetek Lifter 救急搬送ドローン",
  "Movex Packer Moving Drone": "Movex Packer 引越しドローン",
  "Flatbed Skid Pallet Drone": "Flatbed Skid パレット運搬ドローン",
  "Cranex Hoist Crane Drone": "Cranex Hoist クレーンドローン",
  "Boxfly Container Drone": "Boxfly Container ドローン",
  "Salvex Scoop Salvage Drone": "Salvex Scoop 廃品回収ドローン",
  "Armorfly Shield Armor Carrier Drone": "Armorfly Shield 装甲運搬ドローン",
  "Bulktek Drop Heavy Delivery Drone": "Bulktek Drop 重量物配達ドローン",
  "Tankfly Liquid Tanker Drone": "Tankfly Liquid 液体輸送ドローン",
  "Escapex Extract Evacuation Drone": "Escapex Extract 避難支援ドローン",
  "Stretchfly Medivac Stretcher Drone": "Stretchfly Medivac 担架ドローン",
  "Stashtek Cache Storage Drone": "Stashtek Cache 保管ドローン",
  "Turretvex Mount Turret Carrier Drone": "Turretvex Mount 砲塔運搬ドローン",
  "Voltshade EW Electronic Warfare Drone": "Voltshade EW 電子戦ドローン",
  "Jammex Disrupt Jammer Drone": "Jammex Disrupt 妨害ドローン",
  "Hackwing Intrude Hacker Drone": "Hackwing Intrude ハッキングドローン",
  "Blindex Fog Radar Jammer Drone": "Blindex Fog レーダー妨害ドローン",
  "Pulsevex Blackout EMP Drone": "Pulsevex Blackout 電磁パルスドローン",
  "Countervex Shield Countermeasure Drone": "Countervex Shield 対抗措置ドローン",
  "Snatchwave Intercept Interception Drone": "Snatchwave Intercept 通信傍受ドローン",
  "Netbreach Worm Cyberwar Drone": "Netbreach Worm サイバー戦ドローン",
  "Decoyvex Mimic Decoy Drone": "Decoyvex Mimic 囮ドローン",
  "Overflux Spam Saturation Drone": "Overflux Spam 飽和攻撃ドローン",
  "Warvex Relay War Relay Drone": "Warvex Relay 戦闘通信中継ドローン",
  "Deadzone Null Signal Denial Drone": "Deadzone Null 通信遮断ドローン",
  "Prowltek Scan Active Surveillance Drone": "Prowltek Scan 能動監視ドローン",
  "Fakevex Ghost Spoofer Drone": "Fakevex Ghost 信号偽装ドローン",
  "Trigex Locate Triangulation Drone": "Trigex Locate 三角測量ドローン",
  "Megahack Siege Heavy Hacker Drone": "Megahack Siege 重ハッキングドローン",
  "Silencex Cut Anti-Comm Drone": "Silencex Cut 通信妨害ドローン",
  "Cipherbreak Crack Cryptanalysis Drone": "Cipherbreak Crack 暗号解析ドローン",
  "Earworm Tap Tactical Listening Drone": "Earworm Tap 戦術盗聴ドローン",
  "Netsting Harass Network Harassment Drone": "Netsting Harass ネットワーク妨害ドローン",
  "Mudcrawl Trekker All-Terrain Drone": "Mudcrawl Trekker 全地形対応ドローン",
  "Aquavex Ranger Amphibious Drone": "Aquavex Ranger 水陸両用ドローン",
  "Rubblerun Climber Rubble Drone": "Rubblerun Climber 瓦礫走破ドローン",
  "Frostcrawl Polar Arctic Drone": "Frostcrawl Polar 極地用ドローン",
  "Vinecrawl Tropic Jungle Drone": "Vinecrawl Tropic 密林用ドローン",
  "Pipecrawl Sewer Sewer Drone": "Pipecrawl Sewer 下水道用ドローン",
  "Peakcrawl Summit Mountain Drone": "Peakcrawl Summit 山岳用ドローン",
  "Deepcrawl Miner Underground Drone": "Deepcrawl Miner 地下用ドローン",
  "Sandvex Nomad Desert Drone": "Sandvex Nomad 砂漠用ドローン",
  "Bogcrawl Wader Swamp Drone": "Bogcrawl Wader 湿地用ドローン",
  "Streetcrawl Tank Reinforced Urban Drone": "Streetcrawl Tank 市街地用強化ドローン",
  "Woodvex Ranger Forest Drone": "Woodvex Ranger 森林用ドローン",
  "Lavacrawl Ember Volcanic Drone": "Lavacrawl Ember 火山用ドローン",
  "Treadvex Grinder Tracked Drone": "Treadvex Grinder 無限軌道ドローン",
  "Wallcrawl Spider Climbing Drone": "Wallcrawl Spider 壁面登攀ドローン",
  "Tundravex Drift Tundra Drone": "Tundravex Drift ツンドラ用ドローン",
  "Divex Plunge Submersible Drone": "Divex Plunge 潜水ドローン",
  "Wreckcrawl Ruin Ruins Drone": "Wreckcrawl Ruin 廃墟用ドローン",
  "Legvex Strider Legged Drone": "Legvex Strider 歩行ドローン",
  "Borecrawl Worm Tunnel Drone": "Borecrawl Worm 地下道用ドローン",
  "Rocketvex Salvo Rocket Drone": "Rocketvex Salvo ロケットドローン",
  "Skyguard Overwatch Air Support Drone": "Skyguard Overwatch 航空支援ドローン",
  "Aegisfly Barrier Shield Drone": "Aegisfly Barrier 防護ドローン",
  "Gasvex Cloud Gas Launcher Drone": "Gasvex Cloud ガスランチャードローン",
  "Scoutstrike Dual Armed Recon Drone": "Scoutstrike Dual 武装偵察ドローン",
  "Overwing Support Tactical Aid Drone": "Overwing Support 戦術支援ドローン",
  "Grapplefly Hook Cable Launcher Drone": "Grapplefly Hook ケーブルランチャードローン",
  "Minetek Scatter Mine Layer Drone": "Minetek Scatter 地雷敷設ドローン",
  "Barricadex Wall Barrage Drone": "Barricadex Wall 阻止ドローン",
  "Stratex Command C&C Drone": "Stratex Command 指揮統制ドローン",
  "Skybreaker Flak Anti-Air Drone": "Skybreaker Flak 対空ドローン",
  "Wreckvex Hammer Demolition Drone": "Wreckvex Hammer 解体ドローン",
  "Hazefly Smoke Smoke Grenade Drone": "Hazefly Smoke 発煙弾ドローン",
  "Patchvex Field Terrain Repair Drone": "Patchvex Field 地形修復ドローン",
  "Lurevex Trap Bait Drone": "Lurevex Trap 誘引ドローン",
  "GarbageTek Dumpster Disguise Drone": "GarbageTek Dumpster 偽装ドローン",
  "FrostBite Cream Armored Ice Cream Truck": "FrostBite Cream 装甲アイスクリーム販売車",
  "CartBlitz Motorized Shopping Cart": "CartBlitz Motorized 電動ショッピングカート",
  "RoombaX Titan Giant Vacuum": "RoombaX Titan 巨大掃除機",
  "TacoStrike Armed Taco Van": "TacoStrike Armed 武装タコス販売車",
  "WarBus Alpha Converted School Bus": "WarBus Alpha 改造スクールバス",
  "TrashWar Compactor Combat Garbage Truck": "TrashWar Compactor 戦闘ゴミ収集車",
  "MailStorm Mk.III Armored Mail Van": "MailStorm Mk.III 装甲郵便車",
  "LawnRage Mower Combat Lawnmower": "LawnRage Mower 戦闘芝刈り機",
  "BoxHaul Nomad Sentient Moving Truck": "BoxHaul Nomad 自我を持つ引越しトラック",
  "MediJack Siren Hijacked Ambulance": "MediJack Siren 強奪された救急車",
  "ForkLift Fury War Forklift": "ForkLift Fury 戦闘フォークリフト",
  "SpinCycle Roller Rolling Washing Machine": "SpinCycle Roller 走行洗濯機",
  "VendBot Prowl Mobile Vending Machine": "VendBot Prowl 移動自動販売機",
  "Xerox Fury Combat Photocopier": "Xerox Fury 戦闘コピー機",
  "RodeoBots Mk.V Mechanical Bull": "RodeoBots Mk.V 機械闘牛",
  "Widow Heavy Armored Spider": "Widow Heavy 重装甲クモ",
  "SteedTek Gallop Robotic Horse": "SteedTek Gallop ロボット馬",
  "StingMax Emperor Giant Scorpion": "StingMax Emperor 巨大サソリ",
  "ApeTek Silverback Mechanical Gorilla": "ApeTek Silverback 機械ゴリラ",
  "Pincervex Ironclad Armored Crab": "Pincervex Ironclad 装甲カニ",
  "OstrichWar Sprint Combat Ostrich": "OstrichWar Sprint 戦闘ダチョウ",
  "ShellMax Bunker Fortress Tortoise": "ShellMax Bunker 要塞リクガメ",
  "HippoTek Crusher Armored Hippo": "HippoTek Crusher 装甲カバ",
  "CoilVex Anaconda Articulated Snake": "CoilVex Anaconda 多関節ヘビ",
  "BeakHaul Scoop Cargo Pelican": "BeakHaul Scoop 貨物運搬ペリカン",
  "RhinoBlitz Ram Charging Rhino": "RhinoBlitz Ram 突撃サイ",
  "OctoGrip Tentacle Mechanical Octopus": "OctoGrip Tentacle 機械タコ",
  "MantisVex Blade Giant Mantis": "MantisVex Blade 巨大カマキリ",
  "GeckoMax Wall Climbing Lizard": "GeckoMax Wall 壁面登攀トカゲ",
  "SpaFly Bubbles Flying Hot Tub": "SpaFly Bubbles 空飛ぶジャグジー",
  "DoomSphere Roll Rolling Ball of Doom": "DoomSphere Roll 転がる破滅の球体",
  "BounceWar Jump Combat Trampoline": "BounceWar Jump 戦闘トランポリン",
  "CouchCruise Lazy Motorized Couch": "CouchCruise Lazy 電動ソファ",
  "BunkTek Mobile Rolling Bunk Bed": "BunkTek Mobile 走行2段ベッド",
  "ThroneTek Fortress Armored Toilet": "ThroneTek Fortress 装甲トイレ",
  "GrandSlam Keys Combat Grand Piano": "GrandSlam Keys 戦闘グランドピアノ",
  "PhoneCrawl Retro Rolling Phone Booth": "PhoneCrawl Retro 走行電話ボックス",
  "FridgeWar Chill War Refrigerator": "FridgeWar Chill 戦闘冷蔵庫",
  "PoolRun Splash Motorized Inflatable Pool": "PoolRun Splash 電動ビニールプール",
  "JackpotBot Lucky Rolling Slot Machine": "JackpotBot Lucky 走行スロットマシン",
  "KingCrawl Majesty Motorized Royal Throne": "KingCrawl Majesty 電動王座",
  "LiftGhost Shaft Wandering Elevator Car": "LiftGhost Shaft 徘徊するエレベーターかご",
  "PharaohTek Tomb Armored Sarcophagus": "PharaohTek Tomb 装甲石棺",
  "TubCrawl Soak Tracked Bathtub": "TubCrawl Soak 無限軌道式浴槽",
  "SteamStride Brass Steam Walker": "SteamStride Brass 蒸気式歩行機",
  "Clockwerk Spinner Clockwork Spider": "Clockwerk Spinner 時計仕掛けのクモ",
  "BrassGuard Empire Victorian Tank": "BrassGuard Empire ヴィクトリア朝風戦車",
  "TrainWreck Express Armored Locomotive": "TrainWreck Express 装甲機関車",
  "ZeppelinWar Helios Combat Blimp": "ZeppelinWar Helios 戦闘飛行船",
  "GearTank Crank Gear-Driven Tank": "GearTank Crank 歯車駆動戦車",
  "Automatek Colossus Giant Automaton": "Automatek Colossus 巨大自動人形",
  "CoachSteam Phantom Steam Carriage": "CoachSteam Phantom 蒸気馬車",
  "WindMill Walker Walking Windmill": "WindMill Walker 歩く風車",
  "PipeOrgan Thunder Rolling Pipe Organ": "PipeOrgan Thunder 走行パイプオルガン",
  "HandTek Grasp Giant Articulated Hand": "HandTek Grasp 巨大多関節ハンド",
  "ArtWalk Abstract Walking Sculpture": "ArtWalk Abstract 歩く彫刻",
  "EyeBall Gaze Giant Rolling Eye": "EyeBall Gaze 転がる巨大な眼球",
  "HeadTek Hover Giant Floating Head": "HeadTek Hover 浮遊する巨大な頭",
  "CalderBot Swing Giant Mobile": "CalderBot Swing 巨大なモビール",
  "MirrorCube Reflect Rolling Mirror Cube": "MirrorCube Reflect 走行鏡面立方体",
  "FountainBot Splash Walking Fountain": "FountainBot Splash 歩く噴水",
  "NeonWalk Glow Walking Giant Neon": "NeonWalk Glow 歩く巨大ネオン看板",
  "SpiralBot Spin Rolling Kinetic Spiral": "SpiralBot Spin 回転走行する螺旋彫刻",
  "DollTek Uncanny Giant Articulated Mannequin": "DollTek Uncanny 巨大多関節マネキン",
  "PizzaBlitz Delivery Pizza Tank": "PizzaBlitz Delivery ピザ戦車",
  "SushiTrack Roll Sushi Conveyor": "SushiTrack Roll 寿司コンベア",
  "GrillWar Smoke Armored Rolling BBQ": "GrillWar Smoke 装甲移動バーベキュー台",
  "FryStrike Deep Combat Fryer": "FryStrike Deep 戦闘フライヤー",
  "BreadTek Oven Mobile Bakery": "BreadTek Oven 移動パン屋",
  "WokRun Sizzle Giant Wok on Wheels": "WokRun Sizzle 車輪付き巨大中華鍋",
  "BrewTank Espresso Armored Coffee Machine": "BrewTank Espresso 装甲コーヒーマシン",
  "WienerBot Mustard Giant Rolling Hot Dog": "WienerBot Mustard 転がる巨大ホットドッグ",
  "RamenRig Broth Ramen Truck": "RamenRig Broth ラーメントラック",
  "FreezeTek Blast Combat Freezer": "FreezeTek Blast 戦闘冷凍庫",
  "GladiaTek Arena Gladiator Walker": "GladiaTek Arena 剣闘士型歩行機",
  "BushidoBot Ronin Samurai Walker": "BushidoBot Ronin 侍型歩行機",
  "ConcreteTek Titan Concrete Golem": "ConcreteTek Titan コンクリート・ゴーレム",
  "RiddleTek Oracle Mechanical Sphinx": "RiddleTek Oracle 機械スフィンクス",
  "NorseTek Berserker Mechanical Viking": "NorseTek Berserker 機械ヴァイキング",
  "KnightTek Crusader Mechanical Knight": "KnightTek Crusader 機械騎士",
  "SumoBot Yokozuna Robotic Sumo": "SumoBot Yokozuna ロボット力士",
  "WrestleTek Champ Mechanical Wrestler": "WrestleTek Champ 機械レスラー",
  "LegionBot March Rolling Centurion": "LegionBot March 走行百人隊長",
  "ToreroTek Faena Mechanical Matador": "ToreroTek Faena 機械闘牛士",
  "TreeBot Lumber Walking Mechanical Tree": "TreeBot Lumber 歩く機械樹木",
  "GyroTek Balance Giant Rolling Gyroscope": "GyroTek Balance 転がる巨大ジャイロスコープ",
  "FishTank Patrol Mobile Armored Aquarium": "FishTank Patrol 移動装甲水槽",
  "BirdCage Warden Giant Birdcage": "BirdCage Warden 巨大鳥かご",
  "HydrantTek Geyser Giant Fire Hydrant": "HydrantTek Geyser 巨大消火栓",
  "WorldBot Spin Rolling Globe": "WorldBot Spin 転がる地球儀",
  "UmbrellaTek Shield Giant Armored Umbrella": "UmbrellaTek Shield 巨大装甲傘",
  "PanBot Sizzle Giant Frying Pan on Legs": "PanBot Sizzle 脚付き巨大フライパン",
  "TowerTek Roam Mobile Control Tower": "TowerTek Roam 移動管制塔",
  "LighthouseBot Beam Rolling Lighthouse": "LighthouseBot Beam 走行灯台",
  "JukeWar Beat Armored Rolling Jukebox": "JukeWar Beat 装甲移動ジュークボックス",
  "SnailTek Crawl Giant Mechanical Snail": "SnailTek Crawl 巨大機械カタツムリ",
  "ChairBlitz Throne War Wheelchair": "ChairBlitz Throne 戦闘車椅子",
  "ClockTek Pendulum Walking Grandfather Clock": "ClockTek Pendulum 歩く振り子時計",
  "ShroomBot Spore Giant Mechanical Mushroom": "ShroomBot Spore 巨大機械キノコ"
};
