/**
 * Japanese descriptions for the NPC generator's gear templates.
 *
 * The companion of npc-generator-data-ja.ts, split off because the
 * descriptions are an order of magnitude larger than the names and reviewing
 * them in the same file would be impractical. The key is the same: the
 * upstream French `name`, nested under featType, for the reasons set out in
 * that file's header.
 *
 * Every value carries the same <p> markup as the source description. The
 * generator writes it straight into the item's description field, which
 * Foundry renders as HTML, so a dropped or unbalanced tag would be visible on
 * the sheet. npc-generator-descs-ja.test.ts checks the tag sequence of every
 * entry against the upstream description it replaces.
 *
 * A template with no entry here falls back to English, exactly as before.
 */

export const FEAT_DESCS_JA: Record<string, Record<string, string>> = {
  armor: {
    'Veste synthécuir renforcée': '<p>控えめな弾道インサートを仕込んだ合成皮革のジャケット。</p>',
    'Hoodie blindé UrbanWall': '<p>弾道繊維の裏地を備えたフーディ。</p>',
    'T-shirt renforcé IronThread': '<p>パラアラミド繊維製のTシャツ。軽量で目立たない。</p>',
    'Blouson de moto SteetHide': '<p>肘にプロテクターを備えた複合皮革のバイカージャケット。</p>',
    'Chemise blindée CorpoGuard': '<p>弾道繊維を織り込んだ上品なドレスシャツ。企業との会談に最適。</p>',
    'Gilet pare-balles Apex Shield': '<p>衣服の下に着込む軽量の防弾ベスト。</p>',
    'Veste tactique ShadowVest': '<p>着脱可能なセラミックプレートを備えた黒のタクティカルジャケット。</p>',
    'Pardessus blindé TrenchLine': '<p>弾道裏地と強化された襟を備えたロングコート。</p>',
    'Combinaison de course RunShield': '<p>関節部にプロテクターを内蔵したスポーツスーツ。</p>',
    'Gilet de sécurité WatchGuard': '<p>レベル III の弾道プレートを備えた民間警備用ベスト。</p>',
    'Manteau blindé NightShield': '<p>セラミックプレートを内蔵したロングコート。スタイルと防護を兼ね備える。</p>',
    'Armure urbaine StreetFort': '<p>交換可能なプレートを備えたモジュール式のアーバンアーマー一式。</p>',
    "Combinaison d'assaut StormSuit": '<p>敵性環境での作戦用に強化されたスーツ。</p>',
    'Cape blindée IronCape': '<p>弾道防護を備えた複合繊維製のロングクローク。</p>',
    'Armure corporelle tactique TacForce': '<p>軍用級のフル・ボディアーマー。目立たないどころではない。</p>',
    'Armure de combat Vanguard': '<p>弾道防護と対破片防護を備えたフル・コンバットアーマー。</p>',
    'Exosquelette léger FrameGuard': '<p>装甲プレートを統合した部分的なエクソスケルトン。</p>',
    'Armure anti-émeute RiotMax': '<p>強化バイザーを備えた重装の暴動鎮圧アーマー。</p>',
    'Exo-armure lourde Titan': '<p>部分的なエクソスケルトンを備えた重装甲。企業の特殊部隊が使用する。</p>',
    'Armure de siège Bulwark': '<p>正面突撃と制圧のために設計された超重装甲。</p>',
    'Gilet urbain NeoWeave': '<p>軽量な NeoWeave 繊維のベスト。バレンズでの日常に最適。</p>',
    'Poncho blindé DustRunner': '<p>再生ケブラーの裏地を備えたゆったりしたポンチョ。ノマドに人気。</p>',
    'Plastron discret SlimPlate': '<p>シャツの下に着込む極薄のチェストガード。ほぼ探知されない。</p>',
    'Veste cargo ToughLine': '<p>肩と胴を補強した頑丈なカーゴジャケット。</p>',
    'Bandana blindé StreetWrap': '<p>首と顔の下半分を覆う弾道繊維のバンダナ。</p>',
    'Duster blindé RoadWarden': '<p>裏地に軽量プレートを縫い込んだロードコート。</p>',
    'Blouson de vol ArmorWing': '<p>腕と背にセラミック補強を備えたパイロットジャケット。</p>',
    'Combinaison ouvrière ForgeSkin': '<p>弾道補強を統合した難燃性の作業用カバーオール。</p>',
    'Kimono renforcé SilkSteel': '<p>合成スパイダーシルク製の伝統的な着物。刃物に強い。</p>',
    'Parka arctique IceShell': '<p>装甲を内蔵した断熱パーカ。寒冷地作戦用に設計された。</p>',
    'Armure modulaire HexPlate': '<p>複合セラミックの六角プレートで構成された装甲。任務ごとに再構成できる。</p>',
    'Harnais de combat WarRig': '<p>着脱可能な装甲プレートと装備取付点を備えた重装タクティカルハーネス。</p>',
    'Robe de combat mystico-blindée ArcaneVeil': '<p>弾道繊維とマナ伝導フィラメントを織り込んだロングローブ。</p>',
    "Plastron d'assaut CrashCore": '<p>衝撃吸収機構を内蔵した大型の軽合金チェストプレート。</p>',
    'Armure intégrale BunkerSuit': '<p>自立式の空気濾過システムを備えた密閉式フル・ボディアーマー。</p>',
    'Carapace de sécurité SentinelShell': '<p>メガコープの精鋭警備兵が用いる硬質カラパス。</p>',
    'Armure de tranchée IronBastion': '<p>強化されたすね当てと喉当てを備えた重装の陣地防御用アーマー。</p>',
    'Combinaison blindée OgreMail': '<p>トロールの中世装甲に着想を得た、複合素材を重ねた鎖帷子のスーツ。</p>',
    'Armure de puissance Juggernaut': '<p>サーボモーターと強化セラミック装甲を備えた軍用クラスのパワードアーマー。</p>',
    'Exo-blindage Colossus': '<p>エクソスケルトンに搭載する大型の外部装甲。都市の破壊作戦用に設計された。</p>',
  },
  cyberdeck: {
    'Cyberdeck Ghostline 3700': '<p>中級のサイバーデッキ。ファイアウォールと攻撃力のバランスが良い。</p>',
    'Cyberdeck PixelWave Starter': '<p>入門用のサイバーデッキ。初心者デッカーに最適。</p>',
    'Cyberdeck DataForge Mk.I': '<p>頑丈で信頼できるモデル。フリーランサーに人気。</p>',
    'Cyberdeck NovaPulse Runner': '<p>敵性地帯での機動性に最適化された小型サイバーデッキ。</p>',
    'Cyberdeck GridRunner Eco': '<p>直感的なインターフェースと低消費電力を備えた廉価モデル。</p>',
    'Cyberdeck OmniDyne Pulse': '<p>日常的なハッキング作業向けの汎用サイバーデッキ。</p>',
    'Cyberdeck ShadowByte Mini': '<p>市場で最小のサイバーデッキ。ポケットに収まる。</p>',
    'Cyberdeck TechHive Basic': '<p>量産された基本サイバーデッキ。信頼できるが飾りはない。</p>',
    'Cyberdeck Prism Nexus': '<p>強化ファイアウォールと高度な攻撃モジュールを備えた高級サイバーデッキ。</p>',
    'Cyberdeck Ghostline 9000 Elite': '<p>量子プロセッサを統合した Ghostline の上位版。</p>',
    'Cyberdeck BlackVeil Phantom': '<p>企業ネットワークへの不可視侵入のために設計されたステルス・サイバーデッキ。</p>',
    'Cyberdeck Kurotech Ronin X': '<p>最適化されたニューラル・インターフェースを備えた日本製の精密サイバーデッキ。</p>',
    'Cyberdeck DataForge Mk.III Pro': '<p>第三世代の DataForge。攻撃と防御のモジュールが均衡している。</p>',
    'Cyberdeck Meridian Warframe': '<p>民間市場向けに転用された軍用サイバーデッキ。素の性能は比類ない。</p>',
    'Cyberdeck NovaPulse Apex': '<p>マルチコア・プロセッサと能動的熱拡散を備えた NovaPulse の最上位機。</p>',
    'Cyberdeck VortexNet Razor': '<p>専用の総当たりモジュールを備え、攻撃的サイバー戦闘に最適化されている。</p>',
    'Cyberdeck SpectraCorp Sentinel': '<p>多層ファイアウォールと高度な侵入検知を備えた防御型サイバーデッキ。</p>',
    'Cyberdeck ZeroDay Exploit': '<p>ハッカーがハッカーのために設計した。個体ごとに仕様が異なる。</p>',
    'Cyberdeck OmniDyne Titan': '<p>最強の民間サイバーデッキ。軍用機材に匹敵する。</p>',
    'Cyberdeck ShadowByte Wraith': '<p>マトリックス上の痕跡がほぼ探知されない超ステルス・サイバーデッキ。</p>',
    'Cyberdeck StreetSpark Lite': '<p>金のないハッカー向けの超簡素なサイバーデッキ。ソイカフの缶に収まる。</p>',
    'Cyberdeck BinaryBudget V2': '<p>Budget シリーズの第二モデル。相応のファイアウォールを備えた防御寄り。</p>',
    'Cyberdeck NeonFlicker': '<p>ネオン LED を備えた派手なサイバーデッキ。地下クラブで人気。</p>',
    'Cyberdeck RustBucket Mk.II': '<p>錆びて見えるが機能する。廃品から組み上げられた品。</p>',
    'Cyberdeck WaveRider Compact': '<p>マトリックス巡航用の小型サイバーデッキ。軽量で目立たない。</p>',
    'Cyberdeck CipherNode Entry': '<p>暗号化と秘匿性に重点を置いた入門モデル。</p>',
    'Cyberdeck SubNet Crawler': '<p>マトリックスの忘れられた下層網の探索に特化している。</p>',
    'Cyberdeck HoloJack Slim': '<p>没入感のあるハッキング体験のためのホログラフィック・インターフェースを統合。</p>',
    'Cyberdeck ProbeLight Scanner': '<p>戦闘よりもネットワークの偵察と走査に最適化されている。</p>',
    'Cyberdeck IronClad Pocket': '<p>防御作戦向けの堅固なファイアウォールを備えたポケット・サイバーデッキ。</p>',
    'Cyberdeck QuantumEdge Sigma': '<p>マトリックス演算を超高速で行う最新世代の量子プロセッサ。</p>',
    'Cyberdeck NightFall Stealth': '<p>マトリックス上の痕跡が最小限のステルス・サイバーデッキ。侵入に最適。</p>',
    'Cyberdeck HyperVault Fortress': '<p>三重のファイアウォール層と量子隔離を備えたデジタル要塞。</p>',
    'Cyberdeck StrikeForce Omega': '<p>専用の攻撃モジュールを備え、攻撃的サイバー戦闘のために設計された。</p>',
    'Cyberdeck CrystalMind Nexus': '<p>完全に澄んだマトリックス接続を実現する結晶製ニューラル・インターフェース。</p>',
    'Cyberdeck TempestWare Havoc': '<p>敵性プログラムへ自動で反撃する軍用サイバーデッキ。</p>',
    'Cyberdeck NebulaCore Prime': '<p>NebulaCore の最上位機。市場で最強の民間用マトリックス・プロセッサ。</p>',
    'Cyberdeck VoidRunner Eclipse': '<p>マトリックス基盤への深層ダイブに最適化されている。</p>',
    'Cyberdeck ArcticByte Glacier': '<p>極端なオーバークロックを可能にする冷凍式の熱拡散。</p>',
    'Cyberdeck PhantomLink Ultra': '<p>追跡不能な幻影マトリックス接続。プロの選択。</p>',
  },
  awakened: {
    'Éveillé — Perception et Sorcellerie': '<p>このキャラクターは覚醒者である。アストラル界を知覚し、呪文を行使できる。</p>',
    'Éveillé — Perception, Sorcellerie et Conjuration': '<p>このキャラクターは覚醒者である。アストラル知覚、呪術、精霊の召喚を行える。</p>',
    'Éveillé — Projection astrale et Conjuration': '<p>このキャラクターはシャーマンである。アストラル投射と精霊の召喚を行える。</p>',
    'Éveillé — Perception astrale et Adepte': '<p>このキャラクターはフィジカル・アデプトである。マナを自らの肉体に通す。</p>',
  },
  emerged: {
    'Émergé — Persona vivante': '<p>このキャラクターはエマージドである。思考によってマトリックスに接続し、コンプレックス・フォームを編成する。</p>',
  },
  weapon: {
    'Couteau de combat Valkyr KS-3': '<p>カーバイドで補強された短い刃。</p>',
    'Dague Neon Arms Fang': '<p>両刃の複合セラミック製ダガー。</p>',
    'Couteau de survie Meridian Claw': '<p>鋸歯の刃を備えた頑丈なサバイバルナイフ。</p>',
    'Couteau papillon OmniDyne Flicker': '<p>磁力展開による超高速のバタフライナイフ。</p>',
    'Stiletto Apex Venom': '<p>装甲の隙間を狙って設計された細い刺突用の刃。</p>',
    'Lame rétractable Kurotech Razor': '<p>黒色チタン製の伸縮式スイッチブレード。</p>',
    'Machette Prismex Bushmaster': '<p>厚い刃を備えた汎用の短いマチェット。</p>',
    'Couteau de lancer NovaPulse Dart': '<p>投擲にも近接戦闘にも使える均衡の取れたナイフ。</p>',
    'Tanto Kurogane Ghost': '<p>炭素処理鋼による日本の短刀。</p>',
    'Kriss Titan Arms Serpent': '<p>切断用合金で現代化された伝統的な波状の刃。</p>',
    'Katana Kurogane Type-4': '<p>分子鋼の刀。剃刀のように鋭い。</p>',
    'Épée large Titan Arms Claymore': '<p>両手持ちの強化合金剣。近接戦で壊滅的。</p>',
    'Sabre Meridian Hussar': '<p>現代化された騎兵サーベル。軽く鋭い。</p>',
    'Rapière NovaPulse Estoc': '<p>超軽量のカーボンファイバー製フェンシング・レイピア。</p>',
    'Nodachi Kaze Tempest': '<p>間合いに優れた長大な両手持ちの日本刀。</p>',
    'Cimeterre Apex Crescent': '<p>斬撃に最適化された湾曲したシミター。</p>',
    'Épée vibrante Prismex Resonance': '<p>軽装甲を斬り裂く超音波振動の長刃。</p>',
    'Machette longue Valkyr Jungle King': '<p>敵性環境向けの厚刃のロングマチェット。</p>',
    'Batte renforcée Ironside': '<p>鉛の芯を備えた複合合金のバット。</p>',
    'Massue Titan Arms Ogre': '<p>フランジ付きの頭部を備えた重い焼入鋼のメイス。</p>',
    'Marteau NovaPulse Sledge': '<p>強化された頭部を備えた小型のウォーハンマー。</p>',
    'Nunchaku Kaze Whirlwind': '<p>収納式の鎖を備えた硬質ポリマーのヌンチャク。</p>',
    'Matraque télescopique Apex Enforcer': '<p>三段式の伸縮バトン。素早く展開できる。</p>',
    'Tonfas Meridian Guardian': '<p>カーボンファイバー製のトンファー一対。防御と攻撃の双方に使える。</p>',
    'Bâton bo Kurotech Sensei': '<p>収納式のチタン合金製の棒。</p>',
    'Morgenstern Valkyr Brute': '<p>棘付きの球を備えたフレイル。残虐で止められない。</p>',
    'Matraque shock Zapper': '<p>高電圧の電撃バトン。</p>',
    'Taser Neon Arms Volt': '<p>近距離用のパルス式テーザー。軽装甲にも有効。</p>',
    'Gants shock OmniDyne Thunder': '<p>接触時に放電する強化グローブ。</p>',
    'Fouet électrique Prismex Arc': '<p>打撃ごとに電撃を与える導電性のウィップ。</p>',
    'Lance shock Kaze Storm': '<p>高電圧で通電する先端を備えた絶縁ランス。</p>',
    'Lame monofilament Whisper': '<p>収納式のモノフィラメント・ウィップ。ほぼ何でも斬り裂く。</p>',
    'Chaîne monofilament Kurotech Reaper': '<p>モノフィラメントの鎖。専門家向けの武器。</p>',
    'Gantelet à griffes Apex Predator': '<p>収納式の単分子合金の爪を備えたガントレット。</p>',
    'Éventail de combat Kaze Mantis': '<p>刃を隠した鉄扇。優雅で致命的。</p>',
    'Kusarigama NovaPulse Shadow': '<p>重りを付けた鎖と鎌。伝統的な武器を現代化したもの。</p>',
    'Arts martiaux : Karaté Kurotech': '<p>強力な打撃に重点を置いた空手の修練。</p>',
    'Arts martiaux : Muay Thaï Kaze': '<p>壊滅的な肘と膝の技。</p>',
    'Arts martiaux : Krav Maga Valkyr': '<p>残忍で効率的な護身術。飾りはない。</p>',
    "Poings d'acier Titan Arms": '<p>重い焼入鋼のナックル。</p>',
    'Arts martiaux : Jiu-Jitsu NovaPulse': '<p>関節技と寝技による制圧の技。</p>',
    'Pied-de-biche Meridian Leverage': '<p>強化されたバール。工具にも即席の武器にもなる。</p>',
    'Chaîne lourde Titan Arms Anchor': '<p>即席のフレイルとして使う重い鎖。</p>',
    'Tuyau en acier Apex Sewer King': '<p>拾った鉄パイプ。ストリートの武器の代表格。</p>',
    'Clé à molette Prismex Wrecker': '<p>特大のパイプレンチ。重く恐ろしい。</p>',
    'Bouteille cassée Neon Arms Last Call': '<p>強化ガラスの割れた瓶。酒場の定番武器。</p>',
    'Lames de poignet Kurotech Mantis': '<p>前腕に埋め込まれた収納式の刃。</p>',
    'Griffes cyber Apex Lynx': '<p>爪の下に仕込んだサイバネティックな爪。常に隠されている。</p>',
    'Éperon cybernétique OmniDyne Spike': '<p>不意打ち用の収納式の肘スパイク。</p>',
    'Main-lame Valkyr Edge': '<p>手のひらに統合された刃。瞬時に展開する。</p>',
    'Couteau tactique Meridian Talon': '<p>反射を抑えた黒い刃のタクティカルナイフ。</p>',
    'Kukri NovaPulse Gorkhali': '<p>強化された湾曲刃を備えた現代化ネパール製ククリ。</p>',
    'Couteau Bowie Titan Arms Frontier': '<p>高性能ステンレス鋼の大型ボウイナイフ。</p>',
    'Couteau céramique Kaze Silent': '<p>全セラミック製のナイフ。金属探知機では探知できない。</p>',
    'Karambit Apex Scorpion': '<p>湾曲刃のカランビット。近接戦の技法のために設計された。</p>',
    'Dirk OmniDyne Highland': '<p>直線的で耐久性のある合金刃を備えたスコットランドのダーク。</p>',
    'Couteau pliant Neon Arms Switchback': '<p>ベルトクリップ付きの開刃補助機構を備えた折りたたみナイフ。</p>',
    'Couteau de plongée Prismex Depth': '<p>鋸歯の刃を備えた防蝕のダイビングナイフ。</p>',
    'Poignard trench Valkyr Doughboy': '<p>ナックルガードを統合したトレンチナイフ。</p>',
    'Lame dissimulée Kurotech Shade': '<p>ペンに隠した極薄の刃。探知されない。</p>',
    'Épée bâtarde Titan Arms Conquest': '<p>片手半剣。汎用性が高く壊滅的。</p>',
    'Falchion Apex Cleaver': '<p>厚く幅広の刃を備えたファルシオン。強力な打撃に最適。</p>',
    'Wakizashi Kaze Moonlight': '<p>折り返し鍛錬の鋼による日本の脇差。</p>',
    'Gladius NovaPulse Centurion': '<p>現代化されたローマのグラディウス。短く扱いやすい。</p>',
    'Épée laser Prismex Photon': '<p>封じ込めたプラズマの刃。中装甲を斬り裂く。</p>',
    'Flamberge OmniDyne Inferno': '<p>波状の刃を持つ剣。治りにくい傷を与える。</p>',
    'Dao Kurotech Dragon': '<p>片刃の中国の青龍刀。素早い連撃に合わせて調整されている。</p>',
    'Claymore vibro Valkyr Earthquake': '<p>震動を伝えるクレイモア。打撃ごとに骨まで響く。</p>',
    'Kanabo Kaze Oni': '<p>複合鋼による棘付きの日本の金棒。</p>',
    "Fléau d'armes Titan Arms Crusher": '<p>二つの球を備えた戦闘フレイル。衝撃は壊滅的。</p>',
    'Matraque tactique NovaPulse Pacifier': '<p>重量級の暴動鎮圧用バトン。堅牢で威圧的。</p>',
    "Masse d'armes Meridian Paladin": '<p>六角の頭部を備えた戦闘メイス。装甲を打ち破る。</p>',
    'Bâton escrima Apex Dual Strike': '<p>堅木とカーボンファイバーのエスクリマ・スティック一対。</p>',
    'Marteau de guerre Prismex Goliath': '<p>タングステンの頭部を備えた重いウォーハンマー。</p>',
    'Bokken OmniDyne Senshi': '<p>強化された稽古用の木刀。鋼のように硬い。</p>',
    'Batte cloutée Neon Arms Basher': '<p>釘を打ち込んだ野球バット。ギャングを象徴する武器。</p>',
    'Taser longue portée Apex Bolt': '<p>射程を 10 メートルまで延伸したダート式テーザー。</p>',
    'Bâton choc Valkyr Thunderstrike': '<p>二箇所の接触点を備えた通電する長棒。</p>',
    'Poing shock Kurotech Jolt': '<p>放電機構を統合したナックル。</p>',
    'Filet électrifié NovaPulse NetShock': '<p>対象を拘束して感電させる導電性のネット。</p>',
    'Lasso shock Meridian Lariat': '<p>接触時に高電圧を流す導電性のラッソ。</p>',
    'Chaîne-faucille Titan Arms Harvester': '<p>モノフィラメントの刃を備えた重りつきの鎖鎌。</p>',
    'Urumi Kaze Serpent': '<p>しなやかなインドのばね鋼の剣。予測しがたく致命的。</p>',
    'Tekko-kagi NovaPulse Shadow Hand': '<p>単分子合金による忍びの手甲鉤。</p>',
    'Sai Prismex Trident': '<p>チタン製の釵一対。武器落としと打撃に最適。</p>',
    'Fouet à lame Valkyr Hydra': '<p>刃を組み込んだ分節式のウィップ。間合いと切り裂きを兼ねる。</p>',
    'Arts martiaux : Wing Chun Apex': '<p>手の速さと近距離戦に重点を置いた流派。</p>',
    'Arts martiaux : Capoeira Meridian': '<p>曲芸的なブラジルの武術。強力で予測しがたい蹴り。</p>',
    'Arts martiaux : Systema OmniDyne': '<p>流れるようなロシアの武術。関節技と投げ技を用いる。</p>',
    'Arts martiaux : Savate NovaPulse': '<p>優雅なフランスの拳闘。精確で技術的な蹴り。</p>',
    'Arts martiaux : Pencak Silat Kaze': '<p>インドネシアの武術。流れる動きと容赦のない打撃。</p>',
    'Extincteur Apex Firefight': '<p>即席の棍棒として使う重い消火器。</p>',
    'Barre à mine Kurotech Breaker': '<p>重い鋼の掘削バー。工事現場の恐るべき武器。</p>',
    "Panneau d'arrêt Neon Arms Halt": '<p>引き抜いた止まれ標識。ストリートを象徴する即席の武器。</p>',
    "Câble d'acier Prismex Garrote": '<p>絞殺用に使う撚り合わせた鋼製ケーブル。静かで致命的。</p>',
    'Clé en croix OmniDyne Roadkill': '<p>自動車用のクロスレンチ。頑丈で手に入りやすい。</p>',
    'Lame de doigt Kurotech Stiletto': '<p>人差し指に埋め込んだ収納式の極小の刃。</p>',
    'Lame de tibia NovaPulse Shin Edge': '<p>サイバネティックな脛から展開する刃。</p>',
    'Crocs cyber Apex Fang': '<p>切断用合金による強化されたサイバネティックな犬歯。</p>',
    'Queue cyber Prismex Tail Spike': '<p>収納式の棘を備えたサイバネティックな尾。究極の不意打ち武器。</p>',
    'Neon Arms Stiletto .22': '<p>小型のポケットピストル。隠し持ちやすい。</p>',
    'Prismex Whisper .25': '<p>消音機構を内蔵したピストル。潜入に最適。</p>',
    'OmniDyne Minnow .22LR': '<p>二連発のデリンジャー。手のひらに収まる。</p>',
    'Kaze Petal .22': '<p>超薄型のセラミック製ピストル。走査では探知できない。</p>',
    'Meridian Cricket .25': '<p>五発装弾の予備用小型ピストル。</p>',
    'Apex Sentinel 9mm': '<p>信頼できる軽量ピストル。分別のあるランナーの選択。</p>',
    'Valkyr P9 Compact': '<p>反動を抑えた小型の 9mm。扱いやすい。</p>',
    'Kurogane Sparrow 9mm': '<p>ホログラフィック照準器を統合した軽量ピストル。</p>',
    'NovaPulse Guardian 9mm': '<p>民間警備部隊の標準装備ピストル。</p>',
    'Titan Arms Deputy .38': '<p>古典的な軽量リボルバー。信頼でき安価。</p>',
    'Meridian Civic 9mm': '<p>普及した民間向けピストル。低価格で量産されている。</p>',
    'Neon Arms Lynx 9mm': '<p>タクティカルレイルと制退器を備えた軽量ピストル。</p>',
    'Prismex Halo 9mm': '<p>クローム仕上げと延長弾倉を備えた意匠性の高いピストル。</p>',
    'Valkyr HK-7': '<p>発射選択機構を備えた小型の自動ピストル。</p>',
    'Kurogane Rapid 10mm': '<p>延長弾倉を備えた高速連射の自動ピストル。</p>',
    'Apex Staccato Auto': '<p>折りたたみ銃床を備えたポケット・マシンピストル。</p>',
    'Meridian Tempest Auto': '<p>反動制退器を統合した自動ピストル。</p>',
    'NovaPulse Burst-9': '<p>三点射のピストル。精確で制御しやすい。</p>',
    'Apex Ironside .44': '<p>重量級のリボルバー。轟音と痛みを伴う。</p>',
    'Titan Arms Rhino .45': '<p>強化銃身を備えた重量級の半自動ピストル。</p>',
    'Valkyr Warhawk .44 Magnum': '<p>大型のマグナム・リボルバー。素の制圧力に優れる。</p>',
    'Kurogane Enforcer 10mm': '<p>複列弾倉を備えた重量級の 10mm ピストル。</p>',
    'Neon Arms Nomad .50': '<p>口径 .50 のピストル。反動は凶暴だがダメージは絶大。</p>',
    'Meridian Judge .357': '<p>つや消し鋼の汎用重量級リボルバー。</p>',
    'Prismex Dominator .45 ACP': '<p>競技用の重量級ピストル。精度と威力を兼ね備える。</p>',
    'Valkyr Pixie .22': '<p>短銃身の超小型ポケットピストル。</p>',
    'Titan Arms Mouse .25': '<p>強化ポリマー製の極小ピストル。</p>',
    'Apex Wasp .22': '<p>安全装置を統合したダブルアクションのポケットピストル。</p>',
    'OmniDyne Protector 9mm': '<p>人間工学的な把持部と速装弾倉を備えた軽量ピストル。</p>',
    'Kaze Breeze 9mm': '<p>命中精度を高める浮動銃身を備えた日本製の軽量ピストル。</p>',
    'Titan Arms Scout .380': '<p>サブコンパクトの .380 ピストル。隠し持ちに最適。</p>',
    'Meridian Peacekeeper 9mm': '<p>企業の警備部隊が用いる信頼できる装備ピストル。</p>',
    'Kaze Typhoon Auto': '<p>連射速度可変で点射機構を備えた自動ピストル。</p>',
    'Titan Arms Rattler Auto': '<p>銃口制退器を統合した小型マシンピストル。</p>',
    'Prismex Torrent Auto': '<p>螺旋弾倉を備えた高速連射の自動ピストル。</p>',
    'OmniDyne Firestorm Auto': '<p>急速冷却機構を備えた自動ピストル。</p>',
    'Neon Arms Hornet Auto': '<p>超軽量の自動ピストル。移動しながらの射撃に最適。</p>',
    'OmniDyne Mammoth .50': '<p>大型の .50 口径ピストル。素の威力は比類ない。</p>',
    'Kaze Thunder .44': '<p>強化シリンダーと放気銃身を備えた重量級リボルバー。</p>',
    'NovaPulse Titan .45': '<p>高度な反動制退器を備えた重量級の半自動ピストル。</p>',
    'Neon Arms Colossus .454': '<p>怪物じみた .454 リボルバー。入手できる拳銃口径で最大。</p>',
    'Apex Executioner .50 AE': '<p>レーザー照準器を統合した .50 AE の半自動ピストル。</p>',
    'Kurotech Shogun .44': '<p>つや消し黒仕上げと長銃身を備えた日本製の重量級リボルバー。</p>',
    'Kurogane AR-77': '<p>標準的なアサルトライフル。汎用性が高く信頼できる。</p>',
    'Valkyr Commando 5.56': '<p>近接戦闘作戦向けの小型アサルトライフル。</p>',
    'Titan Arms Warrior 7.62': '<p>重量級のバトルライフル。口径 7.62 で火力に優れる。</p>',
    'Neon Arms Spectre 5.56': '<p>消音器を統合した小型のブルパップ式アサルトライフル。</p>',
    'Meridian Patriot 6.8': '<p>汎用レイル系を備えたモジュール式アサルトライフル。</p>',
    'Meridian Scorpio': '<p>ポンプ式のショットガン。近距離では壊滅的。</p>',
    'Titan Arms Boomstick': '<p>銃身を切り詰めたショットガン。小型で壊滅的。</p>',
    'Valkyr Breacher Auto-12': '<p>ドラム弾倉を備えた 12 番の半自動ショットガン。</p>',
    'Kurogane Street Sweeper': '<p>高速連射の回転式ショットガン。面の掃討を確実にする。</p>',
    'NovaPulse Marksman X': '<p>ジャイロ安定装置を備えた高性能スナイパーライフル。</p>',
    'Apex Longbow .338': '<p>二脚を統合した長距離精密ライフル。</p>',
    'Kurotech Phantom .50 BMG': '<p>重量級の対物ライフル。軽装甲を貫通する。</p>',
    'Valkyr Wraith SR': '<p>消音器とスマート照準器を備えたモジュール式スナイパーライフル。</p>',
    'Apex Warden 5.56': '<p>中距離の精度を高める重銃身の信頼できるアサルトライフル。</p>',
    'OmniDyne Centurion 6.5': '<p>中間口径 6.5 のバトルライフル。汎用性が高く精確。</p>',
    'Prismex Phantom 5.56': '<p>消音器とフリーフロート銃身を統合したステルス・アサルトライフル。</p>',
    'Kurotech Ronin 7.62': '<p>日本製の 7.62 バトルライフル。頑丈で壊滅的。</p>',
    'Apex Thunderclap': '<p>伸縮銃床を備えたポンプ式のタクティカル・ショットガン。</p>',
    'NovaPulse Hydra-12': '<p>反動を緩和する機構を備えた半自動ショットガン。</p>',
    'Neon Arms Riot Master': '<p>20 発のドラム弾倉を備えた暴動鎮圧用ショットガン。</p>',
    'Prismex Undertaker': '<p>上下二連式の双銃身ショットガン。壊滅的な二射を放つ。</p>',
    'Meridian Deadeye .308': '<p>熱線照準器を統合した .308 精密ライフル。</p>',
    'Titan Arms Basilisk .416': '<p>対物用の .416 ライフル。中装甲を貫通する。</p>',
    'OmniDyne Specter SR': '<p>熱光学迷彩機構を備えた分解式スナイパーライフル。</p>',
    'Neon Arms Reaper .338': '<p>ねじ切り銃身とカーボン二脚を備えた長距離精密ライフル。</p>',
    'Kaze Whisperwind .300': '<p>消音された .300 スナイパーライフル。極めて遠く、音は最小限。</p>',
    'Kurogane Viper SMG': '<p>小型のサブマシンガン。市街戦に最適。</p>',
    'Neon Arms Hornet SMG': '<p>超軽量で高速連射のサブマシンガン。</p>',
    'Apex Sidewinder PDW': '<p>収納式銃床を備えた小型の個人防衛火器。</p>',
    'Meridian Cyclone 10mm': '<p>頑丈な 10mm のサブマシンガン。制圧力に優れる。</p>',
    'Prismex Vector 9mm': '<p>平衡錘機構で反動を大幅に抑えたサブマシンガン。</p>',
    'Valkyr Tempest SMG': '<p>折りたたみ銃床と前方把持部を備えたタクティカル・サブマシンガン。</p>',
    'Titan Arms Bulldog PDW': '<p>小型で頑丈な個人防衛火器。ボディガードに好まれる。</p>',
    'OmniDyne Razor SMG': '<p>連射速度を調整できる軽量ポリマー製サブマシンガン。</p>',
    'Kurotech Whisper SMG': '<p>一体型の消音器と亜音速弾を用いる消音サブマシンガン。</p>',
    'Neon Arms Firefly SMG': '<p>大容量の螺旋弾倉を備えた極小のサブマシンガン。</p>',
    'Titan Arms Devastator': '<p>重機関銃。制圧を確実にする。</p>',
    'Apex Thunder Lance': '<p>六連発の半自動グレネードランチャー。</p>',
    'NovaPulse Hellfire ATRL': '<p>レーザー誘導の対戦車ロケットランチャー。一射で足りる。</p>',
    'Valkyr Annihilator LMG': '<p>水冷機構を備えた軽機関銃。</p>',
    'Meridian Hellstorm GL': '<p>12 連発の回転式自動グレネードランチャー。</p>',
    'Kurotech Raijin ATRL': '<p>赤外線捕捉機構を備えた携行式ロケットランチャー。</p>',
    'Couteaux de lancer Kaze': '<p>均衡の取れた投げナイフ一組。</p>',
    'Shurikens Kaze Eclipse': '<p>空力に優れた焼入鋼の手裏剣。</p>',
    'Grenades frag Apex': '<p>標準的な破片グレネード。</p>',
    'Grenades fumigènes Meridian Haze': '<p>速やかに拡散する催涙ガス・グレネード。</p>',
    'Haches de lancer Titan Arms Tomahawk': '<p>均衡の取れた焼入鋼の投斧。</p>',
    'Bolas Meridian Tangle': '<p>ケブラーの紐を備えた重りつきのボーラ。対象を拘束する。</p>',
    'Grenades flash Apex Sunburst': '<p>高輝度で視界を奪う閃光グレネード。</p>',
    'Grenades EMP NovaPulse Blackout': '<p>電磁パルス・グレネード。電子機器を無力化する。</p>',
  },
};

/** The Japanese description for a template, or undefined to fall back to English. */
export function featDescJa(featType: string, name: string): string | undefined {
  return FEAT_DESCS_JA[featType]?.[name];
}
