/**
 * Japanese names for the NPC generator's gear templates.
 *
 * npc-generator-data.ts carries French and English names on every template
 * (`name` / `nameEn`), and the generator writes one of them into the created
 * actor's items. Those templates have no id or slug: their identity is the
 * French `name` string. Rather than add a third field to the 835 KB upstream
 * table — which would collide on every merge from upstream — the Japanese
 * names live here, keyed by the French name, and a template with no entry
 * falls back to English exactly as before.
 *
 * The key is nested under featType because the same French name exists as a
 * spell, an adept power and a trait, and upstream gives some of those
 * different English names (Résistance à la douleur is Pain Relief, Pain
 * Resistance and Pain Tolerance). A flat map would silently merge them.
 *
 * Nothing here comes from a rulebook: the products are the upstream author's
 * own inventions. Only the category word is translated; the invented product
 * name stays in Latin script, as SRA2.FEATS.WEAPON.TYPES.* already does for
 * the real-world weapon names.
 *
 * A key that no longer matches a template would silently stop working, so
 * npc-generator-data-ja.test.ts fails on one.
 */

export const FEAT_NAMES_JA: Record<string, Record<string, string>> = {
  armor: {
    'Veste synthécuir renforcée': '強化シンセレザー・ジャケット',
    'Hoodie blindé UrbanWall': 'UrbanWall 装甲フーディ',
    'T-shirt renforcé IronThread': 'IronThread 強化Tシャツ',
    'Blouson de moto SteetHide': 'StreetHide バイカージャケット',
    'Chemise blindée CorpoGuard': 'CorpoGuard 装甲ドレスシャツ',
    'Gilet pare-balles Apex Shield': 'Apex Shield 防弾ベスト',
    'Veste tactique ShadowVest': 'ShadowVest タクティカルジャケット',
    'Pardessus blindé TrenchLine': 'TrenchLine 装甲オーバーコート',
    'Combinaison de course RunShield': 'RunShield レーシングスーツ',
    'Gilet de sécurité WatchGuard': 'WatchGuard セキュリティベスト',
    'Manteau blindé NightShield': 'NightShield 装甲コート',
    'Armure urbaine StreetFort': 'StreetFort アーバンアーマー',
    "Combinaison d'assaut StormSuit": 'StormSuit アサルトスーツ',
    'Cape blindée IronCape': 'IronCape 装甲クローク',
    'Armure corporelle tactique TacForce': 'TacForce タクティカル・ボディアーマー',
    'Armure de combat Vanguard': 'Vanguard コンバットアーマー',
    'Exosquelette léger FrameGuard': 'FrameGuard 軽量エクソスケルトン',
    'Armure anti-émeute RiotMax': 'RiotMax 暴動鎮圧アーマー',
    'Exo-armure lourde Titan': 'Titan 重エクソアーマー',
    'Armure de siège Bulwark': 'Bulwark シージアーマー',
    'Gilet urbain NeoWeave': 'NeoWeave アーバンベスト',
    'Poncho blindé DustRunner': 'DustRunner 装甲ポンチョ',
    'Plastron discret SlimPlate': 'SlimPlate 隠匿型チェストガード',
    'Veste cargo ToughLine': 'ToughLine カーゴジャケット',
    'Bandana blindé StreetWrap': 'StreetWrap 装甲バンダナ',
    'Duster blindé RoadWarden': 'RoadWarden 装甲ダスターコート',
    'Blouson de vol ArmorWing': 'ArmorWing フライトジャケット',
    'Combinaison ouvrière ForgeSkin': 'ForgeSkin ワーカーカバーオール',
    'Kimono renforcé SilkSteel': 'SilkSteel 強化着物',
    'Parka arctique IceShell': 'IceShell アークティックパーカ',
    'Armure modulaire HexPlate': 'HexPlate モジュラーアーマー',
    'Harnais de combat WarRig': 'WarRig コンバットハーネス',
    'Robe de combat mystico-blindée ArcaneVeil': 'ArcaneVeil 魔術戦闘ローブ',
    "Plastron d'assaut CrashCore": 'CrashCore アサルト・チェストプレート',
    'Armure intégrale BunkerSuit': 'BunkerSuit フルボディアーマー',
    'Carapace de sécurité SentinelShell': 'SentinelShell セキュリティ・カラペイス',
    'Armure de tranchée IronBastion': 'IronBastion トレンチアーマー',
    'Combinaison blindée OgreMail': 'OgreMail 装甲スーツ',
    'Armure de puissance Juggernaut': 'Juggernaut パワーアーマー',
    'Exo-blindage Colossus': 'Colossus エクソプレーティング',
  },

  cyberware: {
    'Cyberbras Meridian Mk.III': 'Meridian Mk.III サイバーアーム',
    'Cyberbras TitanGrip Industriel': 'TitanGrip Industrial サイバーアーム',
    'Cyberbras Solaris Elite': 'Solaris Elite サイバーアーム',
    'Cyberjambes Apex Strider': 'Apex Strider サイバーレッグ',
    'Cyberjambes Vantage Sprint': 'Vantage Sprint サイバーレッグ',
    'Cyberjambes Ironclad Siege': 'Ironclad Siege サイバーレッグ',
    'Cybermains Dextra Precision': 'Dextra Precision サイバーハンド',
    'Cybermains Ferox Combat': 'Ferox Combat サイバーハンド',
    'Cyberpieds Gecko Tread': 'Gecko Tread サイバーフット',
    'Cyberpieds Silentrun': 'Silentrun サイバーフット',
    'Torse cybernétique Aegis Core': 'Aegis Core サイバートルソ',
    'Torse cybernétique Nexagen Vital': 'Nexagen Vital サイバートルソ',
    'Cyberbras Helix Tactical': 'Helix Tactical サイバーアーム',
    'Cyberjambes Kraken Aqua': 'Kraken Aqua サイバーレッグ',
    'Cybermains Artisan Mk.V': 'Artisan Mk.V サイバーハンド',
    'Réflexes câblés Kurotech Série 9': 'Kurotech Series 9 ワイアード・リフレックス',
    'Réflexes câblés Pulsefire Alpha': 'Pulsefire Alpha ワイアード・リフレックス',
    'Boosteur de réflexes Veloce R3': 'Veloce R3 ブーステッド・リフレックス',
    'Amplificateur de réaction Syntech': 'Syntech 反応強化装置',
    'Accélérateur kinétique Bolt': 'Bolt 運動加速装置',
    "Module d'agilité Valkyr Flex": 'Valkyr Flex 敏捷モジュール',
    'Système de réaction Overclock': 'Overclock 反応システム',
    'Câblage rapide NeuroFlash': 'NeuroFlash クイックワイアリング',
    'Stabilisateur gyroscopique Axion': 'Axion ジャイロ安定装置',
    "Régulateur d'adrénaline Surge": 'Surge アドレナリン調整装置',
    'Yeux cyber Prismex Hawk-Eye': 'Prismex Hawk-Eye サイバーアイ',
    'Yeux cyber Oculon Nightseer': 'Oculon Nightseer サイバーアイ',
    'Yeux cyber Spectra Wideband': 'Spectra Wideband サイバーアイ',
    'Oreilles cyber Sonatek Clarity': 'Sonatek Clarity サイバーイヤー',
    'Oreilles cyber Echoware Pro': 'Echoware Pro サイバーイヤー',
    'Oreilles cyber Audiomex Range': 'Audiomex Range サイバーイヤー',
    'Boosteur olfactif Scentex': 'Scentex 嗅覚ブースター',
    'Boosteur olfactif Nasalyze V2': 'Nasalyze V2 嗅覚ブースター',
    'Sonar ultrasonique Batwave': 'Batwave 超音波センサー',
    'Module de vision Targetex HUD': 'Targetex HUD 視覚モジュール',
    'Rétine cyber Photex Flash': 'Photex フラッシュ・サイバー網膜',
    'Capteur tactile Dermasen': 'Dermasen 触覚センサー',
    'Radar interne Pulsewave': 'Pulsewave 体内レーダー',
    'Yeux cyber Iridex Panoramic': 'Iridex パノラマ・サイバーアイ',
    'Analyseur vocal Phonex': 'Phonex 音声解析装置',
    'Plaque dermique Ironhide II': 'Ironhide II 皮膚装甲',
    'Plaque dermique Coreguard Titan': 'Coreguard Titan 皮膚装甲',
    'Renforcement osseux TitanFrame': 'TitanFrame ボーンレーシング',
    'Renforcement osseux Ferrocast': 'Ferrocast ボーンレーシング',
    'Renforcement osseux Carbide Mk.II': 'Carbide Mk.II ボーンレーシング',
    'Trame cutanée Silksteel': 'Silksteel スキンウィーブ',
    'Trame cutanée Nanoweave': 'Nanoweave スキンウィーブ',
    'Blindage sous-cutané Shellweave': 'Shellweave 皮下装甲',
    'Revêtement anti-impact Shockguard': 'Shockguard 耐衝撃コーティング',
    'Plaque dermique Scaletech V3': 'Scaletech V3 皮膚装甲',
    'Datajack OmniDyne V2': 'OmniDyne V2 データジャック',
    'Datajack Cortex Link': 'Cortex Link データジャック',
    'Datajack Neurogate Wireless': 'Neurogate 無線データジャック',
    'Skillwires Mnemotech Basic': 'Mnemotech Basic スキルワイヤ',
    'Skillwires Synapticore Plus': 'Synapticore Plus スキルワイヤ',
    'Processeur tactique NovaMind': 'NovaMind 戦術プロセッサ',
    'Processeur tactique StratOS': 'StratOS 戦術コンピュータ',
    'SPU mathématique Calcyon': 'Calcyon 数学 SPU',
    'SPU mathématique Numera Pro': 'Numera Pro 数学 SPU',
    'Amplificateur mémoriel Recallex': 'Recallex 記憶増幅装置',
    'Encéphalographe Mindscape': 'Mindscape 脳波記録装置',
    'Chipjack NeuroSlot': 'NeuroSlot チップジャック',
    'Interface neurale Bridgepoint': 'Bridgepoint 神経インターフェース',
    'Processeur linguistique Babelware': 'Babelware 言語プロセッサ',
    'Co-processeur analytique Logix': 'Logix 分析コプロセッサ',
    'Lien smartgun Aimlink': 'Aimlink スマートガン・リンク',
    'Lien smartgun Bullseye Pro': 'Bullseye Pro スマートガン・リンク',
    'Compensateur de recul Steadyarm': 'Steadyarm 反動補正装置',
    'Compensateur de recul Ironfist': 'Ironfist 反動補正装置',
    "Support d'arme interne Concealer": 'Concealer 体内ウェポンマウント',
    'Lame rétractable Razorback': 'Razorback 伸縮式ブレード',
    'Griffes cybernétiques Predex': 'Predex サイバークロー',
    'Éperonnage cybernétique Ramhorn': 'Ramhorn サイバースパー',
    'Système de visée intégré Vortex': 'Vortex 統合照準システム',
    'Lanceur de projectiles Spikefist': 'Spikefist 射出装置',
    'Modulateur vocal Echomask': 'Echomask ボイス・モジュレーター',
    'Modulateur vocal Charismatek': 'Charismatek ボイス・モジュレーター',
    'Émetteur phéromonal Allure': 'Allure フェロモン放出装置',
    'Émetteur phéromonal Apex Dominance': 'Apex Dominance フェロモン放出装置',
    'Phéromones ajustées Velvetscent': 'Velvetscent 調整フェロモン',
    'Phéromones ajustées Serenex': 'Serenex 調整フェロモン',
    'Implant facial Morphex': 'Morphex 顔面インプラント',
    'Synthétiseur émotionnel Empathex': 'Empathex 情動シンセサイザー',
    'Régulateur hormonal Calmex': 'Calmex ホルモン調整装置',
    'Module de projection vocale SonicCharm': 'SonicCharm 音声投射モジュール',
    "Réserve d'air interne Breathguard": 'Breathguard 体内エアタンク',
    "Réserve d'air interne DeepLung": 'DeepLung 体内エアタンク',
    'Filtre toxique Zenith': 'Zenith 毒素フィルター',
    'Filtre toxique PureLine': 'PureLine 毒素フィルター',
    'Analyseur chimique Chemex': 'Chemex 化学分析装置',
    'Analyseur chimique Reagex': 'Reagex 化学分析装置',
    'Commlink cybernétique Nexlink': 'Nexlink サイバー・コムリンク',
    'Système de localisation Pathfinder': 'Pathfinder 位置特定システム',
    'Enregistreur sensoriel Blackbox': 'Blackbox 感覚記録装置',
    'Compartiment interne Stashware': 'Stashware 体内コンパートメント',
    'Régulateur thermique Thermocore': 'Thermocore 体温調整装置',
    'Stimulateur médical AutoDoc': 'AutoDoc 医療スティミュレーター',
    'Balise de détresse Beacon': 'Beacon 救難信号装置',
    'Pompe à médicaments Pharmaflow': 'Pharmaflow ドラッグポンプ',
    'Interface véhiculaire Drivelink': 'Drivelink 車両インターフェース',
    'Cyberbras Ares Predator Mk.IV': 'Ares Predator Mk.IV サイバーアーム',
    'Cyberbras Renraku Shinobi': 'Renraku Shinobi サイバーアーム',
    'Cyberjambes Shiawase Kumo': 'Shiawase Kumo サイバーレッグ',
    'Cyberjambes Saeder-Krupp Blitz': 'Saeder-Krupp Blitz サイバーレッグ',
    'Cyberbras Mitsuhama Ronin': 'Mitsuhama Ronin サイバーアーム',
    'Cybermains Aztechnology Xochitl': 'Aztechnology Xochitl サイバーハンド',
    'Torse cybernétique Evo Bogatyr': 'Evo Bogatyr サイバートルソ',
    'Cyberjambes NovaTech Valkyrie': 'NovaTech Valkyrie サイバーレッグ',
    'Cyberbras Wuxing Jade Dragon': 'Wuxing Jade Dragon サイバーアーム',
    'Cyberpieds Horizon Danseur': 'Horizon Dancer サイバーフット',
    'Réflexes câblés Ares Quicksilver': 'Ares Quicksilver ワイアード・リフレックス',
    'Boosteur synaptique Renraku Hayai': 'Renraku Hayai シナプス・ブースター',
    'Accélérateur nerveux Shiawase Raiden': 'Shiawase Raiden 神経加速装置',
    'Module de vitesse Saeder-Krupp Blitzkrieg': 'Saeder-Krupp Blitzkrieg スピードモジュール',
    'Système nerveux augmenté Mitsuhama Kaze': 'Mitsuhama Kaze 神経系強化装置',
    'Réflexes amplifiés NovaTech Spark': 'NovaTech Spark 反射強化装置',
    'Accélérateur cinétique Evo Momentum': 'Evo Momentum 運動加速装置',
    'Câblage neural Aztechnology Quetzal': 'Aztechnology Quetzal 神経配線',
    'Stabilisateur inertiel Wuxing Fenghuang': 'Wuxing Fenghuang 慣性安定装置',
    'Amplificateur musculaire Horizon Zephyr': 'Horizon Zephyr 筋力増幅装置',
    'Yeux cyber Ares Eagle Vision': 'Ares Eagle Vision サイバーアイ',
    'Yeux cyber Renraku Panopticon': 'Renraku Panopticon サイバーアイ',
    'Oreilles cyber Shiawase Kitsune': 'Shiawase Kitsune サイバーイヤー',
    'Capteur lidar Saeder-Krupp Argus': 'Saeder-Krupp Argus ライダーセンサー',
    'Module infrarouge Mitsuhama Hinome': 'Mitsuhama Hinome 赤外線モジュール',
    'Analyseur biométrique Evo Vitascan': 'Evo Vitascan 生体計測解析装置',
    'Réseau sensoriel NovaTech Omnisense': 'NovaTech Omnisense センサーネットワーク',
    'Amplificateur auditif Aztechnology Ocelot': 'Aztechnology Ocelot 音声増幅装置',
    'Détecteur de mouvement Wuxing Longyan': 'Wuxing Longyan 動体検知装置',
    'Scanner électromagnétique Horizon Pulse': 'Horizon Pulse 電磁スキャナー',
    'Blindage dermique Ares Fortress': 'Ares Fortress 皮膚装甲',
    'Renforcement osseux Renraku Adamant': 'Renraku Adamant 骨強化',
    'Trame cutanée Shiawase Yoroi': 'Shiawase Yoroi スキンウィーブ',
    'Plaque dermique Saeder-Krupp Panzerung': 'Saeder-Krupp Panzerung 皮膚装甲',
    'Gel protecteur Mitsuhama Kappa': 'Mitsuhama Kappa 防護ゲル',
    'Ossature renforcée Evo Endosteel': 'Evo Endosteel 強化骨格',
    'Revêtement cutané NovaTech Aegis': 'NovaTech Aegis 皮膚コーティング',
    'Blindage thoracique Aztechnology Jaguar': 'Aztechnology Jaguar 胸部装甲',
    'Fibres de protection Wuxing Tianlong': 'Wuxing Tianlong 防護繊維',
    'Matrice protectrice Horizon Shellshock': 'Horizon Shellshock 防護マトリクス',
    'Datajack Ares Overwatch': 'Ares Overwatch データジャック',
    'Processeur cognitif Renraku Tenshi': 'Renraku Tenshi 認知プロセッサ',
    'Interface de contrôle Shiawase Puppeteer': 'Shiawase Puppeteer 制御インターフェース',
    'Encéphalon Saeder-Krupp Denker': 'Saeder-Krupp Denker エンセファロン',
    'Skillwires Mitsuhama Gakusha': 'Mitsuhama Gakusha スキルワイヤ',
    'Réseau neural Evo Synapse': 'Evo Synapse ニューラルネットワーク',
    'Interface matricielle NovaTech DeepDive': 'NovaTech DeepDive マトリックス・インターフェース',
    'Processeur linguistique Aztechnology Nahuatl': 'Aztechnology Nahuatl 言語プロセッサ',
    'Amplificateur de volonté Wuxing Iron Mind': 'Wuxing Iron Mind 意志力増幅装置',
    'Module de coordination Horizon Maestro': 'Horizon Maestro 協調モジュール',
    'Smartlink Ares Predator Elite': 'Ares Predator Elite スマートリンク',
    'Lame rétractable Renraku Tanto': 'Renraku Tanto 伸縮式ブレード',
    'Canon à fléchettes Shiawase Hornet': 'Shiawase Hornet フレシェット・ガン',
    'Griffes vibrantes Saeder-Krupp Kralle': 'Saeder-Krupp Kralle バイブロクロー',
    'Système de visée Mitsuhama Sharpshooter': 'Mitsuhama Sharpshooter 照準システム',
    'Compensateur de recul Evo Ironwrist': 'Evo Ironwrist 反動補正装置',
    'Éperon osseux NovaTech Mantis': 'NovaTech Mantis ボーンスパー',
    'Lanceur de micro-grenades Aztechnology Xibalba': 'Aztechnology Xibalba マイクログレネード・ランチャー',
    'Fouet monofilament Wuxing Serpent': 'Wuxing Serpent モノフィラメント・ウィップ',
    'Poing-marteau Horizon Thunderfist': 'Horizon Thunderfist ハンマーフィスト',
    'Modulateur vocal Ares Commander': 'Ares Commander ボイス・モジュレーター',
    'Implant phéromonal Renraku Geisha': 'Renraku Geisha フェロモン・インプラント',
    'Synthétiseur facial Shiawase Noh': 'Shiawase Noh 顔面シンセサイザー',
    'Régulateur émotionnel Saeder-Krupp Eisherz': 'Saeder-Krupp Eisherz 情動調整装置',
    'Diffuseur chimique Mitsuhama Kitsune': 'Mitsuhama Kitsune 化学拡散装置',
    'Amplificateur charismatique Evo Persona': 'Evo Persona カリスマ増幅装置',
    'Interface sociale NovaTech Mirror': 'NovaTech Mirror ソーシャル・インターフェース',
    'Projecteur subliminal Aztechnology Tonal': 'Aztechnology Tonal サブリミナル投射装置',
    'Modulateur hormonal Wuxing Harmony': 'Wuxing Harmony ホルモン調節装置',
    'Émetteur sonore Horizon Siren': 'Horizon Siren ソニック放出装置',
    'Filtration hépatique Ares CleanSweep': 'Ares CleanSweep 肝臓濾過装置',
    'Réservoir interne Renraku Tanuki': 'Renraku Tanuki 体内貯蔵器',
    'Recycleur respiratoire Shiawase Kaze-no-Iki': 'Shiawase Kaze-no-Iki 呼吸リサイクラー',
    'GPS inertiel Saeder-Krupp Kompass': 'Saeder-Krupp Kompass 慣性 GPS',
    'Commlink cranien Mitsuhama Whisper': 'Mitsuhama Whisper 頭蓋内コムリンク',
    'Régulateur métabolique Evo Homeostasis': 'Evo Homeostasis 代謝調整装置',
    'Module de survie NovaTech Lifeline': 'NovaTech Lifeline サバイバルモジュール',
    'Interface véhiculaire Aztechnology Tezcatlipoca': 'Aztechnology Tezcatlipoca 車両インターフェース',
    'Compartiment blindé Wuxing Baoxiang': 'Wuxing Baoxiang 装甲コンパートメント',
    'Système médical Horizon FirstResponder': 'Horizon FirstResponder 医療システム',
    'Nanoruche interne Ares Swarm': 'Ares Swarm 体内ナノハイブ',
    'Camouflage thermique Renraku Ghost': 'Renraku Ghost 熱迷彩',
    'Doigts-outils Shiawase MultiTool': 'Shiawase MultiTool フィンガーツール',
    'Générateur de champ magnétique Saeder-Krupp Polaris': 'Saeder-Krupp Polaris 磁場発生装置',
    'Implant de récupération Mitsuhama Phoenix': 'Mitsuhama Phoenix 回復インプラント',
    'Système anti-choc Evo Resilience': 'Evo Resilience 耐衝撃システム',
    'Propulseurs de saut NovaTech Grasshopper': 'NovaTech Grasshopper ジャンプブースター',
    'Émetteur de brouillage Aztechnology Huitzilopochtli': 'Aztechnology Huitzilopochtli ジャミング放出装置',
    'Glandes surrénales augmentées Wuxing Longwei': 'Wuxing Longwei 副腎強化',
    'Sous-système de récupération Horizon Rebirth': 'Horizon Rebirth 回復サブシステム',
    'Derme photovoltaïque Shiawase Solaris': 'Shiawase Solaris 太陽光発電皮膚',
    'Système de refroidissement Saeder-Krupp Frostbyte': 'Saeder-Krupp Frostbyte 冷却システム',
    'Réacteur de secours Mitsuhama Backup': 'Mitsuhama Backup 非常用リアクター',
    'Blindage crânien Evo Cranium': 'Evo Cranium 頭蓋装甲',
    'Amortisseurs spinaux NovaTech Flex': 'NovaTech Flex 脊椎ダンパー',
    'Cœur cybernétique Aztechnology Corazón': 'Aztechnology Corazon サイバネティック心臓',
    'Interface de rigging Wuxing Dragon Rider': 'Wuxing Dragon Rider リギング・インターフェース',
    'Amplificateur musculaire Horizon Atlas': 'Horizon Atlas 筋力増幅装置',
    'Système circulatoire Renraku Bloodstream': 'Renraku Bloodstream 循環系',
    'Processeur de combat Ares Warmonger': 'Ares Warmonger 戦闘プロセッサ',
    'Muscles augmentés BioGen Alpha': 'BioGen Alpha 強化筋肉',
    'Muscles augmentés VitaForce Pro': 'VitaForce Pro 強化筋肉',
    'Muscles augmentés Titanex Bulk': 'Titanex Bulk 強化筋肉',
    'Tonifiant musculaire Flexigen': 'Flexigen マッスルトナー',
    'Tonifiant musculaire Agilyx': 'Agilyx マッスルトナー',
    'Tonifiant musculaire Litheform': 'Litheform マッスルトナー',
    'Augmentation musculaire Myocore': 'Myocore 筋肉増強',
    'Augmentation musculaire Dynacell': 'Dynacell 筋肉増強',
    'Tendons bio-renforcés Elastex': 'Elastex 生体強化腱',
    'Ligaments bio-améliorés Springtex': 'Springtex 生体強化靱帯',
    'Fibres de puissance Goliath': 'Goliath パワーファイバー',
    'Diaphragme renforcé Oxacore': 'Oxacore 強化横隔膜',
    'Fascia réactif Shieldex': 'Shieldex 反応性筋膜',
    'Muscle cardiaque renforcé Endurex': 'Endurex 強化心筋',
    'Muscles dorsaux Ironback': 'Ironback 背筋強化',
    'Densité osseuse Marrowtech': 'Marrowtech 骨密度強化',
    'Densité osseuse Calcitex Ultra': 'Calcitex Ultra 骨密度強化',
    'Orthopeau Dermatex Basic': 'Dermatex Basic オルソスキン',
    'Orthopeau NanoSkin Plus': 'NanoSkin Plus オルソスキン',
    'Renforcement cartilagineux Flexbone': 'Flexbone 軟骨強化',
    'Renforcement cartilagineux JointFlex': 'JointFlex 軟骨強化',
    'Moelle osseuse améliorée Hemagen': 'Hemagen 骨髄強化',
    'Squelette flexible Rubberbone': 'Rubberbone 柔軟骨格',
    'Cage thoracique renforcée Ribguard': 'Ribguard 強化胸郭',
    'Colonne vertébrale élastique Spineflex': 'Spineflex 弾性脊椎',
    'Réflexes synaptiques NeuroCorp': 'NeuroCorp シナプス・ブースター',
    'Booster synaptique Reflexa': 'Reflexa シナプス・ブースター',
    'Booster synaptique Velocine': 'Velocine シナプス・ブースター',
    'Booster cérébral Cognivex': 'Cognivex 大脳ブースター',
    'Booster cérébral Intellex Pro': 'Intellex Pro 大脳ブースター',
    'Booster cérébral Neuramax': 'Neuramax 大脳ブースター',
    'Amplificateur mnémonique Memovault': 'Memovault 記憶強化装置',
    'Amplificateur mnémonique Recollex': 'Recollex 記憶強化装置',
    'Réseau neural optimisé ThinkFast': 'ThinkFast 最適化神経網',
    'Cortex émotionnel stabilisé Equanix': 'Equanix 安定化情動皮質',
    'Noyau intuitif Hunchware': 'Hunchware 直感コア',
    'Centre du langage amélioré Linguex': 'Linguex 言語中枢強化',
    'Suppresseur de douleur Paingate': 'Paingate 痛覚抑制装置',
    'Concentrateur cortical Focusyn': 'Focusyn 皮質集中装置',
    'Réseau nerveux étendu NervNet': 'NervNet 拡張神経網',
    'Oreille interne augmentée SonicBio': 'SonicBio 内耳強化',
    'Ouïe augmentée Audiograft': 'Audiograft 聴覚強化',
    'Ouïe augmentée Echolocalis': 'Echolocalis 聴覚強化',
    'Odorat augmenté Nasalex': 'Nasalex 嗅覚強化',
    'Odorat augmenté Tracker Bio': 'Tracker Bio 嗅覚強化',
    'Yeux de chat NightGraft': 'NightGraft キャッツアイ',
    'Yeux de chat Felinex': 'Felinex キャッツアイ',
    'Langue sensorielle Gustex': 'Gustex 感覚舌',
    'Vibrisses bio-greffées Whiskertech': 'Whiskertech 生体移植触毛',
    'Peau photosensible Solarsense': 'Solarsense 光感受性皮膚',
    'Glandes surrénales boost OrganTech': 'OrganTech 副腎ブースト',
    'Pompe adrénaline Surgetex': 'Surgetex アドレナリンポンプ',
    'Pompe adrénaline Combatex': 'Combatex アドレナリンポンプ',
    'Glande suprathyroïdienne Metabolex': 'Metabolex 上甲状腺',
    'Glande suprathyroïdienne Thyromax': 'Thyromax 上甲状腺',
    'Expansion digestive Gutworks': 'Gutworks 消化器拡張',
    'Expansion digestive Omnivex': 'Omnivex 消化器拡張',
    'Glande endorphinique Blisswave': 'Blisswave エンドルフィン腺',
    'Glande de croissance Growthex': 'Growthex 成長腺',
    'Sécréteur de cortisol Stressbane': 'Stressbane コルチゾール分泌腺',
    'Glande phéromonale Trustex': 'Trustex フェロモン腺',
    'Régulateur hormonal Homeostex': 'Homeostex ホルモン調整装置',
    'Sécréteur de mélatonine Sleepguard': 'Sleepguard メラトニン分泌腺',
    'Glande oxytocique Bondex': 'Bondex オキシトシン腺',
    'Sécréteur de dopamine Motivex': 'Motivex ドーパミン分泌腺',
    'Coeur augmenté Cardiomax': 'Cardiomax 強化心臓',
    'Coeur augmenté Pulsedrive': 'Pulsedrive 強化心臓',
    'Usine plaquettaire Plateletex': 'Plateletex 血小板産生器',
    'Usine plaquettaire Hemoguard': 'Hemoguard 血小板産生器',
    'Symbiotes cellulaires VitaCell': 'VitaCell 細胞共生体',
    'Symbiotes cellulaires Regenerex': 'Regenerex 細胞共生体',
    'Vaisseaux renforcés Vasculex': 'Vasculex 強化血管',
    'Sang oxygéné Oxycyte': 'Oxycyte 酸素化血液',
    'Rate augmentée Splenex': 'Splenex 脾臓強化',
    'Système lymphatique amélioré Lymphoguard': 'Lymphoguard リンパ系強化',
    'Peau symbiotique Veil': 'Veil 共生皮膚',
    'Orthopeau Armorex Bio': 'Armorex バイオ・オルソスキン',
    'Peau caméléon Chromaskin': 'Chromaskin カメレオンスキン',
    'Peau caméléon Mimicrex': 'Mimicrex カメレオンスキン',
    'Atténuation thermique Heatveil': 'Heatveil 熱減衰',
    'Atténuation thermique Coolskin': 'Coolskin 熱減衰',
    'Épiderme cicatrisant Healex': 'Healex 治癒表皮',
    'Peau anti-friction Slickskin': 'Slickskin 摩擦低減皮膚',
    'Peau électrifiée Sparkderm': 'Sparkderm 帯電皮膚',
    'Derme durci Toughskin': 'Toughskin 硬化皮膚',
    'Défense pathogène Immunex': 'Immunex 病原体防御',
    'Défense pathogène Viriguard': 'Viriguard 病原体防御',
    'Défense pathogène Biowall': 'Biowall 病原体防御',
    'Extracteur de toxines Purifax': 'Purifax 毒素抽出装置',
    'Extracteur de toxines Detoxgland': 'Detoxgland 毒素抽出装置',
    'Extracteur de toxines Clearblood': 'Clearblood 毒素抽出装置',
    'Amortisseur de trauma Shockbio': 'Shockbio トラウマ・ダンパー',
    'Amortisseur de trauma Resilex': 'Resilex トラウマ・ダンパー',
    'Amortisseur de trauma Nerveblock': 'Nerveblock トラウマ・ダンパー',
    'Globules blancs améliorés Leucomax': 'Leucomax 白血球強化',
    'Bouclier allergénique Histaguard': 'Histaguard アレルゲン・シールド',
    'Coagulation rapide Sealex': 'Sealex 急速凝固',
    'Glande anti-venin Serpentex': 'Serpentex 抗毒腺',
    'Nanites réparateurs Fixocyte': 'Fixocyte 修復ナノマシン',
    'Thymus régénéré Thymex': 'Thymex 再生胸腺',
    'Symbiote digestif Gutflora Pro': 'Gutflora Pro 消化共生体',
    'Symbiote digestif Nutrivore': 'Nutrivore 消化共生体',
    'Symbiote sanguin Oxycyte': 'Oxycyte 血液共生体',
    'Symbiote sanguin Hemoboost': 'Hemoboost 血液共生体',
    'Symbiote épidermique Biofilm': 'Biofilm 表皮共生体',
    'Symbiote neural Synapsyte': 'Synapsyte 神経共生体',
    'Symbiote musculaire Mycofibre': 'Mycofibre 筋肉共生体',
    'Symbiote osseux Calciphage': 'Calciphage 骨共生体',
    'Symbiote hépatique Livercyte': 'Livercyte 肝共生体',
    'Symbiote pulmonaire Aerocyte': 'Aerocyte 肺共生体',
    'Glande surrénale améliorée Adrenex': 'Adrenex 副腎強化',
    'Glande surrénale améliorée Surgex': 'Surgex 副腎強化',
    'Phéromones adaptés Sociolex': 'Sociolex 調整フェロモン',
    'Phéromones adaptés Charmex': 'Charmex 調整フェロモン',
    'Phéromones adaptés Dominex': 'Dominex 調整フェロモン',
    'Glande thyroïde optimisée Metabolex': 'Metabolex 最適化甲状腺',
    'Glande pituitaire boostée Growthex': 'Growthex 下垂体強化',
    'Glande pinéale augmentée Chronex': 'Chronex 松果体強化',
    'Pancréas bio-optimisé Insulex': 'Insulex 生体最適化膵臓',
    'Glande sudoripare modifiée Coolant': 'Coolant 改造汗腺',
    'Booster cérébral Cognex Alpha': 'Cognex Alpha 大脳ブースター',
    'Booster cérébral Neurex Prime': 'Neurex Prime 大脳ブースター',
    'Booster cérébral Thinktank': 'Thinktank 大脳ブースター',
    'Mémoire eidétique Mnemolex': 'Mnemolex 映像記憶',
    'Mémoire eidétique Recallex': 'Recallex 映像記憶',
    'Cortex analytique Logicex': 'Logicex 分析皮質',
    'Cortex créatif Artisanex': 'Artisanex 創造皮質',
    'Régulateur émotionnel Serenex': 'Serenex 情動調整装置',
    'Processeur linguistique Polyglotex': 'Polyglotex 言語プロセッサ',
    'Calculateur spatial Navicore': 'Navicore 空間計算装置',
    'Système vasculaire amélioré Hemocircuit': 'Hemocircuit 血管系強化',
    'Système vasculaire amélioré Flowmax': 'Flowmax 血管系強化',
    'Plaquettes améliorées Coagulex': 'Coagulex 血小板強化',
    'Sang oxygéné Vitablood': 'Vitablood 酸素化血液',
    'Veines renforcées Vasoguard': 'Vasoguard 強化静脈',
    'Pompe cardiaque auxiliaire Dualcore': 'Dualcore 補助心臓ポンプ',
    'Filtration sanguine Hemapure': 'Hemapure 血液濾過',
    'Rate améliorée Splenomax': 'Splenomax 脾臓強化',
    'Réseau lymphatique optimisé Lymphocore': 'Lymphocore 最適化リンパ網',
    'Valves cardiaques renforcées Valvex': 'Valvex 強化心臓弁',
    'Rétine améliorée Optigen': 'Optigen 網膜強化',
    'Rétine améliorée Hawkeye Bio': 'Hawkeye Bio 網膜強化',
    'Cochlée bio-amplifiée Audimax': 'Audimax 生体増幅蝸牛',
    'Cochlée bio-amplifiée Sonarex': 'Sonarex 生体増幅蝸牛',
    'Nerf olfactif amélioré Scentex': 'Scentex 嗅神経強化',
    'Papilles gustatives augmentées Tastex': 'Tastex 味蕾強化',
    'Vision nocturne bio Nyctalex': 'Nyctalex バイオ暗視',
    'Proprioception augmentée Kinesthex': 'Kinesthex 固有感覚強化',
    'Système vestibulaire amélioré Balancex': 'Balancex 平衡器官強化',
    'Thermorécepteurs améliorés Thermosense': 'Thermosense 温度受容器強化',
    'Articulation améliorée Flexpoint': 'Flexpoint 関節強化',
    'Articulation améliorée Pivotex': 'Pivotex 関節強化',
    'Synovie améliorée Lubricex': 'Lubricex 滑液強化',
    'Doigts articulés Dextrex': 'Dextrex 多関節指',
    'Doigts articulés Nimbleflex': 'Nimbleflex 多関節指',
    'Colonne articulée Serpentex': 'Serpentex 多関節脊椎',
    'Poignets rotatifs Gyrohand': 'Gyrohand 回転手首',
    'Chevilles renforcées Anklex': 'Anklex 強化足首',
    'Épaules hyper-mobiles Shouldex': 'Shouldex 超可動肩',
    'Hanches articulées Hipflex': 'Hipflex 多関節股関節',
    'Poumons améliorés Pneumex': 'Pneumex 強化肺',
    'Poumons améliorés Deepbreath': 'Deepbreath 強化肺',
    'Filtres nasaux Aeropure': 'Aeropure 鼻腔フィルター',
    'Trachée renforcée Windpipe': 'Windpipe 強化気管',
    'Bronches élargies Airmax': 'Airmax 拡張気管支',
    'Sinus oxygénateurs Oxyboost': 'Oxyboost 酸素供給副鼻腔',
    'Membrane alvéolaire Gasex': 'Gasex 肺胞膜',
    'Cordes vocales modifiées Voxmod': 'Voxmod 改造声帯',
    'Réserve pulmonaire Apnex': 'Apnex 肺予備量',
    'Cils bronchiques améliorés Mucosweep': 'Mucosweep 気管支繊毛強化',
    'Estomac renforcé Ironbelly': 'Ironbelly 強化胃',
    'Intestins optimisés Absorplex': 'Absorplex 最適化腸',
    'Métabolisme accéléré Burnrate': 'Burnrate 代謝促進',
    'Métabolisme accéléré Hypercore': 'Hypercore 代謝促進',
    'Réserves adipeuses tactiques Fatstore': 'Fatstore 戦術脂肪貯蔵',
    'Foie bio-augmenté Hepatex': 'Hepatex 生体強化肝臓',
    'Reins bio-optimisés Nephromax': 'Nephromax 生体最適化腎臓',
    'Enzymes digestives Catalyx': 'Catalyx 消化酵素',
    'Glandes salivaires modifiées Salimod': 'Salimod 改造唾液腺',
    'Microbiome optimisé Floracore': 'Floracore 最適化マイクロバイオーム',
    'Régénération tissulaire Regenex': 'Regenex 組織再生',
    'Régénération tissulaire Healwave': 'Healwave 組織再生',
    'Cicatrisation rapide Scarless': 'Scarless 急速瘢痕化',
    'Cellules souches activées Stemcell Pro': 'Stemcell Pro 活性化幹細胞',
    'Régénération nerveuse Neurogrow': 'Neurogrow 神経再生',
    'Os auto-réparateurs Osteofix': 'Osteofix 自己修復骨',
    'Muscles auto-réparateurs Myofix': 'Myofix 自己修復筋',
    'Peau régénérative Dermagrow': 'Dermagrow 再生皮膚',
    'Cartilage régénératif Chondrofix': 'Chondrofix 再生軟骨',
    'Tendons régénératifs Tendonex': 'Tendonex 再生腱',
    'Adaptation génétique Genomex': 'Genomex 遺伝的適応',
    'Adaptation génétique Evolux': 'Evolux 遺伝的適応',
    'Télomères rallongés Agelock': 'Agelock テロメア延長',
    'ADN stabilisé Geneguard': 'Geneguard DNA 安定化',
    'Phénotype adaptatif Morphex': 'Morphex 適応表現型',
    'Mitochondries améliorées Powercel': 'Powercel ミトコンドリア強化',
    'Protéines de choc Heatshield': 'Heatshield ショックタンパク質',
    'Collagène renforcé Dermagen': 'Dermagen コラーゲン強化',
    'Kératine bio-renforcée Nailclaw': 'Nailclaw 生体強化ケラチン',
    'Élastine améliorée Stretchex': 'Stretchex エラスチン強化',
  },

  equipment: {
    'Commlink NovaPulse X2': 'NovaPulse X2 コムリンク',
    'Faux SIN Rating 3': '偽造SIN 指数3',
    'Micro-caméra espion Lenstek': 'Lenstek スパイ・マイクロカメラ',
    'Scanneur de fréquences SpectraWave': 'SpectraWave 周波数スキャナー',
    'Brouilleur de signal portatif Hushline': 'Hushline 携帯型信号ジャマー',
    'Détecteur de mouchards SweepTech': 'SweepTech 盗聴器探知機',
    'Drone de surveillance Peekaboo': 'Peekaboo 監視ドローン',
    'Enregistreur audio Whisperlog': 'Whisperlog 音声記録装置',
    'Projecteur holographique TruViz': 'TruViz ホログラフィック・プロジェクター',
    'Boîtier de piratage QuickJack': 'QuickJack ハッキング・ドングル',
    'Antenne relais pliable GridLink': 'GridLink 折りたたみ中継アンテナ',
    'Lampe UV tactique BrightEdge': 'BrightEdge タクティカル UV ランプ',
    'Jumelles électroniques Hawkview': 'Hawkview 電子双眼鏡',
    'Lunettes de vision nocturne NiteOwl': 'NiteOwl ナイトビジョン・ゴーグル',
    'Tracker GPS magnétique StickPin': 'StickPin 磁着式 GPS トラッカー',
    'Clé de chiffrement quantique Vaultex': 'Vaultex 量子暗号キー',
    'Médikit portatif CureTech': 'CureTech 携帯型メディキット',
    'Seringue auto-inject NanoHeal': 'NanoHeal 自動注射シリンジ',
    'Stabilisateur de trauma QuickSave': 'QuickSave 外傷安定装置',
    'Analyseur sanguin RedScan': 'RedScan 血液分析装置',
    "Injecteur d'adrénaline PulsePen": 'PulsePen アドレナリン注射器',
    'Patch antidouleur BlissWrap': 'BlissWrap 鎮痛パッチ',
    'Défibrillateur portable ZapBack': 'ZapBack 携帯型除細動器',
    'Kit de chirurgie de terrain FieldCut': 'FieldCut 野戦外科キット',
    'Inhalateur anti-toxines ClearLung': 'ClearLung 解毒吸入器',
    'Brancard gonflable RescuePod': 'RescuePod 空気式ストレッチャー',
    'Kit de crochetage électronique BypassPro': 'BypassPro 電子ロックピック・キット',
    "Kit d'escalade magnétique GeckoGrip": 'GeckoGrip 磁着式クライミング・キット',
    'Corde rétractable SilkLine': 'SilkLine 伸縮ロープ',
    "Gants d'effraction ShadowTouch": 'ShadowTouch 侵入用グローブ',
    'Spray camouflage thermique ColdSkin': 'ColdSkin 熱迷彩スプレー',
    'Coupe-grillage plasma MeltEdge': 'MeltEdge プラズマ・ワイヤーカッター',
    'Chaussures silencieuses HushStep': 'HushStep サイレント・シューズ',
    'Brouilleur de caméras BlindSpot': 'BlindSpot カメラ・ジャマー',
    'Marqueur laser infrarouge GhostDot': 'GhostDot 赤外線レーザー・マーカー',
    'Masque à gaz compact BreathSafe': 'BreathSafe 小型ガスマスク',
    'Sac de survie RuggedPack': 'RuggedPack サバイバル・バッグ',
    "Purificateur d'eau AquaPure": 'AquaPure 浄水器',
    'Rations concentrées NutriBlock': 'NutriBlock 濃縮レーション',
    'Tente camouflée StealthTent': 'StealthTent 迷彩テント',
    'Briquet plasma FireStrike': 'FireStrike プラズマ・ライター',
    'Couverture de survie ThermoWrap': 'ThermoWrap サバイバル・ブランケット',
    'Kit de réparation universel FixAll': 'FixAll 万能修理キット',
    'Boussole AR NavPoint': 'NavPoint AR コンパス',
    'Compteur Geiger RadWatch': 'RadWatch ガイガーカウンター',
    'Multi-outil magnétique ToolFlex': 'ToolFlex 磁着式マルチツール',
    'Oreillette subvocale WhisperLink': 'WhisperLink サブボーカル・イヤピース',
    'Émetteur longue portée SkyReach': 'SkyReach 長距離送信機',
    'Traducteur vocal InstaTrans': 'InstaTrans 音声翻訳機',
    'Réseau mesh tactique SquadNet': 'SquadNet 戦術メッシュネットワーク',
    'Amplificateur de signal BoostWave': 'BoostWave 信号増幅器',
    'Transmetteur burst DataFlash': 'DataFlash バースト・データ送信機',
    'Micro-espion adhésif BugDrop': 'BugDrop 粘着式盗聴器',
    'Modulateur vocal VoxShift': 'VoxShift ボイス・モジュレーター',
    'Casque comm blindé IronComm': 'IronComm 装甲通信ヘッドセット',
    'Antenne satellite pliable OrbitLink': 'OrbitLink 折りたたみ衛星アンテナ',
    'Kit de déguisement FaceMaker': 'FaceMaker 変装キット',
    'Costume à fibres adaptatives ChamSuit': 'ChamSuit 適応繊維スーツ',
    'Lentilles à iris variable ShiftEye': 'ShiftEye 可変虹彩レンズ',
    'Carte de visite holographique BizGlow': 'BizGlow ホログラフィック名刺',
    'Parfum phéromonal AttraxOne': 'AttraxOne フェロモン香水',
    'Tatouage électronique FlexInk': 'FlexInk 電子タトゥー',
    'Badge de sécurité falsifié ClearPass': 'ClearPass 偽造セキュリティバッジ',
    'Mallette diplomatique ShieldCase': 'ShieldCase 外交用ブリーフケース',
    'Micro-imprimante de faux papiers DocForge': 'DocForge 偽造書類マイクロプリンター',
    "Lunettes d'enregistrement social SpySpex": 'SpySpex 社交用録画グラス',
    'Turbo-boost magnétique RushCore': 'RushCore 磁気ターボブースト',
    'Blindage véhicule léger ArmorPlate': 'ArmorPlate 軽車両装甲',
    'Système de leurres thermiques FlareBox': 'FlareBox 熱デコイ・システム',
    'Pneus auto-réparants SealTread': 'SealTread 自己修復タイヤ',
    'Fumigènes arrière SmokeTrail': 'SmokeTrail 後方発煙発射装置',
    'GPS anti-tracking GhostRoute': 'GhostRoute 追跡妨害 GPS',
    'Compartiment secret VoidStash': 'VoidStash 隠し収納',
    'Phares aveuglants FlashBeam': 'FlashBeam 眩惑ヘッドライト',
    'Lanceur de clous routiers SpikeDrop': 'SpikeDrop 路上スパイク発射装置',
    "Pilote automatique d'urgence AutoPilot": 'AutoPilot 非常用オートパイロット',
    'Holster rapide QuickDraw': 'QuickDraw スピード・ホルスター',
    'Lunette de visée SmartScope': 'SmartScope 照準サイト',
    'Chargeurs rapides SpeedMag': 'SpeedMag クイックローダー',
    'Silencieux universel MuteShot': 'MuteShot 汎用サプレッサー',
    'Bandolière tactique TacVest': 'TacVest タクティカル・バンドリア',
    'Lampe tactique BlindFire': 'BlindFire タクティカル・フラッシュライト',
    'Poignée avant stabilisatrice SteadyGrip': 'SteadyGrip 安定化フォアグリップ',
    'Grenades flash BangOut': 'BangOut フラッシュグレネード',
    'Grenades fumigènes HazeCloud': 'HazeCloud スモークグレネード',
    'Pointeur laser TrueAim': 'TrueAim レーザー・ポインター',
    'Drone barista KafBot': 'KafBot バリスタ・ドローン',
    'Skateboard magnétique HoverRide': 'HoverRide 磁気スケートボード',
    'Générateur de bruit blanc ZenField': 'ZenField ホワイトノイズ発生器',
    'Set de poker holographique LuckDeck': 'LuckDeck ホログラフィック・ポーカーセット',
    'Animal de compagnie robot PetDroid': 'PetDroid ロボットペット',
    'Synthétiseur musical PocketJam': 'PocketJam 音楽シンセサイザー',
    'Bouteille thermos autodéfense FlaskStrike': 'FlaskStrike 護身用サーモス',
    'Parapluie blindé UmbraShield': 'UmbraShield 装甲傘',
    'Réchaud de terrain portatif HeatMeal': 'HeatMeal 携帯型フィールドストーブ',
    'Montre multifonctions ChronoX': 'ChronoX 多機能腕時計',
    'Jeu de dés truqués LuckyBones': 'LuckyBones イカサマダイス',
    'Chargeur solaire pliant SunPack': 'SunPack 折りたたみソーラー充電器',
    'Peinture corporelle UV GlowArt': 'GlowArt UV ボディペイント',
    'Couteau suisse cybernétique CyberBlade': 'CyberBlade サイバネティック十徳ナイフ',
    'Baguette de feu Pyralith': 'Pyralith 炎のワンド',
    'Cristal de foudre Stormvein': 'Stormvein 雷のクリスタル',
    'Anneau de cendres Cindreth': 'Cindreth 灰のリング',
    'Dague rituelle Ignaris': 'Ignaris 儀式用ダガー',
    'Tatouage de flammes Pyroglyphe': 'Pyroglyph 炎のタトゥー',
    'Bâton de guerre Vorathil': 'Vorathil 戦の杖',
    'Orbe de tempête Fulgurath': 'Fulgurath 嵐のオーブ',
    "Grimoire de l'Annihilation Zervonis": 'Zervonis 滅びのグリモワール',
    'Pendentif clairvoyant Oeilune': 'Oeilune 千里眼のペンダント',
    'Cristal de divination Vistara': 'Vistara 占術クリスタル',
    'Masque du Troisième Oeil Mystera': 'Mystera 第三の眼の仮面',
    'Baguette sensorielle Aethersight': 'Aethersight 感覚のワンド',
    'Orbe omniscient Panoptès': 'Panoptes 全知のオーブ',
    'Amulette de guérison Vitasève': 'Vitaseve 治癒のアミュレット',
    'Anneau de jade Curaverde': 'Curaverde 翡翠のリング',
    'Fétiche de racines Sylvamend': 'Sylvamend 根のフェティッシュ',
    'Brûle-encens Sanaflore': 'Sanaflore 香炉',
    'Gemme de résurrection Auravita': 'Auravita 復活のジェム',
    'Masque des mirages Phantasma': 'Phantasma 幻影の仮面',
    "Prisme d'ombre Umbralex": 'Umbralex 影のプリズム',
    'Tatouage de brume Nébuline': 'Nebuline 霧のタトゥー',
    'Baguette de reflets Miralis': 'Miralis 反射のワンド',
    'Grimoire des Cent Visages Polychroma': 'Polychroma 百面のグリモワール',
    'Gantelet runique Gravisar': 'Gravisar ルーン・ガントレット',
    'Anneau de domination Vexalis': 'Vexalis 支配のリング',
    'Fétiche de corde Lianel': 'Lianel 紐のフェティッシュ',
    'Tambour de contrôle Dominara': 'Dominara 操作のドラム',
    'Bâton du Marionnettiste Nexarion': 'Nexarion 傀儡の杖',
    'Amulette de protection Aegisara': 'Aegisara 守護のアミュレット',
    'Cristal de dissipation Nullith': 'Nullith 解呪のクリスタル',
    'Anneau-bouclier Wardring': 'Wardring 守りのリング',
    'Masque de silence Mutharion': 'Mutharion 沈黙の仮面',
    "Grimoire de l'Annulation Zerovox": 'Zerovox 無効化のグリモワール',
    'Orbe de bannissement Spirex': 'Spirex 追放のオーブ',
    "Fétiche d'os Exorka": 'Exorka 骨のフェティッシュ',
    'Dague de séparation Sundralis': 'Sundralis 断絶のダガー',
    'Encensoir de purification Vanquor': 'Vanquor 浄化の香炉',
    "Bâton d'exorcisme Netherbane": 'Netherbane 退魔の杖',
    'Plume de tempête Zephyris': 'Zephyris 嵐の羽根',
    'Flûte des vents Aeronel': 'Aeronel 風の笛',
    'Pierre-ancre Terralis': 'Terralis 錨の石',
    'Statuette de glaise Lithomère': 'Lithomere 粘土の人形',
    "Brûle-encens d'ambre Flamaris": 'Flamaris 琥珀の香炉',
    'Rubis ardent Pyrovex': 'Pyrovex 燃えるルビー',
    'Coquillage chantant Marellis': 'Marellis 歌う貝殻',
    'Saphir des abysses Thalassion': 'Thalassion 深淵のサファイア',
    'Griffe de loup Fenrath': 'Fenrath 狼の爪',
    'Tambour des meutes Faunaris': 'Faunaris 群れのドラム',
    'Dague astrale Ectharion': 'Ectharion アストラル・ダガー',
    'Épée fantôme Spectralis': 'Spectralis 幽霊の剣',
    'Détecteur de mouvement TrembleSense': 'TrembleSense 動体検知器',
    'Projecteur de leurre holographique DecoyViz': 'DecoyViz ホログラフィック・デコイ投影機',
    'Microphone parabolique EarShot': 'EarShot パラボラ・マイク',
    'Analyseur de spectre RadioEye': 'RadioEye スペクトラム・アナライザー',
    'Répéteur de signal fantôme PhantomRelay': 'PhantomRelay ゴースト信号リピーター',
    'Caméra thermique ThermoSnap': 'ThermoSnap サーマルカメラ',
    'Clé USB de décryptage CryptoCrack': 'CryptoCrack 復号 USB キー',
    'Drone araignée SpiderBot': 'SpiderBot スパイダー・ドローン',
    'Émetteur de bruit parasite StaticBox': 'StaticBox ノイズ発生器',
    'Scanner biométrique FingerGhost': 'FingerGhost 生体認証スキャナー',
    'Antenne directionnelle PinPoint': 'PinPoint 指向性アンテナ',
    'Boîtier de clonage RFID TagMirror': 'TagMirror RFID 複製ボックス',
    'Gants chirurgicaux haptiques SurgiTouch': 'SurgiTouch 触覚手術用グローブ',
    'Bandage hémostatique ClotWrap': 'ClotWrap 止血包帯',
    'Scanner diagnostic UltraMed': 'UltraMed 診断スキャナー',
    'Capsules anti-radiation RadPurge': 'RadPurge 抗放射線カプセル',
    'Attelle gonflable InstaSplint': 'InstaSplint 空気式添え木',
    'Injecteur de stimulant SnapShot': 'SnapShot 興奮剤注射器',
    'Kit de transfusion portable HemoLink': 'HemoLink 携帯型輸血キット',
    'Spray cicatrisant DermaSeal': 'DermaSeal 治癒スプレー',
    'Moniteur de signes vitaux BioWatch': 'BioWatch バイタルサイン・モニター',
    'Pince hémostatique magnétique MagClamp': 'MagClamp 磁着式止血クランプ',
    'Grappin magnétique ascensionnel LiftHook': 'LiftHook 昇降用磁気グラップル',
    "Combinaison d'infiltration NightSkin": 'NightSkin 潜入スーツ',
    'Lunettes de détection laser TrapSight': 'TrapSight レーザー探知ゴーグル',
    'Pâte de thermite MeltPack': 'MeltPack テルミット・ペースト',
    'Détecteur de pression FloorSense': 'FloorSense 圧力探知器',
    "Ventouse d'escalade murale WallWalker": 'WallWalker 壁面吸着カップ',
    'Poudre de marquage UV TraceGlow': 'TraceGlow UV マーキング粉',
    'Mini perceuse silencieuse DrillGhost': 'DrillGhost 静音ミニドリル',
    'Film de camouflage optique MimicWrap': 'MimicWrap 光学迷彩フィルム',
    'Piège de distraction sonore NoiseSnare': 'NoiseSnare 音響かく乱トラップ',
    'Filtre respiratoire BreathGuard': 'BreathGuard 呼吸フィルター',
    'Balise de détresse SOS-Beacon': 'SOS-Beacon 救難信号装置',
    'Poncho isolant thermique HeatCloak': 'HeatCloak 断熱ポンチョ',
    'Détecteur de vie BioScan': 'BioScan 生命探知器',
    'Gel de décontamination PureSkin': 'PureSkin 除染ジェル',
    'Câble de rappel auto-enrouleur DropLine': 'DropLine 自動巻取ラペリング・ケーブル',
    'Piège à collet électronique TrapMaster': 'TrapMaster 電子スネアトラップ',
    "Pastilles de purification d'air OxyTab": 'OxyTab 空気浄化タブレット',
    'Hamac tactique SkyNest': 'SkyNest 戦術ハンモック',
    'Carte topographique AR TerrainMap': 'TerrainMap AR 地形図',
    'Brouilleur vocal ScrambleVox': 'ScrambleVox ボイス・スクランブラー',
    'Relais satellite covert CometLink': 'CometLink 秘匿衛星中継器',
    'Implant dentaire comm ToothTalk': 'ToothTalk 歯科通信インプラント',
    'Écran de confidentialité holographique PrivScreen': 'PrivScreen ホログラフィック・プライバシースクリーン',
    'Codec crypté de groupe TeamCrypt': 'TeamCrypt グループ暗号コーデック',
    'Drone messager SwiftWing': 'SwiftWing 伝令ドローン',
    'Balise infrarouge de ralliement IRBeacon': 'IRBeacon 赤外線集合ビーコン',
    'Projecteur de messages lumineux SkyWrite': 'SkyWrite 光メッセージ投影機',
    'Communicateur sous-marin AquaComm': 'AquaComm 水中通信機',
    'Décodeur de fréquences policières BlueScanner': 'BlueScanner 警察周波数デコーダー',
    'Modulateur de démarche GaitShift': 'GaitShift 歩容変調装置',
    'Crème de changement de teint DermaTone': 'DermaTone 肌色クリーム',
    'Perruque adaptative MorphHair': 'MorphHair 適応ウィッグ',
    'Micro-caméra corporelle BodyEye': 'BodyEye ボディカメラ',
    'Montre de luxe contrefaite FauxLux': 'FauxLux 偽造高級腕時計',
    'Kit de maquillage cicatriciel ScarFX': 'ScarFX 傷痕メイクキット',
    "Vaporisateur d'ADN brouillé GeneMask": 'GeneMask DNA 撹乱スプレー',
    'Costume corpo premium EliteFit': 'EliteFit 高級コーポスーツ',
    'Bague de signature numérique AuthRing': 'AuthRing 電子署名リング',
    'Prothèses auriculaires elfiques ElfEar': 'ElfEar エルフ耳プロテーゼ',
    'Gel de modification vocale VocalShift': 'VocalShift 声質変更ジェル',
    "Sacoche d'extraction de données CorpSleeve": 'CorpSleeve データ抽出サッチェル',
    'Système de changement de plaque SwapTag': 'SwapTag ナンバープレート交換装置',
    'Brouilleur radar StealthField': 'StealthField レーダー・ジャマー',
    'Siège éjectable CatapultSeat': 'CatapultSeat 射出座席',
    'Peinture caméléon ChromaCoat': 'ChromaCoat カメレオン塗装',
    'Système anti-poursuite OilSlick': 'OilSlick 追跡妨害システム',
    "Haut-parleur d'autorité CommandVoice": 'CommandVoice 威圧スピーカー',
    'Suspension tout-terrain RoughRide': 'RoughRide オフロード・サスペンション',
    'Système de navigation furtive ShadowNav': 'ShadowNav ステルス航法システム',
    'Kit de réparation rapide PatchJob': 'PatchJob 応急修理キット',
    'Filet de camouflage véhicule CamoNet': 'CamoNet 車両迷彩ネット',
    'Klaxon sonique ShockHorn': 'ShockHorn ソニック・ホーン',
    'Coffre blindé anti-scan VaultBox': 'VaultBox スキャン防護装甲トランク',
    'Bouclier balistique pliable FoldShield': 'FoldShield 折りたたみ防弾シールド',
    'Chargeur de munitions traçantes TracerMag': 'TracerMag 曳光弾マガジン',
    'Genouillères balistiques KneePlate': 'KneePlate 防弾ニーパッド',
    'Viseur nocturne NightShot': 'NightShot ナイトビジョン・スコープ',
    'Couteau de combat dissimulé HideBlade': 'HideBlade 隠匿戦闘ナイフ',
    'Gants de combat renforcés IronFist': 'IronFist 強化戦闘グローブ',
    'Ceinture de munitions AmmoFeed': 'AmmoFeed 弾帯',
    'Bipied stabilisateur GroundLock': 'GroundLock 安定化バイポッド',
    'Grenade EMP ShockPulse': 'ShockPulse EMP グレネード',
    'Étui dissimulé de cheville AnkleDraw': 'AnkleDraw 隠匿アンクルホルスター',
    'Protège-oreilles tactiques SonicShield': 'SonicShield タクティカル・イヤープロテクター',
    "Harnais de transport d'arme lourde HeavyRig": 'HeavyRig 重火器搬送ハーネス',
    'Coffre-fort portable NanoVault': 'NanoVault 携帯型金庫',
    'Cigarettes électroniques à filtre détox PurePuff': 'PurePuff 解毒フィルター電子タバコ',
    'Valise de contrebande SmuggleCase': 'SmuggleCase 密輸スーツケース',
    'Drone de livraison PackMule': 'PackMule 配送ドローン',
    'Lampe de poche tactique à plasma PlasmaBeam': 'PlasmaBeam タクティカル・プラズマライト',
    'Sac à dos anti-vol SecurePack': 'SecurePack 盗難防止バックパック',
    'Générateur portable MicroGen': 'MicroGen 携帯型発電機',
    'Bottes magnétiques à gravité MagBoots': 'MagBoots 磁気重力ブーツ',
    'Kit de nettoyage de scène CleanSweep': 'CleanSweep 現場清掃キット',
    'Lunettes à réalité augmentée TacAR': 'TacAR 拡張現実グラス',
    'Imperméable blindé StormGuard': 'StormGuard 装甲レインコート',
    'Briquet lance-flammes miniature PyroFlick': 'PyroFlick 小型火炎放射ライター',
    'Bracelet de lave Magmaris': 'Magmaris 溶岩のブレスレット',
    'Crâne de corbeau Corvaxis': 'Corvaxis 大鴉の頭骨',
    'Chaîne de foudre Voltanis': 'Voltanis 雷のチェーン',
    'Pierre de tonnerre Grondarak': 'Grondarak 雷鳴の石',
    "Collier d'éclats Shardveil": 'Shardveil 破片のネックレス',
    "Sceptre d'orage Tempestius": 'Tempestius 嵐のセプター',
    'Masque du Berserker Ragnarith': 'Ragnarith 狂戦士の仮面',
    'Gantelet de destruction Havocris': 'Havocris 破壊のガントレット',
    'Pendentif du néant Voidflare': 'Voidflare 虚無のペンダント',
    'Tome des cataclysmes Ruinaris': 'Ruinaris 破局の書',
    'Miroir de vérité Revelox': 'Revelox 真実の鏡',
    "Boucle d'oreille sensitif Auralis": 'Auralis 鋭敏のイヤリング',
    'Lanterne astrale Luménith': 'Lumenith アストラル・ランタン',
    'Lentille de perception Scryex': 'Scryex 知覚のレンズ',
    'Pendule de vérité Truthweaver': 'Truthweaver 真実のペンデュラム',
    'Bracelet de sève vivante Verdaris': 'Verdaris 生樹液のブレスレット',
    'Fiole de rosée lunaire Moonbalm': 'Moonbalm 月露の小瓶',
    'Tatouage de régénération Renewglyph': 'Renewglyph 再生のタトゥー',
    'Calice de renaissance Vitacrest': 'Vitacrest 再誕の聖杯',
    'Orbe de plénitude Harmonia': 'Harmonia 充溢のオーブ',
    "Éventail d'ombres Kagéris": 'Kageris 影の扇',
    'Broche de mirage Chimérion': 'Chimerion 幻影のブローチ',
    'Bague de fumée Hazeweaver': 'Hazeweaver 煙のリング',
    'Kaléidoscope enchanté Fractalis': 'Fractalis 魔法のカレイドスコープ',
    "Cape d'invisibilité Voidcloak": 'Voidcloak 不可視のクローク',
    'Pendentif télékinétique Liftaris': 'Liftaris 念動のペンダント',
    'Gant de marionnettiste Stringweave': 'Stringweave 傀儡のグローブ',
    'Clochette de commandement Bellaris': 'Bellaris 号令のベル',
    'Couronne de domination Imperex': 'Imperex 支配の冠',
    'Anneau gravitique Gravaxis': 'Gravaxis 重力のリング',
    'Talisman de réflexion Mirrorguard': 'Mirrorguard 反射のタリスマン',
    'Bracelet de silence Hushward': 'Hushward 沈黙のブレスレット',
    'Pierre de négation Voidstone': 'Voidstone 否定の石',
    'Bouclier runique Aegisforth': 'Aegisforth ルーン・シールド',
    "Sceptre d'annulation Nullcrown": 'Nullcrown 破棄のセプター',
    'Chaîne de bannissement Ghostchain': 'Ghostchain 追放の鎖',
    "Cloche d'exorcisme PureBell": 'PureBell 退魔の鈴',
    'Amulette de rupture Severis': 'Severis 断絶のアミュレット',
    'Fouet spectral Whipshade': 'Whipshade 幽体のウィップ',
    'Grimoire des sceaux Bindvault': 'Bindvault 封印のグリモワール',
    'Carillon de brise Windchime': 'Windchime 微風のカリヨン',
    'Écharpe de nuages Stratosweave': 'Stratosweave 雲のスカーフ',
    'Sifflet de cyclone Galehorn': 'Galehorn 旋風のホイッスル',
    'Collier de stalactites Cavérite': 'Caverite 石筍のネックレス',
    'Bracelet de lichen Mossgrip': 'Mossgrip 地衣のブレスレット',
    'Marteau tellurique Quartzfall': 'Quartzfall 地脈のハンマー',
    'Mèche éternelle Cinderwick': 'Cinderwick 永遠の灯芯',
    "Pendentif d'escarboucle Blazegem": 'Blazegem 柘榴石のペンダント',
    'Torche du phénix Ashflare': 'Ashflare 不死鳥のトーチ',
    'Perle de marée Tidalorb': 'Tidalorb 潮のパール',
    'Bracelet de corail Corallis': 'Corallis 珊瑚のブレスレット',
    'Trident miniature Depthcaller': 'Depthcaller 小型トライデント',
    'Collier de crocs Fangbound': 'Fangbound 牙のネックレス',
    'Fétiche de plumes Hawktalon': 'Hawktalon 羽根のフェティッシュ',
    'Masque totémique Beastlord': 'Beastlord トーテムの仮面',
    'Lame ectoplasmique Ghostedge': 'Ghostedge エクトプラズムの刃',
    'Gantelet spectral Wraithgrip': 'Wraithgrip 幽体のガントレット',
    'Lance dimensionnelle Riftspear': 'Riftspear 次元のランス',
  },

  // Spells, adept powers and traits carry no product name: the whole string
  // is the ability, so the whole string is translated. Where a spell's name
  // is an established Shadowrun term the katakana form is kept (マナ・ボルト,
  // ファイアボール, テレキネシス); everything descriptive becomes Japanese.
  spell: {
    'Boulon de mana': 'マナ・ボルト',
    'Boule de feu': 'ファイアボール',
    'Éclair': 'ライトニング・ボルト',
    'Flèche de givre': '氷の矢',
    'Vague de choc': '衝撃波',
    'Lance acide': '酸の槍',
    'Étouffement': '窒息',
    'Souffle du dragon': 'ドラゴン・ブレス',
    'Décharge de mana': 'マナ放出',
    'Rayon désintégrateur': '分解光線',
    'Tempête de grêle': '雹嵐',
    'Frappe spectrale': '幽体打撃',
    "Griffes d'ombre": '影の爪',
    'Nova de mana': 'マナ・ノヴァ',
    "Chaîne d'éclairs": '連鎖雷撃',
    'Poing de terre': '大地の拳',
    'Torrent de force': '力の奔流',
    'Pluie de cendres': '灰の雨',
    'Dard venimeux': '毒の投矢',
    'Rupture sonique': '音響破砕',
    'Détection de la vie': '生命探知',
    'Détection des ennemis': '敵影探知',
    'Vision astrale': 'アストラル視覚',
    'Sens du danger': '危険感知',
    'Détection de la magie': '魔力探知',
    'Traque astrale': 'アストラル追跡',
    'Cartographie mentale': '精神地図',
    "Analyse d'aura": 'オーラ読取',
    'Écoute à distance': '遠隔聴取',
    'Psychométrie': '精神感応',
    'Vision thermique': '熱視覚',
    'Détection des esprits': '精霊探知',
    'Sonde mentale': '精神探査',
    'Révélation des passages': '隠路看破',
    'Guérison': '治癒',
    'Régénération': '再生',
    'Augmentation de réflexes': '反射強化',
    'Résistance à la douleur': '鎮痛',
    'Stabilisation': '安定化',
    'Augmentation de force': '筋力強化',
    "Augmentation d'agilité": '敏捷力強化',
    "Vision de l'aigle": '鷹の目',
    'Second souffle': '第二の息吹',
    'Protection contre les toxines': '毒素防護',
    'Restauration cellulaire': '細胞修復',
    'Endurance du troll': 'トロールの耐久力',
    'Transfert vital': '生命力転移',
    'Invisibilité': '不可視化',
    'Double illusoire': '幻影の分身',
    'Masque': '仮面',
    'Terreur': '恐怖',
    'Hallucination de masse': '集団幻覚',
    'Éblouissement': '眩惑',
    'Voix fantôme': '幻の声',
    'Mur illusoire': '幻の壁',
    'Cauchemar éveillé': '白昼の悪夢',
    'Distorsion sensorielle': '感覚撹乱',
    "Brouillard d'ombre": '影の霧',
    'Faux mort': '擬死',
    'Déplacement illusoire': '幻影転位',
    'Folie passagère': '刹那の狂気',
    'Reflet trompeur': '偽りの反映',
    'Lévitation': '浮遊',
    'Armure magique': 'マナ装甲',
    'Contrôle des émotions': '情動操作',
    'Télékinésie': 'テレキネシス',
    'Verrou magique': '魔法錠',
    "Contrôle de l'eau": '水操作',
    'Pétrification': '石化',
    "Animation d'objet": '物体使役',
    'Façonnage de la terre': '地形成形',
    'Contrôle du feu': '火操作',
    'Contrôle mental': '精神操作',
    'Aura de commandement': '号令のオーラ',
    'Ralentissement': '鈍化',
    'Entrave végétale': '植物の罠',
    'Contrôle du vent': '風操作',
    'Glissade de verglas': '氷結路面',
    'Armure de pierre': '石の装甲',
    'Portail dimensionnel': '次元門',
    'Barrière magique': '魔法障壁',
    'Dissipation': '解呪',
    'Bouclier anti-sort': '呪文盾',
    'Ancrage de garde': '結界錨',
    'Réflexion de sort': '呪文反射',
    'Cercle de protection': '守護円',
    'Suppression de magie': '魔力抑制',
    'Piège astral': 'アストラル・トラップ',
    'Absorption de mana': 'マナ吸収',
    'Sceau de fermeture': '封印紋',
    'Lame de plasma': 'プラズマ・ブレード',
    'Pluie de météores': '流星群',
    'Flèche de tonnerre': '雷の矢',
    'Vortex de mana': 'マナ・ヴォルテックス',
    'Souffle glacial': '氷結の息',
    'Impact gravitationnel': '重力叩き付け',
    'Détonation arcanique': '魔力爆発',
    'Vrilles de foudre': '雷の触手',
    'Rayon nécrotique': '死霊光線',
    'Éruption magmatique': 'マグマ噴出',
    'Boulet de canon': '砲弾',
    'Fouet de mana': 'マナ・ウィップ',
    'Pique de givre': '氷の棘',
    'Onde de radiation': '放射線波',
    'Marteau de force': '力の鉄槌',
    'Flèche de feu': '火の矢',
    'Tempête électrique': '電撃嵐',
    'Éclat de void': '虚無の爆裂',
    'Salve de cristal': '結晶弾幕',
    'Étreinte du néant': '虚無の抱擁',
    'Radar astral': 'アストラル・レーダー',
    'Perception des émotions': '情動感知',
    'Œil du faucon': '鷹の眼',
    'Détection des métaux': '金属探知',
    'Lien empathique': '共感リンク',
    'Flair du pisteur': '追跡者の嗅覚',
    'Balayage matriciel': 'マトリックス走査',
    'Vision nocturne': '暗視',
    'Détection des pièges': '罠探知',
    'Télépathie de surface': '表層テレパシー',
    'Sonar magique': '魔法ソナー',
    "Localisation d'objet": '物体捜索',
    'Sens de la Matrice': 'マトリックス感知',
    'Détection des cyberware': 'サイバーウェア探知',
    'Vision panoramique': '全周視覚',
    'Analyse de barrière': '障壁解析',
    'Écho du passé': '過去の残響',
    'Sixième sens': '第六感',
    'Perception des flux': '流れの知覚',
    'Détection des mensonges': '虚言看破',
    'Bouclier vital': '生命の盾',
    'Purge toxique': '毒素排出',
    'Ossification rapide': '急速骨化',
    'Augmentation de constitution': '耐久力強化',
    'Sang de troll': 'トロールの血',
    'Résistance au feu': '火炎耐性',
    'Résistance au froid': '冷気耐性',
    'Cicatrisation accélérée': '急速瘢痕化',
    'Adrénaline magique': '魔法のアドレナリン',
    'Restauration sensorielle': '感覚回復',
    'Guérison de groupe': '集団治癒',
    "Peau d'écorce": '樹皮の肌',
    'Détoxification sanguine': '血液解毒',
    'Souffle de vie': '生命の息吹',
    'Endurance surnaturelle': '超常の耐久力',
    'Résistance électrique': '電撃耐性',
    'Augmentation de volonté': '意志力強化',
    'Peau de fer': '鉄の肌',
    'Adaptation environnementale': '環境適応',
    'Régénération neurale': '神経再生',
    'Dédoublement spectral': '幽体分裂',
    "Voile d'ombre": '影の帷',
    'Illusion de masse': '集団幻影',
    'Murmures insidieux': '蝕む囁き',
    'Paysage fantôme': '幻の風景',
    'Clones illusoires': '幻影の複製',
    'Sommeil profond': '深い眠り',
    'Image miroir': '鏡像',
    'Aura trompeuse': '偽りのオーラ',
    'Cécité': '盲目',
    'Surdité': '聴覚喪失',
    'Labyrinthe mental': '精神の迷宮',
    'Faux bruit': '偽りの音',
    'Apparition terrifiante': '恐怖の幻出',
    'Inversion sensorielle': '感覚反転',
    'Invisibilité de groupe': '集団不可視化',
    'Douleur fantôme': '幻痛',
    'Amnésie sélective': '選択的記憶喪失',
    'Odeur trompeuse': '偽りの匂い',
    'Cage de verre': '硝子の檻',
    'Chaînes de mana': 'マナの鎖',
    'Mur de force': '力の壁',
    'Contrôle des animaux': '動物操作',
    'Rouille accélérée': '急速腐食',
    'Bulle de protection': '守護の泡',
    'Magnétisme': '磁力',
    'Distorsion spatiale': '空間歪曲',
    'Contrôle de la gravité': '重力操作',
    'Marionnettiste': '傀儡師',
    'Sable mouvant': '流砂',
    'Lien de contrôle': '操作リンク',
    'Cristallisation': '結晶化',
    'Désassemblage': '分解',
    'Piège de mana': 'マナの罠',
    'Réparation magique': '魔法修復',
    'Prison de glace': '氷の牢',
    'Contrôle de la température': '温度操作',
    'Compression matérielle': '物質圧縮',
    'Cage de foudre': '雷の檻',
    'Onde de télékinésie': '念動波',
  },

  'adept-power': {
    'Poing perforant': '殺人の手',
    'Frappe du serpent': '蛇の一撃',
    'Frappe du tonnerre': '雷の一撃',
    'Paume vibrante': '震掌',
    'Griffes astrales': 'アストラルの爪',
    'Coup de pied circulaire': '旋風脚',
    'Lame de ki': '気の刃',
    'Frappe paralysante': '神経打撃',
    'Contre-attaque instinctive': '本能の反撃',
    'Puissance concentrée': '集中した膂力',
    'Technique du brise-pierre': '砕石の技',
    'Flèche guidée': '誘導の矢',
    'Rage du berserker': '狂戦士の激昂',
    "Frappe de l'aigle": '鷹の一撃',
    "Prise de l'ours": '熊の握力',
    'Cri de guerre': '戦の叫び',
    'Combo dévastateur': '壊滅の連撃',
    'Projection de ki': '気の投射',
    'Main de fer': '鉄拳',
    'Technique du cobra': '眼鏡蛇の技',
    'Danse des lames': '剣舞',
    'Frappe désarmante': '武装解除打',
    'Anticipation du combat': '戦闘予見',
    'Poing du dragon': '龍拳',
    'Riposte foudroyante': '雷の返し技',
    'Vitesse améliorée': '速度強化',
    'Course du vent': '風の疾走',
    'Saut du tigre': '虎の跳躍',
    'Marche murale': '壁歩き',
    'Chute contrôlée': '制御落下',
    'Nage du saumon': '鮭の泳ぎ',
    'Équilibre parfait': '完全な平衡',
    'Accélération réflexe': '反射加速',
    'Pas du fantôme': '幽鬼の歩法',
    'Roulade acrobatique': '曲芸的受身',
    'Adhérence du gecko': '壁虎の吸着',
    'Bond dimensionnel': '次元跳躍',
    'Grâce féline': '猫の優雅',
    'Souffle de marathon': '長距離の息',
    'Contorsion': '軟体化',
    'Sens du danger': '危険感知',
    'Vision améliorée': '視覚強化',
    'Ouïe amplifiée': '聴覚増幅',
    'Odorat du loup': '狼の嗅覚',
    'Toucher analytique': '解析の触覚',
    'Perception astrale': 'アストラル知覚',
    'Vision nocturne': '暗視',
    'Sens sismique': '震動感知',
    'Écho-localisation': '反響定位',
    "Lecture d'intention": '意図看破',
    'Goût analytique': '解析の味覚',
    'Vision thermographique': '熱感知視覚',
    'Sixième sens': '第六感',
    'Perception du flux': '流れの知覚',
    'Sens magnétique': '磁気感知',
    'Esquive surnaturelle': '超常の回避',
    'Corps de fer': '鉄の肉体',
    'Résistance à la douleur': '痛覚耐性',
    'Peau de pierre': '石の肌',
    'Bouclier de ki': '気の盾',
    'Résistance aux toxines': '毒素耐性',
    "Esprit d'acier": '鋼の精神',
    "Absorption d'impact": '衝撃吸収',
    'Sang de dragon': '龍の血',
    'Déflexion': '受け流し',
    'Volonté indomptable': '不屈の意志',
    'Armure de ki': '気の装甲',
    'Résistance aux éléments': '元素耐性',
    'Récupération accélérée': '回復促進',
    'Détournement de ki': '気の転換',
    'Pas léger': '軽歩',
    'Ombre vivante': '生きた影',
    'Aura nulle': '無のオーラ',
    'Silence absolu': '絶対の静寂',
    'Caméléon': 'カメレオン',
    'Présence effacée': '存在の消去',
    'Passage sans trace': '無痕の通行',
    "Masquage d'odeur": '匂いの遮蔽',
    'Furtivité urbaine': '都市隠密',
    "Dissimulation d'arme": '武器隠匿',
    'Voix enchanteresse': '魅惑の声',
    "Aura d'autorité": '威厳のオーラ',
    'Empathie profonde': '深い共感',
    'Charme surnaturel': '超常の魅力',
    'Regard intimidant': '威圧の眼光',
    'Mimétisme vocal': '声の擬態',
    'Persuasion subtile': '巧みな説得',
    'Calme imposé': '強制の平静',
    'Détection de mensonge': '虚言探知',
    'Présence mémorable': '印象的な存在感',
    'Méditation curative': '治癒の瞑想',
    'Transfert de ki': '気の転移',
    'Purge de toxines': '毒素排出',
    'Régénération accélérée': '再生促進',
    'Transe réparatrice': '回復の恍惚',
    'Souffle vital': '生命の呼吸',
    'Cicatrisation instantanée': '瞬間瘢痕化',
    'Immunité à la fatigue': '疲労無効',
    'Restauration nerveuse': '神経回復',
    'Harmonie corporelle': '身体の調和',
    'Frappe du phénix': '不死鳥の一撃',
    'Prise du python': '蟒蛇の締め',
    'Fouet de ki': '気の鞭',
    'Frappe sismique': '震動打撃',
    'Morsure du scorpion': '蠍の刺突',
    'Tempête de coups': '連打',
    'Coupe du vent': '風の刃',
    'Technique du mantis': '螳螂の技',
    'Charge du taureau': '猛牛の突進',
    'Frappe du vide': '虚無の一撃',
    "Pluie d'acier": '鋼の雨',
    'Balayage tourbillonnant': '回転払い',
    'Frappe du tigre blanc': '白虎の一撃',
    'Technique du miroir': '鏡の技',
    'Coup de grâce': '止めの一撃',
    'Paume céleste': '天掌',
    'Enchaînement du singe': '猿の連技',
    'Lance de ki': '気の槍',
    'Étreinte glaciale': '氷河の抱擁',
    'Marteau de guerre': '戦の鉄槌',
    'Pas de brume': '霧の歩法',
    "Course sur l'eau": '水上歩行',
    'Saut du cerf': '牡鹿の跳躍',
    'Vélocité du colibri': '蜂鳥の速度',
    'Glissade spectrale': '幽体滑走',
    'Ascension du singe': '猿の登攀',
    'Élan du guépard': '豹の瞬発',
    'Rétablissement aérien': '空中復帰',
    'Traverse des toits': '屋上走者',
    'Ancrage terrestre': '地の錨',
    'Radar spirituel': '精霊レーダー',
    'Vision des flux': '流れの視覚',
    'Perception du temps': '時間知覚',
    'Ouïe sélective': '選択的聴取',
    'Cartographie mentale': '精神地図',
    'Détection de magie': '魔力探知',
    'Vision microscopique': '顕微視覚',
    'Sens du cyberespace': 'サイバースペース感知',
    'Perception des émotions': '情動知覚',
    'Oreille absolue': '絶対音感',
    'Carapace astrale': 'アストラルの甲殻',
    'Résilience du chêne': '樫の強靱さ',
    'Barrière psychique': '精神障壁',
    'Redirection de force': '力の転向',
    'Peau de diamant': '金剛の肌',
    'Absorption de mana': 'マナ吸収',
    'Posture du roc': '磐石の構え',
    'Contre-sort instinctif': '本能の対抗呪文',
    'Résistance au drain': 'ドレイン耐性',
    'Sang coagulant': '凝固する血',
    'Effacement de traces numériques': '電子痕跡の消去',
    'Dédoublement illusoire': '幻影の分身',
    'Marche silencieuse': '無音歩行',
    "Voile d'ombre": '影の帷',
    'Invisibilité partielle': '部分不可視化',
    'Respiration suspendue': '呼吸停止',
    'Déplacement non-euclidien': '非ユークリッド移動',
    'Fondu dans la foule': '雑踏への埋没',
    'Empreinte nulle': '無痕の足跡',
    'Mimétisme environnemental': '環境擬態',
    'Commandement tactique': '戦術指揮',
    'Masque émotionnel': '情動の仮面',
    'Projection de confiance': '自信の投射',
    'Voix de la raison': '理性の声',
    'Terreur mystique': '神秘の恐怖',
    'Lien empathique': '共感リンク',
    'Suggestion subliminale': '潜在意識への示唆',
    'Aura de sérénité': '静謐のオーラ',
    'Négociateur né': '生来の交渉者',
    'Présence terrifiante': '恐怖の存在感',
    'Canalisation élémentaire': '元素の導引',
    'Toucher soigneur': '治癒の手',
    'Ancrage spirituel': '精霊の錨',
    'Flamme intérieure': '内なる炎',
    'Souffle du givre': '氷結の息',
    'Décharge électrique': '電撃放出',
    "Peau d'écorce": '樹皮の肌',
    'Communion animale': '動物との交感',
    'Lévitation mineure': '小浮遊',
    'Onde de choc': '衝撃波',
    "Muscles d'acier": '鋼の筋肉',
    'Os renforcés': '強化された骨',
    'Tendons élastiques': '弾性の腱',
    'Poumons de fer': '鉄の肺',
    'Synapses accélérées': '加速するシナプス',
    'Thermorégulation': '体温調節',
    'Métabolisme accéléré': '代謝促進',
    'Articulations renforcées': '強化された関節',
    'Vision du prédateur': '捕食者の視覚',
    'Réflexes surhumains': '超人的反射',
    'Concentration inébranlable': '揺るがぬ集中',
    'Méditation de combat': '戦闘瞑想',
    'Maîtrise du souffle': '呼吸の熟達',
    'Esprit compartimenté': '分割された精神',
    'Mémoire eidétique': '映像記憶',
    "Résistance à l'interrogatoire": '尋問耐性',
    'Volonté de fer': '鉄の意志',
    'Conscience éveillée': '覚醒した意識',
    'Suppression de la peur': '恐怖の抑制',
    'Transcendance': '超越',
  },

  'complex-form': {
    'Surcharge de données': 'データ過負荷',
    'Spike résonant': 'レゾナンス・スパイク',
    'Virus de fragmentation': '断片化ウイルス',
    'Boucle de crash': 'クラッシュ・ループ',
    'Décharge neurale': '神経放電',
    'Corruption de signal': '信号破損',
    'Impulsion disruptive': '妨害パルス',
    'Injection de code': 'コード注入',
    'Siphon de données': 'データ吸引',
    'Parasite résonant': 'レゾナンス寄生体',
    'Surcharge sensorielle': '感覚過負荷',
    'Bombe logique': 'ロジック・ボム',
    'Érosion de firewall': 'ファイアウォール侵食',
    'Choc de déconnexion': '切断ショック',
    "Cascade d'erreurs": 'エラー連鎖',
    'Ver de Résonance': 'レゾナンス・ワーム',
    'Blackout matriciel': 'マトリックス停電',
    'Piège de données': 'データ・トラップ',
    'Foudre numérique': '電子の雷',
    'Résonance défensive': '防御レゾナンス',
    'Bouclier de données': 'データ・シールド',
    'Pare-feu résonant': 'レゾナンス・ファイアウォール',
    'Contre-intrusion': '侵入対抗',
    'Cryptage de Résonance': 'レゾナンス暗号化',
    'Isolation de noeud': 'ノード隔離',
    'Miroir matriciel': 'マトリックス・ミラー',
    'Régénération de code': 'コード再生',
    'Quarantaine numérique': '電子隔離',
    'Absorption de signal': '信号吸収',
    'Bastion résonant': 'レゾナンス堡塁',
    'Filtre adaptatif': '適応フィルター',
    'Bouclier anti-biofeedback': '対バイオフィードバック・シールド',
    "Rétablissement d'urgence": '緊急復旧',
    "Détection d'anomalie": '異常検知',
    'Camouflage matriciel': 'マトリックス迷彩',
    'Brouillage résonant': 'レゾナンス妨害',
    'Fantôme numérique': '電子の幽霊',
    'Tunnel de données': 'データ・トンネル',
    "Falsification d'icône": 'アイコン偽装',
    'Évasion de trace': '追跡回避',
    'Masque de signal': '信号遮蔽',
    'Fausse piste': '偽の痕跡',
    'Interférence passive': '受動妨害',
    "Dissolution d'empreinte": '足跡の消滅',
    'Leurre de Résonance': 'レゾナンス・デコイ',
    'Passage fantôme': '幽霊の通過',
    'Brouillard de données': 'データの霧',
    'Silence numérique': '電子の静寂',
    'Mimétisme de noeud': 'ノード擬態',
    'Écho de données': 'データの残響',
    'Pistage matriciel': 'マトリックス追跡',
    'Compression de données': 'データ圧縮',
    'Déchiffrement résonant': 'レゾナンス復号',
    'Clonage de données': 'データ複製',
    'Altération de log': 'ログ改変',
    'Indexation rapide': '高速索引化',
    'Falsification de données': 'データ偽造',
    'Extraction chirurgicale': '精密抽出',
    'Reconstruction de fichier': 'ファイル復元',
    'Transfert sécurisé': '安全転送',
    'Analyse de trafic': 'トラフィック解析',
    'Archivage résonant': 'レゾナンス保管',
    'Corruption sélective': '選択的破損',
    'Miroir de base de données': 'データベース・ミラー',
    'Surcharge moteur': 'エンジン過充電',
    'Diagnostic résonant': 'レゾナンス診断',
    'Contrôle de drone': 'ドローン奪取',
    'Optimisation machine': '機械最適化',
    'Shutdown à distance': '遠隔停止',
    'Reprogrammation flash': '瞬間再プログラム',
    'Lien de commande': '指令リンク',
    'Sabotage de capteur': 'センサー破壊工作',
    "Réanimation d'appareil": '機器再起動',
    'Essaim de contrôle': '群体制御',
    'Verrouillage de véhicule': '車両ロック',
    'Reconfiguration matérielle': 'ハードウェア再構成',
    'Interface forcée': '強制接続',
    'Transfert de contrôle': '制御移譲',
    'Appel de sprite': 'スプライト召喚',
    'Dissolution de sprite': 'スプライト解放',
    'Écho de Résonance': 'レゾナンスの残響',
    'Harmonique profonde': '深層倍音',
    'Purification résonante': 'レゾナンス浄化',
    'Onde de submersion': '沈潜の波',
    'Flux de Résonance': 'レゾナンスの流れ',
    'Porte de Résonance': 'レゾナンスの門',
    'Baptême résonant': 'レゾナンスの洗礼',
    'Cri de la Résonance': 'レゾナンスの叫び',
    'Analyse de système': 'システム解析',
    'Accélération de processus': '処理加速',
    'Réparation matricielle': 'マトリックス修復',
    'Boost de signal': '信号増強',
    'Traduction universelle': '汎用翻訳',
    'Cartographie matricielle': 'マトリックス地図化',
    'Multitâche résonant': 'レゾナンス並行処理',
    'Synchronisation temporelle': '時間同期',
    'Pont de données': 'データ・ブリッジ',
    'Optimisation de bande passante': '帯域最適化',
    'Tornade de paquets': 'パケット・ストーム',
    'Décompileur sauvage': '荒ぶる逆コンパイラ',
    'Résonance corrosive': '腐食レゾナンス',
    'Harpon de données': 'データ・ハープーン',
    'Éclat de mémoire': 'メモリ破裂',
    'Sabotage de protocole': 'プロトコル破壊工作',
    'Tsunami binaire': '二進の津波',
    'Fracture de noeud': 'ノード破砕',
    'Injection de bruit': 'ノイズ注入',
    'Détonation logicielle': 'ソフトウェア爆破',
    'Hémorragie de données': 'データ流出',
    'Pulsation destructrice': '破壊パルス',
    'Surcharge de pile': 'スタック・オーバーフロー',
    'Vortex de Résonance': 'レゾナンスの渦',
    'Rayonnement parasite': '寄生放射',
    'Dislocation de code': 'コード転位',
    'Implosion matricielle': 'マトリックス内破',
    'Lance-flammes numérique': '電子火炎放射',
    'Séisme de protocole': 'プロトコル震動',
    'Éclipse de données': 'データの蝕',
    'Blindage quantique': '量子遮蔽',
    'Matrice de contre-mesures': '対抗手段マトリクス',
    'Carapace de données': 'データの甲殻',
    "Réflexion d'attaque": '攻撃反射',
    'Sanctuaire numérique': '電子の聖域',
    'Armure adaptative': '適応装甲',
    "Dissipation d'énergie": 'エネルギー散逸',
    'Barrière de Résonance': 'レゾナンス障壁',
    'Nettoyage viral': 'ウイルス除去',
    'Bouclier de fragmentation': '断片化シールド',
    'Protocole de survie': '生存プロトコル',
    'Immunité logicielle': 'ソフトウェア免疫',
    'Mur de glace': 'IC の壁',
    'Redistribution de charge': '負荷再配分',
    'Pare-feu vivant': '生きたファイアウォール',
    'Cocon de données': 'データの繭',
    'Déviation de signal': '信号偏向',
    "Tampon d'urgence": '緊急バッファ',
    'Riposte automatique': '自動反撃',
    'Coque anti-traçage': '対追跡シェル',
    "Voile d'ombre numérique": '電子の影の帷',
    "Usurpation d'identité": '身元奪取',
    'Pas silencieux numérique': '電子の無音歩行',
    'Écran de fumée virtuel': '仮想煙幕',
    'Infiltration de sous-réseau': 'サブネット潜入',
    'Clonage de session': 'セッション複製',
    'Effacement rétroactif': '遡及消去',
    'Déguisement de flux': '流量偽装',
    'Porte dérobée résonante': 'レゾナンス・バックドア',
    'Fantôme de réseau': 'ネットワークの幻',
    'Tunnel quantique': '量子トンネル',
    "Permutation d'adresse": 'アドレス置換',
    'Injection de leurres': 'デコイ注入',
    'Masquage de Résonance': 'レゾナンス遮蔽',
    'Déphasage matriciel': 'マトリックス位相転移',
    'Camouflage de trafic': 'トラフィック迷彩',
    'Spectre de données': 'データの亡霊',
    'Brèche fantôme': '幽霊の侵入',
    'Écho inversé': '反転した残響',
    'Substitution de noeud': 'ノード置換',
    'Sonar de Résonance': 'レゾナンス・ソナー',
    'Profilage de cible': '標的プロファイリング',
    'Radar de vulnérabilités': '脆弱性レーダー',
    'Interception de flux': 'ストリーム傍受',
    'Excavation de données': 'データ発掘',
    'Lecture de mémoire résiduelle': '残存メモリ読取',
    'Cartographie de réseau profond': '深層網の地図化',
    'Décodeur de chiffrement': '暗号解読器',
    'Prédiction de trafic': 'トラフィック予測',
    'Sonde résonante': 'レゾナンス探査',
    'Détection de backdoor': 'バックドア検知',
    'Extraction de métadonnées': 'メタデータ抽出',
    'Analyse spectrale': 'スペクトル解析',
    'Triangulation de signal': '信号三角測量',
    'Renifleur de paquets': 'パケット・スニファー',
    'Autopsie de programme': 'プログラム解剖',
    'Scan de conscience': '意識走査',
    'Archéologie de données': 'データ考古学',
    'Démasquage de sprite': 'スプライトの正体看破',
    'Vision thermique matricielle': 'マトリックス熱視覚',
    'Marionnettiste avancé': '上位傀儡師',
    'Réécriture de firmware': 'ファームウェア書換',
    'Greffon de contrôle': '制御接合',
    'Corruption de pilote': 'ドライバ破損',
    'Synchronisation de drones': 'ドローン同期',
    'Amplification de portée': '射程増幅',
    'Injection de commande': 'コマンド注入',
    'Détournement de véhicule': '車両奪取',
    'Parasitage de caméra': 'カメラ寄生',
    'Boucle de rétroaction': 'フィードバック・ループ',
    'Réseau de Résonance': 'レゾナンス網',
    'Surcharge de capteurs': 'センサー過負荷',
    'Implant de routine': 'ルーチン植込',
    'Clonage de signal': '信号複製',
    'Chaîne de commande': '指令連鎖',
    'Brouillage ciblé': '標的妨害',
    'Éveil de machine': '機械の覚醒',
    'Désactivation de sécurité': 'セキュリティ無効化',
    'Recyclage de code': 'コード再利用',
    'Pont de contrôle à distance': '遠隔制御ブリッジ',
  },

  trait: {
    'Sixième sens': '第六感',
    'Intimidant': '威圧的',
    'Résistant': '頑健',
    'Endurci': '鍛え上げた体',
    'Dur à cuire': 'ハードボイルド',
    'Ambidextre': '両手利き',
    "Tireur d'élite né": '生来の射手',
    'Réflexes de combat': '戦闘反射',
    'Bagarreur de rue': 'ストリート喧嘩屋',
    'Expert en lames': '刃物の達人',
    'Vétéran de guerre': '戦争の退役兵',
    'Esquive instinctive': '本能的回避',
    'As de la gâchette': '引き金好き',
    'Tacticien de terrain': '現場の戦術家',
    'Tueur silencieux': '静かな殺し屋',
    'Encaisseur': '壁役',
    'Spécialiste en explosifs': '爆破の専門家',
    'Sang-froid sous le feu': '銃火の下の冷静',
    'Lanceur précis': '正確な投擲',
    'Caméléon social': '社交のカメレオン',
    'Langues (polyglotte)': '言語（多言語話者）',
    'Contacts de la rue': 'ストリートのコネ',
    "Code d'honneur": '名誉の規範',
    'Menteur professionnel': '玄人の嘘つき',
    'Négociateur hors pair': '交渉の達人',
    'Imposteur': 'なりすまし',
    'Charisme naturel': '天性の魅力',
    'Voix de commandement': '号令の声',
    "Lecteur d'émotions": '情動の読み手',
    'Réputation de la rue': 'ストリートの名声',
    'Médiateur': '仲裁者',
    'Séducteur': '誘惑者',
    'Empathie profonde': '深い共感',
    'Orateur inspirant': '鼓舞する弁士',
    'Maître du double jeu': '二重スパイ',
    'Réseau corpo': '企業人脈',
    'Flair politique': '政治の機微',
    'Mémoire eidétique': '映像記憶',
    'Expert en sécurité matricielle': 'マトリックス防護の専門家',
    'Historien des Ombres': '影の歴史家',
    'Connaisseur en armes': '武器の目利き',
    'Génie mécanique': '機械の天才',
    'Pharmacologue amateur': '素人薬理学者',
    'Chercheur matriciel': 'マトリックス調査員',
    'Expert en sécurité physique': '物理防護の専門家',
    'Linguiste': '言語学者',
    'Cartographe urbain': '都市の地図屋',
    'Secouriste formé': '訓練された救急要員',
    'Hacker éthique': '倫理的ハッカー',
    'Culture corpo': '企業文化',
    'Érudit de la magie': '魔術の学者',
    'Cryptanalyste': '暗号解析者',
    'Grimpeur hors pair': '熟練の登攀者',
    'Ombre vivante': '生きた影',
    'Acrobate': '軽業師',
    'Nageur de fond': '持久泳者',
    'Contorsionniste': '軟体芸人',
    'Survivaliste urbain': '都市のサバイバリスト',
    'Pilote de moto': 'バイク乗り',
    'Conducteur de fuite': '逃走運転手',
    'Constitution de fer': '鉄の体質',
    'Équilibriste': '綱渡り',
    'Infatigable': '疲れ知らず',
    'Crocheteur expert': '熟練の錠開け',
    'Maître du parkour': 'パルクールの達人',
    'Résistance à la douleur': '痛覚鈍麻',
    'Vision perçante': '目が利く',
    'Doigts de fée': '器用な指',
    'Chanceux': '幸運',
    'Volonté de fer': '鉄の意志',
    'Esprit analytique': '分析的な頭脳',
    'Concentration absolue': '絶対的集中',
    'Intuition aiguë': '鋭い直感',
    'Résistance mentale': '精神的な強靱さ',
    'Pensée latérale': '水平思考',
    'Multitâche': '並行処理の達人',
    'Calculateur prodige': '神童の計算力',
    'Détermination inébranlable': '揺るがぬ決意',
    'Sanguin': '冷静沈着',
    'Observateur méticuleux': '綿密な観察者',
    'Planificateur obsessionnel': '執拗な計画者',
    'Résilience psychologique': '心理的回復力',
    'Photographie mentale': '心的写像',
    'Paranoïaque': '疑心暗鬼',
    'Impulsif': '衝動的',
    'Claustrophobe': '閉所恐怖症',
    'Insomniaque': '不眠症',
    'Phobique (hauteurs)': '高所恐怖症',
    'Accro aux BTL': 'BTL 中毒',
    'Endetté': '借金漬け',
    'Recherché': 'お尋ね者',
    'Colérique': '短気',
    'Maudit par la technologie': '機械に嫌われる',
    'Kleptomane': '窃盗癖',
    'Joueur compulsif': '博打狂い',
    'Ennemi juré': '宿敵',
    'Superstitieux': '迷信家',
    'Cauchemars récurrents': '繰り返す悪夢',
    'Frappe chirurgicale': '精密な一撃',
    'Instinct du prédateur': '捕食者の本能',
    'Blindage naturel': '天然の装甲',
    'Tir en mouvement': '移動射撃',
    'Cage thoracique renforcée': '強化された胸郭',
    'Volée de coups': '連打',
    'Œil du cyclone': '嵐の目',
    "Maître de l'embuscade": '待ち伏せの達人',
    'Peau de fer': '鉄の肌',
    'Tireur instinctif': '本能の射手',
    'Rage contrôlée': '制御された憤怒',
    'Expert en armes lourdes': '重火器の専門家',
    'Coup de grâce': '止めの一撃',
    "Parer l'impossible": '不可能を受け流す',
    'Artilleur né': '生来の銃手',
    'Résistance aux chocs': '衝撃耐性',
    'Chasseur de prime': '賞金稼ぎ',
    'Réflexes surhumains': '超人的反射',
    'Combattant de fosse': '闘技場の戦士',
    'Maître des armes improvisées': '間に合わせ武器の達人',
    'Manipulateur froid': '冷徹な操り手',
    'Présence magnétique': '磁力のような存在感',
    'Maître chanteur': '恐喝者',
    "Diplomate de l'ombre": '影の外交官',
    'Acteur consumé': '完璧な役者',
    'Aura de confiance': '信頼のオーラ',
    'Connaisseur du milieu': '裏社会の目利き',
    'Tacticien social': '社交の戦術家',
    "Esprit d'acier": '鋼の精神',
    'Interrogateur expert': '熟練の尋問者',
    'Visage de poker': 'ポーカーフェイス',
    'Éloquence naturelle': '天性の弁舌',
    'Instinct de meute': '群れの本能',
    'Confident des puissants': '権力者の懐刀',
    'Lecteur de lèvres': '読唇',
    'Marchandeur acharné': '執拗な値切り屋',
    'Réseau de rumeurs': '噂の網',
    'Intimidation silencieuse': '無言の威圧',
    'Flair pour les ennuis': '厄介事を嗅ぎ分ける',
    'Sang-froid diplomatique': '外交的な平静',
    'Encyclopédie vivante': '生きた百科事典',
    'Génie du code': 'コードの天才',
    'Instinct médical': '医療の直感',
    'Rat de bibliothèque': '本の虫',
    'Démineur intuitif': '直感的な爆破屋',
    'Connaissance des gangs': 'ギャングの知識',
    'Expert en toxicologie': '毒物学の専門家',
    'Virtuose de la Matrice': 'マトリックスの名手',
    'Architecte de systèmes': 'システム設計者',
    'Mécanicien de drones': 'ドローン整備士',
    'Géographe des Ombres': '影の地理学者',
    'Chercheur obsessionnel': '執着する研究者',
    'Mémoire des visages': '顔の記憶',
    'Expert en contrefaçon': '偽造の専門家',
    "Sens de l'orientation infaillible": '過たぬ方向感覚',
    'Pilote autodidacte': '独学の操縦士',
    'Ouïe surnaturelle': '超常の聴覚',
    'Stratège matriciel': 'マトリックスの戦略家',
    'Anthropologue urbain': '都市人類学者',
    'Analyste de données': 'データ分析者',
    'Pas de fantôme': '幽鬼の歩法',
    'Force brute': '力押し',
    'Souplesse féline': '猫の柔軟性',
    'Marathonien': '長距離走者',
    'Main ferme': '揺るがぬ手',
    'Apnéiste': '素潜り',
    'Guérison rapide': '治りが早い',
    'Grâce de danseur': '踊り手の優雅',
    'Résistance au froid': '冷気耐性',
    'Escaladeur urbain': '都市の登攀者',
    'Métabolisme accéléré': '代謝促進',
    'Pied sûr': '足取りの確かさ',
    'Réflexe de survie': '生存反射',
    'Sens aiguisés': '鋭敏な感覚',
    'Pilote tout-terrain': '悪路の操縦士',
    'Sommeil léger': '眠りが浅い',
    'Capacité pulmonaire': '肺活量',
    'Cicatrisation rapide': '迅速な瘢痕化',
    'Résistance à la chaleur': '熱耐性',
    'Agilité simienne': '類人猿の敏捷性',
    'Addiction au soykaf': 'ソイカフ中毒',
    'Loyauté indéfectible': '揺るがぬ忠誠',
    'Syndrome du héros': '英雄症候群',
    'Rancunier': '恨みを忘れない',
    'Cicatrices de guerre': '戦の傷跡',
    'Phobie de la magie': '魔術恐怖症',
    'Perfectionniste': '完璧主義者',
    'Solitaire': '孤独者',
    'Oreille musicale': '音楽の耳',
    'Double vie': '二重生活',
    'Hyperactif': '多動',
    'Sens du devoir': '義務感',
    'Cynique invétéré': '根深い皮肉屋',
    'Cœur tendre': '甘い心',
    'Métamorphe social': '社交の変身者',
    'Phobique des espaces ouverts': '広場恐怖症',
    'Soif de connaissance': '知識への渇望',
    'Résistance au stress': 'ストレス耐性',
    'Nerveux chronique': '慢性的な緊張',
  },

  // Contacts are "<occupation>: <street name>". The occupation is translated;
  // the street name is a handle, so it stays as it is.
  contact: {
    'Fixer : Mr. Johnson': 'フィクサー: Mr. Johnson',
    'Receleur : Tiny': '故買屋: Tiny',
    'Gang leader : Spike': 'ギャングの頭: Spike',
    'Contrebandier : Smokey': '密輸屋: Smokey',
    'Faussaire : Penman': '偽造屋: Penman',
    'Prêteur sur gages : Mama Casse': '質屋: Mama Casse',
    "Trafiquant d'armes : Iron Mike": '武器商人: Iron Mike',
    'Bookmaker : Lucky Seven': '賭け屋: Lucky Seven',
    'Assassin retraité : Silence': '引退した殺し屋: Silence',
    'Dealer de BTL : Dreamer': 'BTL 売人: Dreamer',
    'Passeur de frontières : Coyote': '国境の案内人: Coyote',
    'Recruteur du milieu : Broker': '裏社会の斡旋屋: Broker',
    'Voleur à la tire : Slick': 'スリ: Slick',
    'Chef de syndicat : Don Renzo': 'シンジケートのボス: Don Renzo',
    'Indicateur : Rat': 'たれ込み屋: Rat',
    'Fabricant de drogues : Alchemist': '薬物製造者: Alchemist',
    'Perceur de coffres : Vault': '金庫破り: Vault',
    'Chauffeur de fuite : Nitro': '逃走運転手: Nitro',
    'Collecteur de dettes : Knuckles': '取立屋: Knuckles',
    'Proxénète : Velvet': 'フィクサー: Velvet',
    'Street Doc : Doc Patch': 'ストリート・ドク: Doc Patch',
    'Barman : Vieux Lou': 'バーテンダー: Old Lou',
    'Mécanicien : Gears': '整備工: Gears',
    'Tatoueuse : Ink': '彫師: Ink',
    'Coursier : Flash': '運び屋: Flash',
    'Cuisinière de rue : Mama Wok': '屋台の料理人: Mama Wok',
    'Gamin des rues : Pixel': 'ストリートの子: Pixel',
    'Ferrailleur : Scrap': '廃品屋: Scrap',
    'Prostituée : Candy': '性風俗従事者: Candy',
    'Prédicateur de rue : Father Grim': '路上の説教師: Father Grim',
    'Pharmacien clandestin : Pillbox': '闇の薬剤師: Pillbox',
    'Chauffeur de taxi : Swerve': 'タクシー運転手: Swerve',
    'DJ de club : BassLine': 'クラブ DJ: BassLine',
    'Squatter vétéran : Roots': '古参のスクオッター: Roots',
    'Chirurgien esthétique clandestin : Scalpel': '闇の形成外科医: Scalpel',
    'Cadre corpo : Ms. Sterling': '企業幹部: Ms. Sterling',
    'Attaché de presse : Vincent Cole': '報道官: Vincent Cole',
    'Secrétaire exécutive : Helen Sharp': '役員秘書: Helen Sharp',
    'Avocat corpo : Maître Duval': '企業弁護士: Attorney Duval',
    'Chercheur R&D : Dr. Nakamura': '研究開発員: Dr. Nakamura',
    'Agent de sécurité corpo : Bouclier': '企業警備員: Shield',
    'Responsable logistique : Karen Park': '物流管理者: Karen Park',
    'Trader financier : Maximilian Frost': '金融トレーダー: Maximilian Frost',
    'Ingénieur système : Ada Reeves': 'システム技術者: Ada Reeves',
    'Directeur de site : Hank Morrison': '拠点長: Hank Morrison',
    'Comptable véreux : Numbers': '不正経理士: Numbers',
    'Recruteur corpo : James Whitfield': '企業の採用担当: James Whitfield',
    'Lobbyiste : Diana Cross': 'ロビイスト: Diana Cross',
    'Médecin corpo : Dr. Wells': '企業医: Dr. Wells',
    'Agent de renseignement corpo : Specter': '企業情報部員: Specter',
    'Journaliste : Red Médiaz': '記者: Red Médiaz',
    'Producteur de trideo : Max Starr': 'トリッド・プロデューサー: Max Starr',
    'Blogueuse shadow : ByteGirl': '影のブロガー: ByteGirl',
    'Cameraman freelance : Lens': 'フリーのカメラマン: Lens',
    'Critique gastronomique : Fourchette': '料理評論家: Fourchette',
    'Musicien célèbre : Neon Vox': '有名音楽家: Neon Vox',
    'Présentateur de news : Tom Brecker': 'ニュースキャスター: Tom Brecker',
    'Artiste de rue : Graffik': 'ストリート・アーティスト: Graffik',
    'Agent de talents : Gloria Vance': '芸能エージェント: Gloria Vance',
    'Pirate des ondes : Fréquence': '海賊放送局: Frequency',
    'Flic corrompu : Inspecteur Marks': '汚職警官: Inspector Marks',
    'Greffier du tribunal : Bernard Clay': '裁判所書記官: Bernard Clay',
    'Agent des douanes : Mule': '税関職員: Mule',
    'Pompier : Red Chief': '消防士: Red Chief',
    'Inspecteur sanitaire : Dr. Finch': '衛生監督官: Dr. Finch',
    'Agent du fisc : Taxman': '税務官: Taxman',
    'Juge : Honorable Blackwood': '裁判官: Honorable Blackwood',
    'Politicien local : Conseiller Oribe': '地元政治家: Councilman Oribe',
    'Agent de probation : Warden Cole': '保護観察官: Warden Cole',
    'Diplomate : Ambassadeur Tran': '外交官: Ambassador Tran',
    'Talismonger : Madame Oya': 'タリスモンガー: Madame Oya',
    'Chaman urbain : Grey Feather': '都市のシャーマン: Grey Feather',
    'Herboriste magique : Willow': '魔法の薬草商: Willow',
    "Professeur d'université occulte : Dr. Arcanus": 'オカルト教授: Dr. Arcanus',
    'Initié libre : Wanderer': '自由なイニシエート: Wanderer',
    'Guérisseur traditionnel : Bonesaw': '伝統医: Bonesaw',
    'Chasseur de paracritters : Fang': 'パラクリッター狩人: Fang',
    'Enchanteur : Runesmith': 'エンチャンター: Runesmith',
    'Exorciste : Father Ash': '悪魔祓い師: Father Ash',
    "Lecteur d'auras : Oracle": 'オーラ読み: Oracle',
    'Hacker : ZeroCool': 'ハッカー: ZeroCool',
    'Admin réseau : SysOp': 'ネットワーク管理者: SysOp',
    'Technicien en cybernétique : Wrench': 'サイバーテック技師: Wrench',
    'Fabricant de commlinks : Circuit': 'コムリンク職人: Circuit',
    'Data broker : InfoVault': 'データ・ブローカー: InfoVault',
    'Techno-anarchiste : FreeNode': 'テクノ・アナキスト: FreeNode',
    'Réparateur de drones : Propeller': 'ドローン修理技師: Propeller',
    'Expert en surveillance : BigEye': '監視の専門家: BigEye',
    'Pirate de données : BlackICE': 'データ海賊: BlackICE',
    'Ingénieur électronique : Solder': '電子機器技師: Solder',
    'Mercenaire retraité : Sergeant Rock': '引退した傭兵: Sergeant Rock',
    'Garde du corps : Stone': 'ボディガード: Stone',
    'Instructeur de tir : Bullseye': '射撃教官: Bullseye',
    'Officier de milice : Capitaine Forge': '民兵の将校: Captain Forge',
    'Agent des forces spéciales : Ghost': '特殊部隊員: Ghost',
    'Armurier militaire : Hammer': '軍の武器係: Hammer',
    'Analyste du renseignement : Cipher': '情報分析官: Cipher',
    "Pilote d'hélicoptère : Rotorhead": 'ヘリ操縦士: Rotorhead',
    'Médecin militaire : Doc Trauma': '戦闘衛生兵: Doc Trauma',
    'Expert en déminage : Defuse': '爆発物処理の専門家: Defuse',
    'Faussaire de luxe : Quill': '高級品の偽造屋: Quill',
    'Pirate urbain : Corsair': '都市の海賊: Corsair',
    'Empoisonneuse : Belladona': '毒殺屋: Belladona',
    'Cambrioleur : Ombre': '空き巣: Shadow',
    'Recéleur high-tech : Nexus': 'ハイテク故買屋: Nexus',
    'Passeur de données : Courier': 'データの運び屋: Courier',
    'Trafiquant de cyberware : Chrome': 'サイバーウェア商人: Chrome',
    'Espion freelance : Mirage': 'フリーのスパイ: Mirage',
    'Racketteur : Bones': 'たかり屋: Bones',
    'Organisateur de combats : Pitboss': '格闘興行主: Pitboss',
    "Blanchisseur d'argent : Rinse": '資金洗浄屋: Rinse',
    'Kidnappeur pro : Snatch': 'プロの誘拐屋: Snatch',
    'Hacker criminel : Glitch': '犯罪ハッカー: Glitch',
    'Voleur de véhicules : Jackrabbit': '車両泥棒: Jackrabbit',
    'Chef de cartel : El Tigre': 'カルテルのボス: El Tigre',
    'Informatrice de luxe : Diamond': '高級情報屋: Diamond',
    'Artificier : Boom': '爆弾製造者: Boom',
    'Nettoyeur : Bleach': '清掃屋: Bleach',
    'Infiltrateur corpo : Viper': '企業潜入者: Viper',
    'Changeur de SIN : Mask': 'SIN 改変屋: Mask',
    'Graffeur mystique : Sigil': '神秘の落書き師: Sigil',
    'Gardien de parking : Sentry': '駐車場の警備員: Sentry',
    'Vendeuse ambulante : Noodle': '露天商: Noodle',
    'Boxeur retraité : Jawbone': '引退したボクサー: Jawbone',
    'Récupérateur : Magpie': '拾い屋: Magpie',
    'Coiffeur de quartier : Razor': '近所の理髪師: Razor',
    'Livreur de colis : Zip': '荷物の走り屋: Zip',
    'Vétérinaire de rue : Doc Paw': '街の獣医: Doc Paw',
    'Videur de club : Boulder': 'クラブのバウンサー: Boulder',
    "Concierge d'immeuble : Janitor": '建物の管理人: Janitor',
    'Dealer de stim-patches : Buzz': 'スティムパッチ売人: Buzz',
    'Guide des égouts : Tunnel Rat': '下水道の案内人: Tunnel Rat',
    'Réparateur de commlinks : Patch': 'コムリンク修理屋: Patch',
    'Mère de gang : Mama Bear': 'ギャングの母: Mama Bear',
    'Colporteur : Hawker': '行商人: Hawker',
    'Squatter tech : Sparky': '技術系スクオッター: Sparky',
    'Prostituée matrice : PixelDoll': 'マトリックスの接待役: PixelDoll',
    "Recycleur d'armes : Meltdown": '武器の再生屋: Meltdown',
    'Gardienne de refuge : Sister Hope': '保護施設の管理人: Sister Hope',
    'Pilote de rickshaw : Dash': '人力車の走り手: Dash',
    'Assistante IA corpo : ARIA': '企業 AI 補佐: ARIA',
    'Directeur marketing : Evan Bright': 'マーケティング部長: Evan Bright',
    'Chef de projet R&D : Dr. Patel': '研究開発の主任: Dr. Patel',
    'Auditeur interne : Bilan': '内部監査人: Ledger',
    'DRH corpo : Mme Laurent': '企業人事部長: Ms. Laurent',
    'Testeur de sécurité corpo : Pentest': '企業のペンテスター: Pentest',
    'Pilote corpo : Skyline': '企業の操縦士: Skyline',
    'Gestionnaire de données : Dataclerk': 'データ管理者: Dataclerk',
    'Cadre désabusé : Victor Hale': '幻滅した幹部: Victor Hale',
    'Directeur de prison privée : Warden Knox': '民営刑務所長: Warden Knox',
    'Chirurgien corpo : Dr. Strand': '企業外科医: Dr. Strand',
    'Archiviste corpo : Ms. Index': '企業の記録管理者: Ms. Index',
    'Chef de la sécurité : Commander Steele': '警備主任: Commander Steele',
    'Attaché diplomatique corpo : Consul Raines': '企業の外交担当官: Consul Raines',
    'Technicien de maintenance : Wrench Jr.': '保守技師: Wrench Jr.',
    'Stagiaire ambitieux : Bright Eyes': '野心的なインターン: Bright Eyes',
    'Responsable transport corpo : Logistics': '企業の輸送管理者: Logistics',
    'Chimiste corpo : Dr. Flask': '企業の化学者: Dr. Flask',
    'Juriste en propriété intellectuelle : Patent': '知財弁護士: Patent',
    'Responsable IT corpo : Root': '企業の情報システム部長: Root',
    'Libraire occulte : Grimoire': 'オカルト書店主: Grimoire',
    'Alchimiste de rue : Crucible': '街の錬金術師: Crucible',
    'Gardien de lieu sacré : Sentinel': '聖地の守り手: Sentinel',
    "Journaliste d'investigation : DeepDig": '調査報道記者: DeepDig',
    'Influenceuse matrice : GlitchQueen': 'マトリックスの影響力者: GlitchQueen',
    'Documentariste : Reel': '記録映画作家: Reel',
    'Officier de police interne : Lieutenant Graves': '内部監察官: Lieutenant Graves',
    'Inspecteur du travail : Compliance': '労働監督官: Compliance',
    'Greffier municipal : Tampon': '市役所の書記: Stamp',
    'Sniper retraité : Longshot': '引退した狙撃手: Longshot',
    'Technicien radar : Ping': 'レーダー技師: Ping',
    'Rigger freelance : Autopilot': 'フリーのリガー: Autopilot',
    "Programmeur d'IA : NeuralNet": 'AI プログラマー: NeuralNet',
    'Expert en cryptomonnaie : Blockchain': '暗号通貨の専門家: Blockchain',
    'Spécialiste en guerre électronique : Jammer': '電子戦の専門家: Jammer',
    'Mage corporatiste : Dr. Arclight': '企業の魔術師: Dr. Arclight',
    'Enquêteur astral : Wraith': 'アストラル調査員: Wraith',
    'Photographe de guerre : Shutter': '戦場写真家: Shutter',
    'Procureur corrompu : DA Voss': '汚職検察官: DA Voss',
    'Bibliothécaire universitaire : Prof. Dusty': '大学図書館員: Prof. Dusty',
    'Éleveur de paracritters : Beastmaster': 'パラクリッター飼育者: Beastmaster',
    'Courtier en informations : Whisper': '情報屋: Whisper',
    'Architecte urbain : Blueprint': '都市建築家: Blueprint',
    'Prêtresse vaudou : Mama Legba': 'ヴードゥーの女司祭: Mama Legba',
    'Bookmaker en ligne : OddsMan': 'ネットの賭け屋: OddsMan',
    'Cascadeur : Stuntman': 'スタントマン: Stuntman',
    'Géologue : Bedrock': '地質学者: Bedrock',
    'Antiquaire : Relique': '古物商: Relic',
    'Chauffeur de limousine : Smooth': 'リムジン運転手: Smooth',
    'Analyste météo : Storm': '気象分析官: Storm',
    'Agent immobilier underground : Squat': '闇の不動産屋: Squat',
    'Ingénieur en bioware : Dr. Gene': 'バイオウェア技師: Dr. Gene',
    'Psychologue de la rue : Doc Mind': '街の心理士: Doc Mind',
    "Expert en systèmes d'alarme : Tripwire": '警報装置の専門家: Tripwire',
    'Conteur ork : Griot': 'オークの語り手: Griot',
    'Entraîneur de combat : Sensei': '戦闘教官: Sensei',
    'Banquier suisse : Vault': 'スイスの銀行家: Vault',
    'Chaman des gangs : Totem': 'ギャングのシャーマン: Totem',
    'Pilote de cargo : Freighter': '貨物機の操縦士: Freighter',
    'Garde forestier éveillé : Ranger': '覚醒したパークレンジャー: Ranger',
  },

  awakened: {
    'Éveillé — Perception et Sorcellerie': '覚醒者 — 知覚と呪術',
    'Éveillé — Perception, Sorcellerie et Conjuration': '覚醒者 — 知覚、呪術、召喚',
    'Éveillé — Projection astrale et Conjuration': '覚醒者 — アストラル投射と召喚',
    'Éveillé — Perception astrale et Adepte': '覚醒者 — アストラル知覚とアデプト',
  },
  emerged: {
    'Émergé — Persona vivante': 'エマージド — リビング・ペルソナ',
  },

  // Firearms are product names with no category word (Kurogane AR-77,
  // Neon Arms Stiletto .22), so there is nothing to translate and they are
  // deliberately absent: the English fallback is already the right answer.
  // 85 of the 193 weapons are in that position.
  weapon: {
    'Couteau de combat Valkyr KS-3': 'Valkyr KS-3 戦闘ナイフ',
    'Dague Neon Arms Fang': 'Neon Arms Fang ダガー',
    'Couteau de survie Meridian Claw': 'Meridian Claw サバイバルナイフ',
    'Couteau papillon OmniDyne Flicker': 'OmniDyne Flicker バタフライナイフ',
    'Stiletto Apex Venom': 'Apex Venom スティレット',
    'Lame rétractable Kurotech Razor': 'Kurotech Razor 伸縮式ブレード',
    'Machette Prismex Bushmaster': 'Prismex Bushmaster マチェット',
    'Couteau de lancer NovaPulse Dart': 'NovaPulse Dart 投げナイフ',
    'Tanto Kurogane Ghost': 'Kurogane Ghost 短刀',
    'Kriss Titan Arms Serpent': 'Titan Arms Serpent クリス',
    'Katana Kurogane Type-4': 'Kurogane Type-4 刀',
    'Épée large Titan Arms Claymore': 'Titan Arms Claymore ブロードソード',
    'Sabre Meridian Hussar': 'Meridian Hussar サーベル',
    'Rapière NovaPulse Estoc': 'NovaPulse Estoc レイピア',
    'Nodachi Kaze Tempest': 'Kaze Tempest 野太刀',
    'Cimeterre Apex Crescent': 'Apex Crescent シミター',
    'Épée vibrante Prismex Resonance': 'Prismex Resonance バイブロブレード',
    'Machette longue Valkyr Jungle King': 'Valkyr Jungle King ロングマチェット',
    'Batte renforcée Ironside': 'Ironside 強化バット',
    'Massue Titan Arms Ogre': 'Titan Arms Ogre メイス',
    'Marteau NovaPulse Sledge': 'NovaPulse Sledge スレッジハンマー',
    'Nunchaku Kaze Whirlwind': 'Kaze Whirlwind ヌンチャク',
    'Matraque télescopique Apex Enforcer': 'Apex Enforcer 伸縮式バトン',
    'Tonfas Meridian Guardian': 'Meridian Guardian トンファー',
    'Bâton bo Kurotech Sensei': 'Kurotech Sensei 棒',
    'Morgenstern Valkyr Brute': 'Valkyr Brute モーニングスター',
    'Matraque shock Zapper': 'Zapper ショックバトン',
    'Taser Neon Arms Volt': 'Neon Arms Volt テーザー',
    'Gants shock OmniDyne Thunder': 'OmniDyne Thunder ショックグローブ',
    'Fouet électrique Prismex Arc': 'Prismex Arc 電撃ウィップ',
    'Lance shock Kaze Storm': 'Kaze Storm ショックランス',
    'Lame monofilament Whisper': 'Whisper モノフィラメント・ウィップ',
    'Chaîne monofilament Kurotech Reaper': 'Kurotech Reaper モノフィラメント・チェーン',
    'Gantelet à griffes Apex Predator': 'Apex Predator クロー・ガントレット',
    'Éventail de combat Kaze Mantis': 'Kaze Mantis 鉄扇',
    'Kusarigama NovaPulse Shadow': 'NovaPulse Shadow 鎖鎌',
    'Arts martiaux : Karaté Kurotech': 'Kurotech 空手修練',
    'Arts martiaux : Muay Thaï Kaze': 'Kaze ムエタイ修練',
    'Arts martiaux : Krav Maga Valkyr': 'Valkyr クラヴ・マガ修練',
    "Poings d'acier Titan Arms": 'Titan Arms 鉄拳',
    'Arts martiaux : Jiu-Jitsu NovaPulse': 'NovaPulse 柔術修練',
    'Pied-de-biche Meridian Leverage': 'Meridian Leverage バール',
    'Chaîne lourde Titan Arms Anchor': 'Titan Arms Anchor 重量チェーン',
    'Tuyau en acier Apex Sewer King': 'Apex Sewer King 鉄パイプ',
    'Clé à molette Prismex Wrecker': 'Prismex Wrecker パイプレンチ',
    'Bouteille cassée Neon Arms Last Call': 'Neon Arms Last Call 割れた瓶',
    'Lames de poignet Kurotech Mantis': 'Kurotech Mantis リストブレード',
    'Griffes cyber Apex Lynx': 'Apex Lynx サイバークロー',
    'Éperon cybernétique OmniDyne Spike': 'OmniDyne Spike サイバースパー',
    'Main-lame Valkyr Edge': 'Valkyr Edge ハンドブレード',
    'Couteau tactique Meridian Talon': 'Meridian Talon タクティカルナイフ',
    'Kukri NovaPulse Gorkhali': 'NovaPulse Gorkhali ククリ',
    'Couteau Bowie Titan Arms Frontier': 'Titan Arms Frontier ボウイナイフ',
    'Couteau céramique Kaze Silent': 'Kaze Silent セラミックナイフ',
    'Karambit Apex Scorpion': 'Apex Scorpion カランビット',
    'Dirk OmniDyne Highland': 'OmniDyne Highland ダーク',
    'Couteau pliant Neon Arms Switchback': 'Neon Arms Switchback 折りたたみナイフ',
    'Couteau de plongée Prismex Depth': 'Prismex Depth ダイビングナイフ',
    'Poignard trench Valkyr Doughboy': 'Valkyr Doughboy トレンチナイフ',
    'Lame dissimulée Kurotech Shade': 'Kurotech Shade 隠匿ブレード',
    'Épée bâtarde Titan Arms Conquest': 'Titan Arms Conquest バスタードソード',
    'Falchion Apex Cleaver': 'Apex Cleaver ファルシオン',
    'Wakizashi Kaze Moonlight': 'Kaze Moonlight 脇差',
    'Gladius NovaPulse Centurion': 'NovaPulse Centurion グラディウス',
    'Épée laser Prismex Photon': 'Prismex Photon レーザーソード',
    'Flamberge OmniDyne Inferno': 'OmniDyne Inferno フランベルジュ',
    'Dao Kurotech Dragon': 'Kurotech Dragon 青龍刀',
    'Claymore vibro Valkyr Earthquake': 'Valkyr Earthquake バイブロ・クレイモア',
    'Kanabo Kaze Oni': 'Kaze Oni 金棒',
    "Fléau d'armes Titan Arms Crusher": 'Titan Arms Crusher 戦闘フレイル',
    'Matraque tactique NovaPulse Pacifier': 'NovaPulse Pacifier タクティカルバトン',
    "Masse d'armes Meridian Paladin": 'Meridian Paladin 戦闘メイス',
    'Bâton escrima Apex Dual Strike': 'Apex Dual Strike エスクリマ・スティック',
    'Marteau de guerre Prismex Goliath': 'Prismex Goliath ウォーハンマー',
    'Bokken OmniDyne Senshi': 'OmniDyne Senshi 木刀',
    'Batte cloutée Neon Arms Basher': 'Neon Arms Basher 釘バット',
    'Taser longue portée Apex Bolt': 'Apex Bolt 長距離テーザー',
    'Bâton choc Valkyr Thunderstrike': 'Valkyr Thunderstrike ショックスタッフ',
    'Poing shock Kurotech Jolt': 'Kurotech Jolt ショックフィスト',
    'Filet électrifié NovaPulse NetShock': 'NovaPulse NetShock 電撃ネット',
    'Lasso shock Meridian Lariat': 'Meridian Lariat ショックラッソ',
    'Chaîne-faucille Titan Arms Harvester': 'Titan Arms Harvester チェーンシックル',
    'Urumi Kaze Serpent': 'Kaze Serpent ウルミ',
    'Tekko-kagi NovaPulse Shadow Hand': 'NovaPulse Shadow Hand 手甲鉤',
    'Sai Prismex Trident': 'Prismex Trident 釵',
    'Fouet à lame Valkyr Hydra': 'Valkyr Hydra ブレードウィップ',
    'Arts martiaux : Wing Chun Apex': 'Apex 詠春拳修練',
    'Arts martiaux : Capoeira Meridian': 'Meridian カポエイラ修練',
    'Arts martiaux : Systema OmniDyne': 'OmniDyne システマ修練',
    'Arts martiaux : Savate NovaPulse': 'NovaPulse サバット修練',
    'Arts martiaux : Pencak Silat Kaze': 'Kaze プンチャック・シラット修練',
    'Extincteur Apex Firefight': 'Apex Firefight 消火器',
    'Barre à mine Kurotech Breaker': 'Kurotech Breaker 掘削バー',
    "Panneau d'arrêt Neon Arms Halt": 'Neon Arms Halt 止まれ標識',
    "Câble d'acier Prismex Garrote": 'Prismex Garrote 鋼製ケーブル',
    'Clé en croix OmniDyne Roadkill': 'OmniDyne Roadkill クロスレンチ',
    'Lame de doigt Kurotech Stiletto': 'Kurotech Stiletto フィンガーブレード',
    'Lame de tibia NovaPulse Shin Edge': 'NovaPulse Shin Edge 脛ブレード',
    'Crocs cyber Apex Fang': 'Apex Fang サイバーファング',
    'Queue cyber Prismex Tail Spike': 'Prismex Tail Spike サイバーテイル',
    'Couteaux de lancer Kaze': 'Kaze 投げナイフ',
    'Shurikens Kaze Eclipse': 'Kaze Eclipse 手裏剣',
    'Grenades frag Apex': 'Apex フラググレネード',
    'Grenades fumigènes Meridian Haze': 'Meridian Haze ガスグレネード',
    'Haches de lancer Titan Arms Tomahawk': 'Titan Arms Tomahawk 投斧',
    'Bolas Meridian Tangle': 'Meridian Tangle ボーラ',
    'Grenades flash Apex Sunburst': 'Apex Sunburst フラッシュグレネード',
    'Grenades EMP NovaPulse Blackout': 'NovaPulse Blackout EMPグレネード',
  },

  cyberdeck: {
    'Cyberdeck Ghostline 3700': 'Ghostline 3700 サイバーデッキ',
    'Cyberdeck PixelWave Starter': 'PixelWave Starter サイバーデッキ',
    'Cyberdeck DataForge Mk.I': 'DataForge Mk.I サイバーデッキ',
    'Cyberdeck NovaPulse Runner': 'NovaPulse Runner サイバーデッキ',
    'Cyberdeck GridRunner Eco': 'GridRunner Eco サイバーデッキ',
    'Cyberdeck OmniDyne Pulse': 'OmniDyne Pulse サイバーデッキ',
    'Cyberdeck ShadowByte Mini': 'ShadowByte Mini サイバーデッキ',
    'Cyberdeck TechHive Basic': 'TechHive Basic サイバーデッキ',
    'Cyberdeck Prism Nexus': 'Prism Nexus サイバーデッキ',
    'Cyberdeck Ghostline 9000 Elite': 'Ghostline 9000 Elite サイバーデッキ',
    'Cyberdeck BlackVeil Phantom': 'BlackVeil Phantom サイバーデッキ',
    'Cyberdeck Kurotech Ronin X': 'Kurotech Ronin X サイバーデッキ',
    'Cyberdeck DataForge Mk.III Pro': 'DataForge Mk.III Pro サイバーデッキ',
    'Cyberdeck Meridian Warframe': 'Meridian Warframe サイバーデッキ',
    'Cyberdeck NovaPulse Apex': 'NovaPulse Apex サイバーデッキ',
    'Cyberdeck VortexNet Razor': 'VortexNet Razor サイバーデッキ',
    'Cyberdeck SpectraCorp Sentinel': 'SpectraCorp Sentinel サイバーデッキ',
    'Cyberdeck ZeroDay Exploit': 'ZeroDay Exploit サイバーデッキ',
    'Cyberdeck OmniDyne Titan': 'OmniDyne Titan サイバーデッキ',
    'Cyberdeck ShadowByte Wraith': 'ShadowByte Wraith サイバーデッキ',
    'Cyberdeck StreetSpark Lite': 'StreetSpark Lite サイバーデッキ',
    'Cyberdeck BinaryBudget V2': 'BinaryBudget V2 サイバーデッキ',
    'Cyberdeck NeonFlicker': 'NeonFlicker サイバーデッキ',
    'Cyberdeck RustBucket Mk.II': 'RustBucket Mk.II サイバーデッキ',
    'Cyberdeck WaveRider Compact': 'WaveRider Compact サイバーデッキ',
    'Cyberdeck CipherNode Entry': 'CipherNode Entry サイバーデッキ',
    'Cyberdeck SubNet Crawler': 'SubNet Crawler サイバーデッキ',
    'Cyberdeck HoloJack Slim': 'HoloJack Slim サイバーデッキ',
    'Cyberdeck ProbeLight Scanner': 'ProbeLight Scanner サイバーデッキ',
    'Cyberdeck IronClad Pocket': 'IronClad Pocket サイバーデッキ',
    'Cyberdeck QuantumEdge Sigma': 'QuantumEdge Sigma サイバーデッキ',
    'Cyberdeck NightFall Stealth': 'NightFall Stealth サイバーデッキ',
    'Cyberdeck HyperVault Fortress': 'HyperVault Fortress サイバーデッキ',
    'Cyberdeck StrikeForce Omega': 'StrikeForce Omega サイバーデッキ',
    'Cyberdeck CrystalMind Nexus': 'CrystalMind Nexus サイバーデッキ',
    'Cyberdeck TempestWare Havoc': 'TempestWare Havoc サイバーデッキ',
    'Cyberdeck NebulaCore Prime': 'NebulaCore Prime サイバーデッキ',
    'Cyberdeck VoidRunner Eclipse': 'VoidRunner Eclipse サイバーデッキ',
    'Cyberdeck ArcticByte Glacier': 'ArcticByte Glacier サイバーデッキ',
    'Cyberdeck PhantomLink Ultra': 'PhantomLink Ultra サイバーデッキ',
  },
};

/** The Japanese name for a template, or undefined to fall back to English. */
export function featNameJa(featType: string, name: string): string | undefined {
  return FEAT_NAMES_JA[featType]?.[name];
}
