/**
 * Japanese names for the NPC generator's gear templates.
 *
 * npc-generator-data.ts carries French and English names on every template
 * (`name` / `nameEn`), and the generator writes one of them into the created
 * actor's items. Those templates have no id or slug: their identity is the
 * French `name` string. Rather than add a third field to the 835 KB upstream
 * table — which would collide on every merge from upstream — the Japanese
 * names live here, keyed by the French name, and a template with no entry
 * falls back to English exactly as before.
 *
 * The key is nested under featType because the same French name exists as a
 * spell, an adept power and a trait, and upstream gives some of those
 * different English names (Résistance à la douleur is Pain Relief, Pain
 * Resistance and Pain Tolerance). A flat map would silently merge them.
 *
 * Nothing here comes from a rulebook: the products are the upstream author's
 * own inventions. Only the category word is translated; the invented product
 * name stays in Latin script, as SRA2.FEATS.WEAPON.TYPES.* already does for
 * the real-world weapon names.
 *
 * A key that no longer matches a template would silently stop working, so
 * npc-generator-data-ja.test.ts fails on one.
 */

export const FEAT_NAMES_JA: Record<string, Record<string, string>> = {
  armor: {
    'Veste synthécuir renforcée': '強化シンセレザー・ジャケット',
    'Hoodie blindé UrbanWall': 'UrbanWall 装甲フーディ',
    'T-shirt renforcé IronThread': 'IronThread 強化Tシャツ',
    'Blouson de moto SteetHide': 'StreetHide バイカージャケット',
    'Chemise blindée CorpoGuard': 'CorpoGuard 装甲ドレスシャツ',
    'Gilet pare-balles Apex Shield': 'Apex Shield 防弾ベスト',
    'Veste tactique ShadowVest': 'ShadowVest タクティカルジャケット',
    'Pardessus blindé TrenchLine': 'TrenchLine 装甲オーバーコート',
    'Combinaison de course RunShield': 'RunShield レーシングスーツ',
    'Gilet de sécurité WatchGuard': 'WatchGuard セキュリティベスト',
    'Manteau blindé NightShield': 'NightShield 装甲コート',
    'Armure urbaine StreetFort': 'StreetFort アーバンアーマー',
    "Combinaison d'assaut StormSuit": 'StormSuit アサルトスーツ',
    'Cape blindée IronCape': 'IronCape 装甲クローク',
    'Armure corporelle tactique TacForce': 'TacForce タクティカル・ボディアーマー',
    'Armure de combat Vanguard': 'Vanguard コンバットアーマー',
    'Exosquelette léger FrameGuard': 'FrameGuard 軽量エクソスケルトン',
    'Armure anti-émeute RiotMax': 'RiotMax 暴動鎮圧アーマー',
    'Exo-armure lourde Titan': 'Titan 重エクソアーマー',
    'Armure de siège Bulwark': 'Bulwark シージアーマー',
    'Gilet urbain NeoWeave': 'NeoWeave アーバンベスト',
    'Poncho blindé DustRunner': 'DustRunner 装甲ポンチョ',
    'Plastron discret SlimPlate': 'SlimPlate 隠匿型チェストガード',
    'Veste cargo ToughLine': 'ToughLine カーゴジャケット',
    'Bandana blindé StreetWrap': 'StreetWrap 装甲バンダナ',
    'Duster blindé RoadWarden': 'RoadWarden 装甲ダスターコート',
    'Blouson de vol ArmorWing': 'ArmorWing フライトジャケット',
    'Combinaison ouvrière ForgeSkin': 'ForgeSkin ワーカーカバーオール',
    'Kimono renforcé SilkSteel': 'SilkSteel 強化着物',
    'Parka arctique IceShell': 'IceShell アークティックパーカ',
    'Armure modulaire HexPlate': 'HexPlate モジュラーアーマー',
    'Harnais de combat WarRig': 'WarRig コンバットハーネス',
    'Robe de combat mystico-blindée ArcaneVeil': 'ArcaneVeil 魔術戦闘ローブ',
    "Plastron d'assaut CrashCore": 'CrashCore アサルト・チェストプレート',
    'Armure intégrale BunkerSuit': 'BunkerSuit フルボディアーマー',
    'Carapace de sécurité SentinelShell': 'SentinelShell セキュリティ・カラペイス',
    'Armure de tranchée IronBastion': 'IronBastion トレンチアーマー',
    'Combinaison blindée OgreMail': 'OgreMail 装甲スーツ',
    'Armure de puissance Juggernaut': 'Juggernaut パワーアーマー',
    'Exo-blindage Colossus': 'Colossus エクソプレーティング',
  },

  // Firearms are product names with no category word (Kurogane AR-77,
  // Neon Arms Stiletto .22), so there is nothing to translate and they are
  // deliberately absent: the English fallback is already the right answer.
  // 85 of the 193 weapons are in that position.
  weapon: {
    'Couteau de combat Valkyr KS-3': 'Valkyr KS-3 戦闘ナイフ',
    'Dague Neon Arms Fang': 'Neon Arms Fang ダガー',
    'Couteau de survie Meridian Claw': 'Meridian Claw サバイバルナイフ',
    'Couteau papillon OmniDyne Flicker': 'OmniDyne Flicker バタフライナイフ',
    'Stiletto Apex Venom': 'Apex Venom スティレット',
    'Lame rétractable Kurotech Razor': 'Kurotech Razor 伸縮式ブレード',
    'Machette Prismex Bushmaster': 'Prismex Bushmaster マチェット',
    'Couteau de lancer NovaPulse Dart': 'NovaPulse Dart 投げナイフ',
    'Tanto Kurogane Ghost': 'Kurogane Ghost 短刀',
    'Kriss Titan Arms Serpent': 'Titan Arms Serpent クリス',
    'Katana Kurogane Type-4': 'Kurogane Type-4 刀',
    'Épée large Titan Arms Claymore': 'Titan Arms Claymore ブロードソード',
    'Sabre Meridian Hussar': 'Meridian Hussar サーベル',
    'Rapière NovaPulse Estoc': 'NovaPulse Estoc レイピア',
    'Nodachi Kaze Tempest': 'Kaze Tempest 野太刀',
    'Cimeterre Apex Crescent': 'Apex Crescent シミター',
    'Épée vibrante Prismex Resonance': 'Prismex Resonance バイブロブレード',
    'Machette longue Valkyr Jungle King': 'Valkyr Jungle King ロングマチェット',
    'Batte renforcée Ironside': 'Ironside 強化バット',
    'Massue Titan Arms Ogre': 'Titan Arms Ogre メイス',
    'Marteau NovaPulse Sledge': 'NovaPulse Sledge スレッジハンマー',
    'Nunchaku Kaze Whirlwind': 'Kaze Whirlwind ヌンチャク',
    'Matraque télescopique Apex Enforcer': 'Apex Enforcer 伸縮式バトン',
    'Tonfas Meridian Guardian': 'Meridian Guardian トンファー',
    'Bâton bo Kurotech Sensei': 'Kurotech Sensei 棒',
    'Morgenstern Valkyr Brute': 'Valkyr Brute モーニングスター',
    'Matraque shock Zapper': 'Zapper ショックバトン',
    'Taser Neon Arms Volt': 'Neon Arms Volt テーザー',
    'Gants shock OmniDyne Thunder': 'OmniDyne Thunder ショックグローブ',
    'Fouet électrique Prismex Arc': 'Prismex Arc 電撃ウィップ',
    'Lance shock Kaze Storm': 'Kaze Storm ショックランス',
    'Lame monofilament Whisper': 'Whisper モノフィラメント・ウィップ',
    'Chaîne monofilament Kurotech Reaper': 'Kurotech Reaper モノフィラメント・チェーン',
    'Gantelet à griffes Apex Predator': 'Apex Predator クロー・ガントレット',
    'Éventail de combat Kaze Mantis': 'Kaze Mantis 鉄扇',
    'Kusarigama NovaPulse Shadow': 'NovaPulse Shadow 鎖鎌',
    'Arts martiaux : Karaté Kurotech': 'Kurotech 空手修練',
    'Arts martiaux : Muay Thaï Kaze': 'Kaze ムエタイ修練',
    'Arts martiaux : Krav Maga Valkyr': 'Valkyr クラヴ・マガ修練',
    "Poings d'acier Titan Arms": 'Titan Arms 鉄拳',
    'Arts martiaux : Jiu-Jitsu NovaPulse': 'NovaPulse 柔術修練',
    'Pied-de-biche Meridian Leverage': 'Meridian Leverage バール',
    'Chaîne lourde Titan Arms Anchor': 'Titan Arms Anchor 重量チェーン',
    'Tuyau en acier Apex Sewer King': 'Apex Sewer King 鉄パイプ',
    'Clé à molette Prismex Wrecker': 'Prismex Wrecker パイプレンチ',
    'Bouteille cassée Neon Arms Last Call': 'Neon Arms Last Call 割れた瓶',
    'Lames de poignet Kurotech Mantis': 'Kurotech Mantis リストブレード',
    'Griffes cyber Apex Lynx': 'Apex Lynx サイバークロー',
    'Éperon cybernétique OmniDyne Spike': 'OmniDyne Spike サイバースパー',
    'Main-lame Valkyr Edge': 'Valkyr Edge ハンドブレード',
    'Couteau tactique Meridian Talon': 'Meridian Talon タクティカルナイフ',
    'Kukri NovaPulse Gorkhali': 'NovaPulse Gorkhali ククリ',
    'Couteau Bowie Titan Arms Frontier': 'Titan Arms Frontier ボウイナイフ',
    'Couteau céramique Kaze Silent': 'Kaze Silent セラミックナイフ',
    'Karambit Apex Scorpion': 'Apex Scorpion カランビット',
    'Dirk OmniDyne Highland': 'OmniDyne Highland ダーク',
    'Couteau pliant Neon Arms Switchback': 'Neon Arms Switchback 折りたたみナイフ',
    'Couteau de plongée Prismex Depth': 'Prismex Depth ダイビングナイフ',
    'Poignard trench Valkyr Doughboy': 'Valkyr Doughboy トレンチナイフ',
    'Lame dissimulée Kurotech Shade': 'Kurotech Shade 隠匿ブレード',
    'Épée bâtarde Titan Arms Conquest': 'Titan Arms Conquest バスタードソード',
    'Falchion Apex Cleaver': 'Apex Cleaver ファルシオン',
    'Wakizashi Kaze Moonlight': 'Kaze Moonlight 脇差',
    'Gladius NovaPulse Centurion': 'NovaPulse Centurion グラディウス',
    'Épée laser Prismex Photon': 'Prismex Photon レーザーソード',
    'Flamberge OmniDyne Inferno': 'OmniDyne Inferno フランベルジュ',
    'Dao Kurotech Dragon': 'Kurotech Dragon 青龍刀',
    'Claymore vibro Valkyr Earthquake': 'Valkyr Earthquake バイブロ・クレイモア',
    'Kanabo Kaze Oni': 'Kaze Oni 金棒',
    "Fléau d'armes Titan Arms Crusher": 'Titan Arms Crusher 戦闘フレイル',
    'Matraque tactique NovaPulse Pacifier': 'NovaPulse Pacifier タクティカルバトン',
    "Masse d'armes Meridian Paladin": 'Meridian Paladin 戦闘メイス',
    'Bâton escrima Apex Dual Strike': 'Apex Dual Strike エスクリマ・スティック',
    'Marteau de guerre Prismex Goliath': 'Prismex Goliath ウォーハンマー',
    'Bokken OmniDyne Senshi': 'OmniDyne Senshi 木刀',
    'Batte cloutée Neon Arms Basher': 'Neon Arms Basher 釘バット',
    'Taser longue portée Apex Bolt': 'Apex Bolt 長距離テーザー',
    'Bâton choc Valkyr Thunderstrike': 'Valkyr Thunderstrike ショックスタッフ',
    'Poing shock Kurotech Jolt': 'Kurotech Jolt ショックフィスト',
    'Filet électrifié NovaPulse NetShock': 'NovaPulse NetShock 電撃ネット',
    'Lasso shock Meridian Lariat': 'Meridian Lariat ショックラッソ',
    'Chaîne-faucille Titan Arms Harvester': 'Titan Arms Harvester チェーンシックル',
    'Urumi Kaze Serpent': 'Kaze Serpent ウルミ',
    'Tekko-kagi NovaPulse Shadow Hand': 'NovaPulse Shadow Hand 手甲鉤',
    'Sai Prismex Trident': 'Prismex Trident 釵',
    'Fouet à lame Valkyr Hydra': 'Valkyr Hydra ブレードウィップ',
    'Arts martiaux : Wing Chun Apex': 'Apex 詠春拳修練',
    'Arts martiaux : Capoeira Meridian': 'Meridian カポエイラ修練',
    'Arts martiaux : Systema OmniDyne': 'OmniDyne システマ修練',
    'Arts martiaux : Savate NovaPulse': 'NovaPulse サバット修練',
    'Arts martiaux : Pencak Silat Kaze': 'Kaze プンチャック・シラット修練',
    'Extincteur Apex Firefight': 'Apex Firefight 消火器',
    'Barre à mine Kurotech Breaker': 'Kurotech Breaker 掘削バー',
    "Panneau d'arrêt Neon Arms Halt": 'Neon Arms Halt 止まれ標識',
    "Câble d'acier Prismex Garrote": 'Prismex Garrote 鋼製ケーブル',
    'Clé en croix OmniDyne Roadkill': 'OmniDyne Roadkill クロスレンチ',
    'Lame de doigt Kurotech Stiletto': 'Kurotech Stiletto フィンガーブレード',
    'Lame de tibia NovaPulse Shin Edge': 'NovaPulse Shin Edge 脛ブレード',
    'Crocs cyber Apex Fang': 'Apex Fang サイバーファング',
    'Queue cyber Prismex Tail Spike': 'Prismex Tail Spike サイバーテイル',
    'Couteaux de lancer Kaze': 'Kaze 投げナイフ',
    'Shurikens Kaze Eclipse': 'Kaze Eclipse 手裏剣',
    'Grenades frag Apex': 'Apex フラググレネード',
    'Grenades fumigènes Meridian Haze': 'Meridian Haze ガスグレネード',
    'Haches de lancer Titan Arms Tomahawk': 'Titan Arms Tomahawk 投斧',
    'Bolas Meridian Tangle': 'Meridian Tangle ボーラ',
    'Grenades flash Apex Sunburst': 'Apex Sunburst フラッシュグレネード',
    'Grenades EMP NovaPulse Blackout': 'NovaPulse Blackout EMPグレネード',
  },

  cyberdeck: {
    'Cyberdeck Ghostline 3700': 'Ghostline 3700 サイバーデッキ',
    'Cyberdeck PixelWave Starter': 'PixelWave Starter サイバーデッキ',
    'Cyberdeck DataForge Mk.I': 'DataForge Mk.I サイバーデッキ',
    'Cyberdeck NovaPulse Runner': 'NovaPulse Runner サイバーデッキ',
    'Cyberdeck GridRunner Eco': 'GridRunner Eco サイバーデッキ',
    'Cyberdeck OmniDyne Pulse': 'OmniDyne Pulse サイバーデッキ',
    'Cyberdeck ShadowByte Mini': 'ShadowByte Mini サイバーデッキ',
    'Cyberdeck TechHive Basic': 'TechHive Basic サイバーデッキ',
    'Cyberdeck Prism Nexus': 'Prism Nexus サイバーデッキ',
    'Cyberdeck Ghostline 9000 Elite': 'Ghostline 9000 Elite サイバーデッキ',
    'Cyberdeck BlackVeil Phantom': 'BlackVeil Phantom サイバーデッキ',
    'Cyberdeck Kurotech Ronin X': 'Kurotech Ronin X サイバーデッキ',
    'Cyberdeck DataForge Mk.III Pro': 'DataForge Mk.III Pro サイバーデッキ',
    'Cyberdeck Meridian Warframe': 'Meridian Warframe サイバーデッキ',
    'Cyberdeck NovaPulse Apex': 'NovaPulse Apex サイバーデッキ',
    'Cyberdeck VortexNet Razor': 'VortexNet Razor サイバーデッキ',
    'Cyberdeck SpectraCorp Sentinel': 'SpectraCorp Sentinel サイバーデッキ',
    'Cyberdeck ZeroDay Exploit': 'ZeroDay Exploit サイバーデッキ',
    'Cyberdeck OmniDyne Titan': 'OmniDyne Titan サイバーデッキ',
    'Cyberdeck ShadowByte Wraith': 'ShadowByte Wraith サイバーデッキ',
    'Cyberdeck StreetSpark Lite': 'StreetSpark Lite サイバーデッキ',
    'Cyberdeck BinaryBudget V2': 'BinaryBudget V2 サイバーデッキ',
    'Cyberdeck NeonFlicker': 'NeonFlicker サイバーデッキ',
    'Cyberdeck RustBucket Mk.II': 'RustBucket Mk.II サイバーデッキ',
    'Cyberdeck WaveRider Compact': 'WaveRider Compact サイバーデッキ',
    'Cyberdeck CipherNode Entry': 'CipherNode Entry サイバーデッキ',
    'Cyberdeck SubNet Crawler': 'SubNet Crawler サイバーデッキ',
    'Cyberdeck HoloJack Slim': 'HoloJack Slim サイバーデッキ',
    'Cyberdeck ProbeLight Scanner': 'ProbeLight Scanner サイバーデッキ',
    'Cyberdeck IronClad Pocket': 'IronClad Pocket サイバーデッキ',
    'Cyberdeck QuantumEdge Sigma': 'QuantumEdge Sigma サイバーデッキ',
    'Cyberdeck NightFall Stealth': 'NightFall Stealth サイバーデッキ',
    'Cyberdeck HyperVault Fortress': 'HyperVault Fortress サイバーデッキ',
    'Cyberdeck StrikeForce Omega': 'StrikeForce Omega サイバーデッキ',
    'Cyberdeck CrystalMind Nexus': 'CrystalMind Nexus サイバーデッキ',
    'Cyberdeck TempestWare Havoc': 'TempestWare Havoc サイバーデッキ',
    'Cyberdeck NebulaCore Prime': 'NebulaCore Prime サイバーデッキ',
    'Cyberdeck VoidRunner Eclipse': 'VoidRunner Eclipse サイバーデッキ',
    'Cyberdeck ArcticByte Glacier': 'ArcticByte Glacier サイバーデッキ',
    'Cyberdeck PhantomLink Ultra': 'PhantomLink Ultra サイバーデッキ',
  },
};

/** The Japanese name for a template, or undefined to fall back to English. */
export function featNameJa(featType: string, name: string): string | undefined {
  return FEAT_NAMES_JA[featType]?.[name];
}
